### ISSUE TITLE
「裏」 在 I.MingCP 中的字形比在 I.Ming 中的好，更清晰

### ISSUE THREAD

**Issue by creatxrgithub** [ichitenfont/I.Ming#1]
「裏」 在 I.MingCP 中的字形比在 I.Ming 中的好，更清晰。
希望下次更新時能把 I.Ming 的 Glyph 給替換一下

**Comment by i-font** [comment]
你好，經過硏究應該只是顯停（Hinting）的問題，兩者字形外框是一樣的。
感謝你的意見！^^
