### ISSUE TITLE
6.0版本中缺少了標點置中的版本

### ISSUE THREAD

**Issue by hingbong** [ichitenfont/I.Ming#10]
你好，6.0版本中缺少了標點置中的版本，不知會否添加上呢

**Comment by SyaoranHinata** [comment]
您好，首先謝謝閣下的意見。正如我們在I.Ming的首頁所說，日後會補上的。不過，我們的目標，是提供符合傳承字形字樣的字型，標點卻不是我們的主力及擅長範圍。本身我們的專門處理範圍在於漢字字形，我們並不懂得寫程式或應付因程序而生的問題。在6.0版本發佈前，我們就只因爲十數個標點問題，被OpenType技術等不斷折磨又折磨，擺平了一個問題卻又自動生了另外的問題，反來覆去，浪費了很大量的時間，令我們丟下了確保字形一致正確的本業，白白推遲了新版的面世時間。因此，現在再設置標點置中的版本，等於要把我們的弱項再重來一次，所以確實需要時間，希望閣能能諒解和海涵。

請容我在此趁機會呼籲：若閣下或各位網友擅長處理甚麼OpenType特性之類的這方面，在下強烈希望您能加入我們的工作團隊。先行拜謝！

**Comment by i-font** [comment]
目前已經有：

- 「I.明體」（I.Ming）：收錄力求遵從字理的傳承字形。
- 「I.明體CP」（I.MingCP）：與「I.明體」一樣，唯全形標點置中。
- 「I.明體異體」（I.MingVar）：部份漢字改爲收錄一些也常見，但字理上未必比上者佔優的傳承字形。
- 「I.明體異體CP」（I.MingVarCP）：與「I.明體異體」一樣，唯全形標點置中。
