### ISSUE TITLE
8.0豎排時橫臥

### ISSUE THREAD

**Issue by groverlynn** [ichitenfont/I.Ming#100]
Mac的舊版TextKit（MacOS 12.0以前）需要vertical metrics來旋轉字符。7.1及以前的版本沒有問題，8.0版刪去了之後，在舊版TextKit中無法正確顯示：
7.01正確旋轉
<img width="24" alt="Screenshot 2023-06-23 at 23 41 03" src="https://github.com/ichitenfont/I.Ming/assets/14979243/283d41fd-5c3b-4768-bcf2-a93ea9f6e771">
8.0因為沒有vhea和vorg而無法識別vertical form
<img width="32" alt="Screenshot 2023-06-23 at 23 41 54" src="https://github.com/ichitenfont/I.Ming/assets/14979243/5619dc1b-18e2-4827-9d01-3e90900643b2">

**Comment by i-font** [comment]
請問此問題已解決了嗎？

**Comment by groverlynn** [comment]
> 請問此問題已解決了嗎？

不算解決，但是發現只要不強制設定為使用豎排字符（vertical glyph form），8.0就不會過度旋轉了。而7.0則是無論是否設定為豎排字符，在豎排模式下均能直立。
