### ISSUE TITLE
敻 as 八 instead of 人 inside 冖

### ISSUE THREAD

**Issue by epistularum** [ichitenfont/I.Ming#101]
The reference pdf of inherited glyphs represents the 敻 component as having the shape 人 inside the top 冖 but from what I understand the original shape is 穴 like seen in 奐. The 奐 shape actually provides an alternate form with 人 in the I.MingVar font file but no such alternate form is available for 敻.

**Comment by i-font** [comment]
感謝意見。其實「敻」字的構理未明，學界尚在硏究中，沒有很主流很一致的意見確定它是否从「穴」。而且它跟「奐」的上方字源是否相同，目前也尚未釐清。而我們在採樣過程中，看到「奐」字內作「人」之形與內作「儿」之形皆常見，「敻」卻不然。因此我們從取樣結果。目前我們並不會修改「夐部件」。
