### ISSUE TITLE
Some stylistic discrepancies

### ISSUE THREAD

**Issue by epistularum** [ichitenfont/I.Ming#103]
鬣:
Lower part of 鼠 connecting to the upper component in one single instance.
The character on the right is only there for comparison:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/3b88aa87-51c0-49a8-92f9-02ff40237267)

䣟嶜朁潛簪蠶鬵㿊𠓸𢑋𥸢𧌩𧕽𧖛𩀿𩅨𮆪:
𡉙𢙴𢛭𣄮𣄱𥬗𨙐𮎁:
Lower right part of 旡 connecting to the upper part in some instances. (The connecting/non-connecting is inconsistent between the main I.Ming font and the Var font.)
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/17f820b4-c35e-47f8-948e-062447a6c459)
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/2cc9232b-3aeb-4751-bd6b-0f1f5c44490d)

䣟:
The upper left part of 旡 connecting and forming an angle in this one character in the Var font file.
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/0b4ea09a-ef75-46d8-8842-88dc47577e4f)

爗:
The lower 艹 part of 華 is connecting to the upper/lower strokes in this one character in the Var font.
The character on the right is only there for comparison:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/f7e17f38-ba7b-4fc0-9e2c-a978a68d2deb)

螱:
The stroke style of the third stroke of 示 is wrong in the regular I.ming font AND is connected to the upper stroke in the Var font file.
The character on the right is only there for comparison:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/d028891f-4860-4e14-81b1-5fda22ae0d81)

䓈𣪯𭮫𭮳𭮴𭯃𭿩𮇩𮬙:
The top part of 殳 ending with a flick instead of stopping.
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/bd09fa74-ce04-4983-8c1f-09d3dc0a449e)

鳔:
The simplified component 鱼 魚 is changed to traditional 魚 shape in the Var font.
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/630be419-0449-40a4-ba1e-dddf618ba147)

**Comment by i-font** [comment]
感謝閣下仔細的比對和意見。很多都很可取，我們將在未來的版本修改。

說說我們考慮後會作爲例外的：

★ 兓部件
要是「乚」筆必須與上方分離，將會造成字形上失去平衡。因爲把「乚」筆的豎部份斷開的話，必須騰出空間放上明體豎筆開首的「![圖片](https://github.com/ichitenfont/I.Ming/assets/24702034/b66a57fd-f4e3-4abf-9894-2d8c99fbf121)」形，這可能令此筆要下移，上方的橫筆也要上移。然而許多「兓部件」本來就空間有限，不得不長得矮，「乚」筆可以享有的空間比「鬣」下方的「鼠腳」還矮小，已沒有再多的空間可以騰出來。而「乚」筆是否與上方相接，本來跟字理沒什麼關係。因此在諮詢過字型設計師朋友的意見和綜合考慮後，這批字中若有妨礙美觀者，如「𥸢」等，則不會修改。

★ 隸定字
個別隸定字，實爲依篆文、古文或其他古代文字之形而隸定，雖隸定後某部份形塊跟常用部件形同，實不同源，字理上不應相混。如「𡴗」不从「呂」，實爲「叀」之古文「![圖片](https://github.com/ichitenfont/I.Ming/assets/24702034/255d9a14-228c-4809-840d-c48fba9a772a)」之隸定，兩圓之間的連接筆畫不應移除。「𣓡」字亦然，不依「呂部件」之規則。

★ 訛字
個別訛字，字理不可考，或者絕大部份文獻都不使用它，而會使用正字，確實用它時是取其訛形，甚至同時是不同字的訛混形體，則未必更改。又如「𨙐」和「𭅺」的「新字形皀」部份，目前暫且保留。
