### ISSUE TITLE
Incomplete support of 異体 in Var font

### ISSUE THREAD

**Issue by epistularum** [ichitenfont/I.Ming#104]
# 肅
𦪲𩙚:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/4ef78fef-9467-4d55-a676-e2736308d005)

# 鼠
鿻鿼䉭𣋲𧞪𪕟:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/9a10e24d-261b-4a28-afc9-b7cc48682a22)

# 兓
𠎱𠓸𢑋𣠟𣾤𤾶𥸢𧌩𧕽𧖛𧝆𨅔𨼐𨽨𩀿𩅨𩱠𩻛𪅽𪖼𮆪:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/656bd6fb-4e6f-4d0d-86d0-dec33e2122a4)

# 直
嗭𠪫𡌴𡸜𢃜𢏶𣇣𣚅𣤳𥜩𥮖𦋘𦷔𧄗𧡚𨁷𪙳𫒦:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/d9f8689c-8a8a-4d1e-827f-781549f332e6)

# 朗
𠘄𭅺:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/73e54801-6365-472f-8c05-7cd0e05a82c5)

# 夬
𥝭𫘝:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/12aeb825-16d4-48a3-b636-5c052285aec8)

# 罒
䎱𪙳𮈣𮊒𮢟:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/c47227ee-3f4e-4753-85a7-ee319e3266b3)

# 吳
误:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/5e6892f2-8bc4-48a5-9dcd-538c5a03376e)

# 呂
𡴗𣓡𭂴:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/872187ae-2bb7-46e8-a627-36af3699e39a)

# 肖
绡蕱𭙱:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/6419a76a-54bd-40b8-b76d-81f69a7c2312)

# 衰
缞:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/33889a19-6440-4315-a714-b56494f4d6bb)

# 票/𫵖
幖缥𮊘:
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/f57cc918-ec92-426a-aeed-bae75d81f245)

**Comment by i-font** [comment]
感謝閣下仔細的比對和意見。很多都很可取，我們將在未來的版本修改。

說說我們考慮後會作爲例外的：

★ 𦪲
——右旁的「⿻肀⿱𠆢𣶒」中，「𠆢」已等同「肅」異體多出的那一橫，寫成「𠆢」形只是篆書隸定的問題。因此不會再多加一橫，不然會架牀疊屋。

★ 兓部件
見#103。

★ 隸定字
見#103。

★ 訛字
見#103。
