### ISSUE TITLE
Inconsistent shape of 儿 when on the left

### ISSUE THREAD

**Issue by epistularum** [ichitenfont/I.Ming#106]
The shape of 儿, when on the left, is inconsistently a "豎曲鈎" or "豎挑".

The "Stroke of Inherited Glyphs" documents does say that it can happen, but not why. Shouldn't it be the same everywhere?

"複合筆畫。先作「豎」，收筆處再拐個逆時針的「曲」，尾部變作折，再作向上的「鈎」。例字如：允、乳、毛、己。注意：若「儿部件」在字中間空間不足的地方，或會避讓變作「ㄦ」，即「豎曲鈎」變爲「曲」，如：𧶠、坴、畟、酉。另外，末筆爲「豎曲鈎」的部件居左旁，或會避讓變作「豎挑」，如：邨、頹、改、刓。"

Little sample of characters containing 元 or 光 on the left.
耀輝辉㒯𠓋𠓌𢼯𦥿𧇲𩒚𩳁𪀯𪕗𭀨𮋚刓衏邧頑顽鵍㪴䲮𢽉𤻆𭶌
![image](https://github.com/ichitenfont/I.Ming/assets/34507493/2965d2fd-c4f5-4de6-8e1a-3ca97847d981)

**Comment by SyaoranHinata** [comment]
這點主要是美觀需求問題，個別字也視乎該字的習慣，不影響字理字源。因此就不勉強統一。
