### ISSUE TITLE
I.Ming-8.00.ttf 在 macOS 13.1 上安装失败？

### ISSUE THREAD

**Issue by lumeng** [ichitenfont/I.Ming#107]
macOS 13.1打开 Font Book.app，将　I.Ming-800.tff 拖入，报错「No Installable Font Selected」：

![screenshot_2023-08-08_13-54-25](https://github.com/ichitenfont/I.Ming/assets/629326/090167fc-c974-406a-b675-1445fdecc265)

又试了把 I.Ming-800.tff 放入　~/Library/Fonts/ 后重启电脑，无法调用字体，猜测没能正确识别。怎么回事？

**Comment by TNTErick** [comment]
安裝其他字體是正常的嗎？

**Comment by lumeng** [comment]
装 7.0 版可以。

**Comment by groverlynn** [comment]
`.ttf` 不是 `.tff`確定沒有拼錯？

**Comment by lumeng** [comment]
Fixed.
