### ISSUE TITLE
康熙部首部分似乎不都是康熙字典写法？

### ISSUE THREAD

**Issue by MY1L** [ichitenfont/I.Ming#111]
想寻找一款康熙字典写法的开源字体用于展示那些属于“康熙部首”的字符。
测试文本：⼇⼎⼜⼧⼪⼬⽂⽆⽎⽓⽗⽠⽰⽳⽻⾆⾑⾗⾣⾱⾳⾵⾷⿆⿇⿌⿍⿐⿓⿔
比如其中⼪`u2F2A`字形应类似𡯁`u21BC1`，等等。

原指望本字体的：
![image](https://github.com/ichitenfont/I.Ming/assets/58043328/a39c49a7-8245-425d-804c-ad8fb140232a)
但发现与扫描样本相比（如题）
![image](https://github.com/ichitenfont/I.Ming/assets/58043328/7f731f9e-7beb-44a5-bc83-8eb61413245b)
我只好自制一套了（改自思源宋）
![image](https://github.com/ichitenfont/I.Ming/assets/58043328/3fdc1492-5771-463f-82ca-68d699d0ebde)

**Comment by i-font** [comment]
感謝閣下的意見。
本字型依據[《檢校表》和《推薦形體表》等標準化文件](https://github.com/ichitenfont/inheritedglyphs)，表中審視過《康熙字典》的字形，依據字理，也同時在不礙及約定俗成和字型美觀設計的條件下，作過好些審訂。因此不會全依《康熙字典》的字形。詳情已在標準化文件中細述。謝謝！

**Comment by i-font** [comment]
您好，
對於漢字的部首和筆畫區域，我們還是盡力沿用[《檢校表》和《推薦形體表》等標準化文件](https://github.com/ichitenfont/inheritedglyphs)的規定，除非另有特別需求。因爲它們也是漢字的元素。

**Comment by aikahiiragi** [comment]
樓主的掃描本有些問題

例如麥，是![image]()，不是![image](https://github.com/ichitenfont/I.Ming/assets/37748071/aba4b579-2640-4e22-b977-3b0dd902f2be)



![image]()
![image]()

**Comment by aikahiiragi** [comment]
樓主的掃描本有些問題。

例如：
麥是![image](https://www.kangxizidian.com/kxzt/7000s/7246-01-39637-9EA5.svg)，不是![image](https://github.com/ichitenfont/I.Ming/assets/37748071/2ba954c5-6a1b-465e-ab14-b2920d3c58cc)
*夂部件變成夕部件，是嚴重錯誤。

豕是![image](https://www.kangxizidian.com/kxzt/5000s/5716-01-30324-8C55.svg)，不是
![image](https://github.com/ichitenfont/I.Ming/assets/37748071/a4c7a808-87f4-46a9-a303-9d66dc7a6167)
*這算是筆畫黏合或位置的設計小差異，不視作對立，是可以兼容的，檢校表已說明這點

气是![image](https://www.kangxizidian.com/kxzt/2000s/2862-01-13732-6C14.svg)，不是
![image](https://github.com/ichitenfont/I.Ming/assets/37748071/e9220962-e4cf-4651-8c8a-ad0d62b12613)
*造型分別，但「一點明體異體」有這種造型

另一方面如果要嚴格依照樓主的掃描本，甚至連已說明是不視作對立的設計小差異也要依從，其實在「一點明體異體」的漢字中也包含了不少，要改造的話可以利用它，不必用「思源宋」來改。尤其是有一些地方，「一點明體」是重視了那些分別的，但「思源宋」是忽視的，就例如樓主例子裏的![image](https://www.kangxizidian.com/kxzt/6000s/6680-01-35902-97F3.svg)，在「一點明體」裏下方的「曰」是清晰的，但樓主借用「思源宋」就跟「日」混同不分了。

康熙掃描本參考： https://www.kangxizidian.com/

**Comment by MY1L** [comment]
@aikahiiragi 这些扫描字形是别人提供的。与提供扫描字形的人聊了下，发现一件尴尬的事：在你给的“康熙掃描本參考”链接里，你指出的4个部首确实有这么写的，即麥的夂写作夕……比如：https://www.kangxizidian.com/v2/index.php?page=66#gv
![image](https://github.com/ichitenfont/I.Ming/assets/58043328/1c6a260b-b238-47c1-8117-a9368da22f4f)
![image](https://github.com/ichitenfont/I.Ming/assets/58043328/9fbf061b-b914-414f-abb1-0d05e72a143a)

考虑到统一码的“康熙部首”区段实际上不作汉字用途，而是字典排序用途（即“一部之首”），那么它可以故意与汉字不一样，以示区分，实际上我自制的字体用途就是从网上的那些文字里快速找出不应该存在于文中的康熙部首。

**Comment by i-font** [comment]
感謝閣下的意見，綿飴閣下對字體設計的努力是我們有目共睹的，閣下提供意見我們也經過審慎的考量；事實上前些日組織內部也有人提到這個建議，並加以討論。但是我們想，一點明體的目的在傳承字形而並非排版、檢查字符差異，也存在許多能區分的字體與工具，如[漢字關聯可視化計畫]([https://garywill.github.io/cc-visualize/](https://garywill.github.io/cc-visualize/?fbclid=IwZXh0bgNhZW0CMTAAAR35Sb2joa_Uw3bqq7i6n-3hXJRi8GWycXivLFuifglQfqXheXbAU34T5DU_aem_ASWoBz1qNgiaCOqSyzzwB50oFMcQy6UE1Uwtxk_TqI1WK4xCDKWAGbTFCms9zODy3L9Q8PE4RXZvQNzsd60SUpvt))用意就是區分異碼同形字。又，康熙部首本就取之於該部之漢字，即使沒有65535字符限制，我們可能還是會合併二碼。

與閣下意見相左，還請諒解。但若閣下有需要，歡迎叉取，進行改作。

**Comment by aikahiiragi** [comment]
> @aikahiiragi 这些扫描字形是别人提供的。与提供扫描字形的人聊了下，发现一件尴尬的事：在你给的“康熙掃描本參考”链接里，你指出的4个部首确实有这么写的，即⿆的夂写作夕、乞字形的⽓……比如：https://www.kangxizidian.com/v2/index.php?page=66#gv

原來是在「總目」中查出來的，可是「總目」的字形比不上正文般可靠，正文也不單是單字，而是同時列出「X部」那裏的部首。我認為「總目」字型有不同是雕刻匠和校對的疏忽，沒有理由依據疏忽出錯的字形而放棄比較嚴謹的字形，這不是正確的態度。

（我個人言論只代表我個人意見，不代表一點字形官方）

![image](https://github.com/ichitenfont/I.Ming/assets/37748071/86031e2d-1595-4aa3-9cfe-1398004dfe7a)
![image](https://github.com/ichitenfont/I.Ming/assets/37748071/de766223-5e51-4e78-8c77-f67e7e6453e5)
![image](https://github.com/ichitenfont/I.Ming/assets/37748071/9cf8ff5f-a3e3-45ce-b6f4-a6b6c9e27486)
![image](https://github.com/ichitenfont/I.Ming/assets/37748071/340ea796-de6e-4618-8c30-82358b20ba27)

**Comment by MY1L** [comment]
@aikahiiragi 我觉得一點明體将康熙部首与汉字复用字形以节省字体文件体积是合理的，倒没有意见，当然我觉得⼪字形适合复用“𡯁`u21BC1`”

至于我的字体作区分则是出于实用目的，思源原有的汉字并不会改动，也就不会“放棄比較嚴謹的字形”，毕竟你也不会故意在一般文章里拿康熙部首充当汉字吧。
你的意见是「康熙總目」相比“康熙正文”写法不对（虽说一點明體也对“康熙正文”不完全赞同），而我觉得出于交流描述目的（就像刻意用于区分的“⻌⻍⻎”）可以加上实际存在的“不对”写法，考虑到即便与汉字完全重复，统一码仍收录康熙部首区段有其特定的设计用途，放置实际出自康熙總目的字形似乎是合理的，不会妨碍使用者的选择。

> 关于交流描述目的，我有个设想是字体使用者可以在文中直接描述：“气不应该写作⽓”，而不用麻烦地比方“气的㇤（笔画hzxg`u31E4`）不应该写作㇠（笔画hxwg`u31E0`）仿佛乞字一般”

——不过话说回来，[康熙字典也说“气乞本同一字也”“省一笔以别之”](https://www.kangxizidian.com/v2/index.php?page=2862)，说不定气写作乞字形也不一定错🤔
