### ISSUE TITLE
建議統一不同編碼的“⻍“部件。

### ISSUE THREAD

**Issue by DevoteToStudy** [ichitenfont/I.Ming#113]
《傳承字形標準化文件 ・傳承字形部件檢校表・⻍部》曰：

> 傳承字形作四筆，首兩筆爲頓點，第三筆爲橫豎，末筆爲挑扁捺。不作「⻌」、
「⻎」或「⻎」，更絕不可作「辶」

然而，⻌、⻍、⻎三箇編碼不同的辵部件在一點明體（包括異體）字形並未統一爲舊字形的“⻍“，而是有兩箇新字形。建議統一爲“⻍“。
![統一部件](https://github.com/ichitenfont/I.Ming/assets/154590102/8dcde7a0-7317-4bcd-93ba-e8a1c22312a2)

**Comment by MY1L** [comment]
随手一查“⻌⻍⻎”这3个不是汉字，不需要符合檢校表；而“辶”这个汉字已符合檢校表了。

老实说你似乎没懂，“⻌⻍⻎”这3个字符是故意做成这样的（请阅读统一码文档：https://www.unicode.org/charts/PDF/U2E80.pdf ），不然你引用的那句就会显示成：

> 傳承字形作四筆，首兩筆爲頓點，第三筆爲橫豎，末筆爲挑扁捺。不作「⻍」、「⻍」或「⻍」，更絕不可作「⻍」

如上这样很搞笑的一句话。

**Comment by DevoteToStudy** [comment]
> 随手一查“⻌⻍⻎”这3个不是汉字，不需要符合檢校表；而“辶”这个汉字已符合檢校表了。
> 
> 老实说你似乎没懂，“⻌⻍⻎”这3个字符是故意做成这样的（请阅读统一码文档：https://www.unicode.org/charts/PDF/U2E80.pdf ），不然你引用的那句就会显示成：
> 
> > 傳承字形作四筆，首兩筆爲頓點，第三筆爲橫豎，末筆爲挑扁捺。不作「⻍」、「⻍」或「⻍」，更絕不可作「⻍」
> 
> 如上这样很搞笑的一句话。

明白，sorry！
