### ISSUE TITLE
建議美化字圖設計，以更好地彰顯傳承字形之美。

### ISSUE THREAD

**Issue by ghost** [ichitenfont/I.Ming#114]
竊以爲，新版細明體（MingLiU）及新細明體（PMingLiU）雖然在字形及字理上幾無可取之處，但是在字圖設計上比較美觀。例如“丨“這個筆畫的末端，細明體設計得比較**圓潤**；而一點明體設計得過於平直，顯得比較生硬——**這有可能會破壞字體使用者的視覺體驗**。
所以我想提一箇建議：將一點明體的那些比較平直的豎畫或垂直斷筆末端變得圓潤一些，讓字不顯得過於死板。
P.S. 如果足下覺得這樣工程浩大，沒有人手或者沒有必要如此講究，可以直接關閉（close）這個問題反饋（issue）。
打擾了。
![豎](https://github.com/ichitenfont/I.Ming/assets/154590102/a3892db0-b8fd-4776-9f06-217b72cdf95f)

**Comment by DevoteToStudy** [comment]
我只不過是覺得筆畫字圖設計如果學習一下細明體會使傳承字形的美感體現的更加淋漓盡致，沒有別的意思。

**Comment by laabaafu** [comment]
我也覺得將「丨」正面的的直角改成圓角比較好，但並不是細明體的那種

**Comment by DevoteToStudy** [comment]
> 我也覺得將「丨」正面的的直角改成圓角比較好，但並不是細明體的那種

感謝你將我想要表達的意思精準地說出來了！

**Comment by i-font** [comment]
您好，感謝您的意見。若要做到這一點，每一個字圖都要人手更改，以我們的人手來說，確實是不可能的任務，還望見諒。

不過，有關字型風格的問題，我們在挑選字型之前已充份諮詢了設計師專家，並不認爲IPA明朝體這種設計會破壞字體使用者的視覺體驗。

即使是明體，當中也可以細分多種風格。IPA明朝體這種是現代風格，講求爽朗、平正，只要骨架美觀，呈現出來就如此，不用多餘的修飾。但這並不等於死板。相比起有些字型呈現出的是僵硬，連骨架本身也沒有柔度，中宮盡力放大，一點明體並沒有走這條路線。IPA明朝體融合幾何直接感，以及適合的中宮、撇捺的弧度等，列印出來或者在屏幕顯示時，即使是很小的字，也保持良好的可讀效果，不會有多餘的雜點。IPA明朝體的豎筆也比細明體/新細明體略粗，使它作爲一般正文文字使用時不至於太細。綜合來說，IPA明朝體在視覺體驗上是上乘的。

誠然，也有朋友就是喜歡字型裏有更濃厚的人文感覺，不喜歡現代、幾何感。不過單單是筆畫結尾的方角改成圓角，並不會對提升人文感覺有很大的影響。樓主以細明體/新細明體來對比，然而專業的字型設計師正正指出過細明體的造型，來自掃描照相植字字體本蘭明朝L，直接變成數碼字型檔。但本蘭明朝L本來是照相植字字型，在照相植字裏，因爲照排機鏡頭拍攝玻璃板上的字型時所產生的光學誤差，本來會呈現出邊緣模糊柔化，細明體/新細明體的製作者不處理這方面，就把本蘭明朝L的圓潤、清晰變成乾枯。

因此，若有朋友喜歡濃厚人文感覺的明體，推薦大家可以使用空明朝體的傳承字形版本（可以利用Opentype切換成傳承字形版），或者森澤的龍明體（リュウミン，但可能只有日文寫法）等字型。
