### ISSUE TITLE
關於「龝」字字形

### ISSUE THREAD

**Issue by 1tseug** [ichitenfont/I.Ming#115]
我剛發現「龝」字（U+9F9D和U+418B）的右邊上面部分在一點明體顯示的是「卝」，而在其他字體顯示的是「𠂊」，請問是有什麼說法嗎？
<img width="78" alt="螢幕擷取畫面 2024-02-17 001529" src="https://github.com/ichitenfont/I.Ming/assets/160258071/04695a97-a69a-4786-a1f6-0fcaecb1d194">
<img width="76" alt="螢幕擷取畫面 2024-02-17 001803" src="https://github.com/ichitenfont/I.Ming/assets/160258071/f6d788f3-1877-459a-aee3-ae7ea523a785">
<img width="1277" alt="螢幕擷取畫面 2024-02-17 001939" src="https://github.com/ichitenfont/I.Ming/assets/160258071/6459aaee-1e9b-4d18-bf32-8f6be3f85c97">

**Comment by SyaoranHinata** [comment]
您好！此即「秋」字，初文爲「𬟏」（![image](https://github.com/ichitenfont/I.Ming/assets/8178284/b73faa98-9c2c-48a4-8147-b47c1e10299d)），蟋蟀類昆蟲，秋天出滿至盛。後或加「火」於其下（以「火」燒之、驅之），或加「禾」於其旁（此害蟲食熟禾），或「火」與「禾」同加。再後來，人不識「𬟏」，常用形體省之作「秋」，非常用形體則將「𬟏」訛寫作「龜」，實魯魚亥豕也。考慮到「𥤚、𪛁、龝」等字並非常用字，依程序詢問後，普遍不認爲扶正這個較少見的字形會很影響辨讀或約定俗成，故從其本也。願能解君惑，祝安康！

**Comment by 1tseug** [comment]
感謝解答！

**Comment by SyaoranHinata** [comment]
季旭昇敎授《說文新證》
![image](https://github.com/ichitenfont/I.Ming/assets/8178284/04c44230-955e-4145-b3e5-ff9c537a2ad9)
