### ISSUE TITLE
關於字形「皆，𣅜」及其相關字的問題

### ISSUE THREAD

**Issue by treemoons** [ichitenfont/I.Ming#116]
當我使用時發現，衹有在5.0版本中使用從'白'的「皆」，之後更新爲從'曰'的「𣅜」。
我又查詢字典以及文說，似乎「皆」字更符合傳承字。
請問是做何考量，將5.0版本使用的「皆」更新爲「𣅜」作爲後續版本字形的？

**Comment by SyaoranHinata** [comment]
感謝提問。
皆部件在《傳承字形部件檢校表》上已有說明，可參之。
其字字理上應從「曰」，雖然增撇者似乎較常見，經抽樣調査，結果認爲恢復從「曰」也不影響辨讀和習慣，故從之。
若眞的有必要使用從撇者，可以用「一點明體異體」，收錄了於「曰」上增一裝飾撇筆（非從黑白之「白」）之形。
因人手和時間等因素，舊版本有時尚有疏失之處，請以新版本爲準。舊版僅供歷史紀錄與硏究用。謝謝！
