### ISSUE TITLE
小寫注音符號「ㆴㆵㆷㆻ」應在漢字方框水平置中（新一細明體）

### ISSUE THREAD

**Issue by 307587** [ichitenfont/I.Ming#117]
爲整齊對稱起見，請將小寫注音符號「ㆴㆵㆷㆻ」在漢字方框由左下改成下方水平置中：
（原文從維基抄到MSword顯示）![20240301　新一細](https://github.com/ichitenfont/I.Ming/assets/146841109/c3077086-5311-41ed-8429-d2fbb7d582c2)

**Comment by SyaoranHinata** [comment]
但這幾個符號是入聲的輔音韻尾，就是要寫在左下方的啊。

**Comment by 307587** [comment]
不可改到中下嗎？中下才對稱啊，而且這些注音法也通常有聲調在後，小寫注音符號放左下看起來好像想提早寫完一樣。
（順帶一提，我記得有款東亞字體全形標點就是放中下，不是正中也不是左下）

**Comment by SyaoranHinata** [comment]
[《一點明體功能記錄》](https://github.com/ichitenfont/I.Ming/blob/master/8.10/I.Ming_functional_report_8.100.pdf)已清楚說明如何正確顯示有關的注音符號。請敬參閱。
不同地方的注音方案，對相關符號的顯示規定也有不同，我們已努力硏究出能適用於不同規定、不同方案的方法。
