### ISSUE TITLE
關於簡化字“当”（當）及相關字的問題

### ISSUE THREAD

**Issue by VentusUta** [ichitenfont/I.Ming#121]
若依《檢校表》附錄三，“当”或許應依“尚部件”“⺕部件”的字形作“𢑐”（U+22450，<img width="26" alt="image" src="https://github.com/ichitenfont/I.Ming/assets/135337676/f1e2b30a-53b8-4912-aa5d-b8cfe1e27ea0">）形，但在一點明體8.00版中卻都作“反向小+不出頭⺕”形，這是有意爲之還是未作修改？

受影響的字有：
当挡铛珰档筜垱裆㓥

於一點明體8.00版中的字形：
<img width="113" alt="image" src="https://github.com/ichitenfont/I.Ming/assets/135337676/ce2eea7b-d8a3-4588-bd67-4af76e39f9d7">

如果能得到解答的話，非常感謝。

**Comment by SyaoranHinata** [comment]
感謝意見。
按字理，「⺕」是一隻手，而「當」與手無關，乃整字訛寫而來。
既然是整字訛寫，難以彰顯字理，我們經過商議，就決定不特別地校訂其字形。
