### ISSUE TITLE
將該字型的品牌英文名由 ichiten 更為 itten。

### ISSUE THREAD

**Issue by ShikiSuen** [ichitenfont/I.Ming#123]
「一點」這兩個字的日文羅馬音分開唸是「ichi」與「ten」，但合併時的讀音是「itten（いってん）」而非「ichiten」。
用日語輸入法敲ichten能敲出來「一點」，但不見得日本人平時會經常這麼唸。

**Comment by enderseven1** [comment]
這個項目的發起者並不是日本人吧？日本人怎麼念也沒關係
