### ISSUE TITLE
『稽』的起筆一撇或有問題

### ISSUE THREAD

**Issue by GrimPixel** [ichitenfont/I.Ming#124]
![䅲](https://github.com/ichitenfont/I.Ming/assets/39795763/75762612-4810-473a-b47e-40ca2e5ec289)

**Comment by Egnale99** [comment]
請問「稽」字首撇具體有甚麼問題呢？

**Comment by GrimPixel** [comment]
『稽』的禾字旁與其他禾字旁字的禾字旁相比，本無特別之處。這是其他幾箇禾字旁字：
![稱](https://github.com/ichitenfont/I.Ming/assets/39795763/e39b17c0-9517-432a-addb-eae7cff1dfaa) ![稻](https://github.com/ichitenfont/I.Ming/assets/39795763/071b3b17-0ff9-4970-ab10-95dbce87b1b5) ![稿](https://github.com/ichitenfont/I.Ming/assets/39795763/2d06f561-f812-435e-a870-05d61180f4d6) ![穆](https://github.com/ichitenfont/I.Ming/assets/39795763/b8ddc71f-b72c-4118-9788-61297b8c956f)

**Comment by Egnale99** [comment]
> 『稽』的禾字旁與其他禾字旁字的禾字旁相比，本無特別之處。這是其他幾箇禾字旁字：
 ![稱](https://private-user-images.githubusercontent.com/39795763/335616514-e39b17c0-9517-432a-addb-eae7cff1dfaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjk0MjAsIm5iZiI6MTcxNzE2OTEyMCwicGF0aCI6Ii8zOTc5NTc2My8zMzU2MTY1MTQtZTM5YjE3YzAtOTUxNy00MzJhLWFkZGItZWFlN2NmZjFkZmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE1MjUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5ZDI4MzBkMzk2ZGMzMTU3NGY4NTBjOTdjZDg1N2IzYWNiNjE5Yzg3YTdhZWE0NzZhZDQxMDBjNTZhNTk5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.10JSSfBOXQc-1T4GfZUw-kXlHInwPRYEUq7pp4fFKvw) ![稻](https://private-user-images.githubusercontent.com/39795763/335616523-071b3b17-0ff9-4970-ab10-95dbce87b1b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjk0MjAsIm5iZiI6MTcxNzE2OTEyMCwicGF0aCI6Ii8zOTc5NTc2My8zMzU2MTY1MjMtMDcxYjNiMTctMGZmOS00OTcwLWFiMTAtOTVkYmNlODdiMWI1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE1MjUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhNGVjNmEzNjA4NjA2MmZkYmRlYTY4NzNjMzQyZjA1YjM2M2JhYmE2OWY4YzQ3OTEyMGY1ZjJkNzhhYWUwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z2kxNxPspV5I4Iaw_SovzZlC4df9P8zE-b_cxudfnWo) ![稿](https://private-user-images.githubusercontent.com/39795763/335616528-2d06f561-f812-435e-a870-05d61180f4d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjk0MjAsIm5iZiI6MTcxNzE2OTEyMCwicGF0aCI6Ii8zOTc5NTc2My8zMzU2MTY1MjgtMmQwNmY1NjEtZjgxMi00MzVlLWE4NzAtMDVkNjExODBmNGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE1MjUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NGFhMzI0NGNmZTEyMDY5NjA4M2YzMmExNTc1ZTU2MzhjN2NkYmVmZTNhODkzNmVkY2NmNzExYjA0OTIyODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FbC7uVdeCBLi8lzWzWLwNlfuK8T9PICxbRtNc_pJRJw) ![穆](https://private-user-images.githubusercontent.com/39795763/335616531-b8ddc71f-b72c-4118-9788-61297b8c956f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxNjk0MjAsIm5iZiI6MTcxNzE2OTEyMCwicGF0aCI6Ii8zOTc5NTc2My8zMzU2MTY1MzEtYjhkZGM3MWYtYjcyYy00MTE4LTk3ODgtNjEyOTdiOGM5NTZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDE1MjUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwNmEwZjc4YjAxM2Q5ODQwOGNiOTY3MTVlM2U0NDk0NmIzZjAzNzVhODk3MmRlYTQzYzAzNzg2MDYxYmU2MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0LdxIpBkBVkcOFGtksBmPmzdrnOK4TGW_fXDERJRVSo)

其實「稽」字理上不從「禾」，而是撇筆不穿頭的「𥝌」。《傳承字形部件檢校表·表二：近形須區分部件》亦提及「禾」、「𥝌」兩者的分別。
![image](https://github.com/ichitenfont/I.Ming/assets/64576145/3287de3a-0737-4ac6-b8cd-d8f266cace44)

另外，「一點明體異體」的「稽」（U+7A3D）從「禾」形；「𥠻」（U+2583B）仍從「𥝌」。

希望以上內容能解答閣下的疑惑。

**Comment by GrimPixel** [comment]
受敎，在此謝過了。
