### ISSUE TITLE
關於（習）與（皆）字

### ISSUE THREAD

**Issue by YongjiuHexie** [ichitenfont/I.Ming#126]
請問爲何於一點明體中，習，皆及其類推字之下皆作“曰”而非“白”？鄙人知曉二字古時有所溷淆，爲何又於一點明體異體中又改回作“白”？望求解答。

**Comment by YongjiuHexie** [comment]
@i-font 請問在製此二字時其中是否有何特殊考量？

**Comment by i-font** [comment]
這些字，一點明體依《檢校表》海字，異體依陸字。相關問題在《檢校表》中已有說明。請參閱《檢校表》「習部件」及「皆部件」條。
https://github.com/ichitenfont/inheritedglyphs

**Comment by YongjiuHexie** [comment]
> 這些字，一點明體依《檢校表》海字，異體依陸字。相關問題在《檢校表》中已有說明。請參閱《檢校表》「習部件」及「皆部件」條。 https://github.com/ichitenfont/inheritedglyphs

感謝您百忙之中抽空作答！拜讀上述檢校表後，獲了些自己學古字時未有觸及的內容。眞的非常感謝！
