### ISSUE TITLE
「庸」字形，似乎沒有按照字源進行區分

### ISSUE THREAD

**Issue by treemoons** [ichitenfont/I.Ming#128]
經過查找「檢索表」等相關文件，均沒有找到關於「庸」的詳細解釋。
字形「庸」按字源第一筆應爲短橫，而非豎點，不應從「广」。
這是當前版本的字形。

![image](https://github.com/user-attachments/assets/b8f115df-3769-4b08-91f3-f363868eaa62)

而查閱相關資料：

![image](https://github.com/user-attachments/assets/c1d096b8-dbbc-4a3f-8eb4-c070eebec954)

![image](https://github.com/user-attachments/assets/286ca554-5547-49b3-adec-34d009febd16)

![image](https://github.com/user-attachments/assets/0f0c39ea-81f0-4756-bd38-33b6d9e945c0)

均以短橫居多。

若要以豎，應一筆至底部與之相連，而非斷開。

**Comment by Egnale99** [comment]
閣下能發現「庸」字在字源上不從「广部件」，是一件好事。然而並不等於**今時今日**「庸」字就應該據此改形。

原因非常簡單：**後世的明體、黑體等一般的印刷字體**都沒有首筆從短橫的寫法。雖然閣下指出「均以短橫居多」，卻都不是在明體中採樣，其實有違《檢校表》、《推薦形體表》從**傳承明體**挑選、釐定形體的做法。《檢校表》版本 1.37，第 3 頁已指出：

> 我們從傳承明體中，盡力挑選最符合字理、同時不悖於約定俗成準則的寫法，並非盲目泥古。

至於閣下提出的另一種一豎貫穿整個字至底的形體，亦不見得可取。這種形體於一般印刷字體中不易設計得美觀，而且同樣沒有採樣結果支持。

「庚」、「康」、「唐」等字同理。

望閣下明悉。
