### ISSUE TITLE
一些字形問題

### ISSUE THREAD

**Issue by Fuur-Cho** [ichitenfont/I.Ming#131]
# 「图」
此字中「冬」係草書「啚」楷化。似不應按一般的「冬」形將末二筆處理爲點挑。
# 「贛」
可以考慮在一點明體異體中加入右上部爲「夅」的字形。唐石經、廣韻作此。
![Screenshot_2024-08-22-23-33-32-855-edit_com android chrome](https://github.com/user-attachments/assets/127a5641-7ff8-4137-b393-4eaab0971c9a)
# 「𠂔」及包含此部件的字
可考慮在異體中加入類似「𡛷」右部的形體。
![Screenshot_2024-08-22-23-39-17-188-edit_com android chrome](https://github.com/user-attachments/assets/c5c6414b-abbb-4bee-afb4-8acd03aa1b4c)

**Comment by SyaoranHinata** [comment]
感謝閣下的意見。以下是少許回應。

1.此簡化字有二說，有說它單純草書楷化，有說它在楷化同時已轉爲「冬」聲。權衡過後，我們在「一點明體」採用了轉爲「冬」聲的形體，在「一點明體異體」採用了直接草書楷化的形體。

2.這字形在我們的明體採樣中沒印象看到。目前要使用的話可以輸入「𥫔」。

3.這字形在我們的明體採樣中沒印象看到。目前要使用的話可以輸入「𡛷」。
