### ISSUE TITLE
能否建置一個除去簡化字、日文等等的版本？ e.g "I.Ming TC"

### ISSUE THREAD

**Issue by Aerotinge** [ichitenfont/I.Ming#133]
先說明使用場景如右：欲將一點明體用作網頁字型，需要盡可能減少字體檔案大小以利傳輸。

本地使用而言，字型所能涵蓋的字集是越大越齊越好，諸如簡化字、二簡字、日文假名、日本新字體、略字、幽靈漢字、朝鮮漢字最好都全收。
但用在網頁環境則大相逕庭，一絲一毫網路頻寬都要爭取下來。最好是像古早時鉛字鑄匠一般，當用一字給一字。而動輒數十MB的全字集字型實難以施展開來。
今日常見的作法是將一字型檔案拆分成百餘，乃至數百個字型子集。每個子集僅百來至二百餘字，數十kb大小(假設壓縮後以woff2格式傳輸)。交給網頁css/js等前端去與瀏覽器互動，按需下載字型子集來顯示文本。
在動手開拆之前，我想先問問有無可能在貴團隊開發的環境時便做初步拆分，從來源就大幅減少字型體積。

**Comment by lxgw** [comment]
說一句題外話，只是針對使用場景。

一點明體是 IPAmj Mincho 的衍生字型。如果將一點明體作爲 Webfont 的話，則構成對字型的再分發，需要滿足 IPA Font License 1.0 第 3 條第 1 款的限制條件。其中第⑵項指出「需要提供一種方法讓用戶可以自願將衍生字型替換回初始的 IPA 字型」[（參閱 FAQ §3.3.2，需自備翻譯）](https://moji.or.jp/ipafont/faq/#q003-3-2)，如果是用於 Webfont 的話，這個條件可能不容易被滿足，除非用戶本地安裝的 IPAmj Mincho 先於一點明體 Webfont 調用（參考 [JPAfonts 的使用方法](https://osdn.net/projects/jpafonts/howto/usage)），或者是網頁有個類似的開關，能夠讓用戶在 Webfont 與本地安裝的 IPA 原始字型之間切換。

順帶一提，Justfont 網站中提供的[「IPAmj 明朝」Webfont 服務](https://webfont.justfont.com/fontdetail/132)可能違反 IPA 字型授權條款。再順帶一提，日本字型商 FLOP Design 推出了一些採用 IPA 字型補足漢字的免費日文字型（如 [スマートフォントUI](https://flopdesign.booth.pm/items/2296502)），卻在字型壓縮包內的 Readme.txt 中聲明：「アプリ・ゲームに内蔵する場合、プログラムにエンベッド（埋め込み）をする場合、オンラインサーバー上に置く場合、ウェブフォントとしてサーバー上にアップロードする場合にIPAの規約に反する場合ご利用頂けません。」（如果它內置於應用程式或遊戲中、嵌入到程式中、放置在在線伺服器上或作爲 Webfont 上傳到伺服器，違反了 IPA 的條款，則不能使用它。），此外也有[日文 Webfont 套件（「日本語ウェブフォントキット」）](https://flopdesign.shop/items/5c209279687024785ef1b976)在賣。

**Comment by Aerotinge** [comment]
感謝提醒。我在看第 3 條第 1 款時也是囫圇吞棗地看過，沒能想到這點
那看來IPAmj Mincho的部分是不能拆了。我想真要弄的話，做法可能要變成一大核(IPAmj)配多小子集(I.Ming)來下手。
(不過這樣是否又變成一點I.Ming的衍生創作了？)

**Comment by Aerotinge** [comment]
今天才看到 ichitenfont/I.MingWebfont 這個項目。
我算是瞎了眼，原來早給弄好了。抱歉打擾了。

**Comment by NightFurySL2001** [comment]
以上@lxgw所言为是。元宵新上线的组织官网 https://ichitenfont.github.io/ 需要网页字体，因此开动了 https://github.com/ichitenfont/I.MingWebfont 。官网内提供切换IPAmj原字体的方式，在 https://ichitenfont.github.io/about-us 。
