### ISSUE TITLE
希望增補二分漢數字

### ISSUE THREAD

**Issue by Fuur-Cho** [ichitenfont/I.Ming#135]
在排版中常用於目錄頁碼和註釋序號，尤其是古籍排版。
![image](https://github.com/user-attachments/assets/f6469c23-78ce-4ac4-b166-a4ec7fc61a7d)
（改正築地五號中的二分字）
![image](https://github.com/user-attachments/assets/db476c16-27fc-4df6-b347-baee32ce08e9)
（當代日文字體中的二分字，例爲秀英明朝）

**Comment by Fuur-Cho** [comment]
使用例
![1815e5b853b4abe6875453e46a23e98](https://github.com/user-attachments/assets/d21a77eb-4a12-4181-a4d9-81b6319424e2)
![efd3a0c1806a7179b4a11020b919adf](https://github.com/user-attachments/assets/64eabca3-c87e-4ce0-a962-409e8a4b698a)
（劉禹錫集，中華書局１９９０年版）

**Comment by SyaoranHinata** [comment]
感謝樓主意見。
請問這些二分漢數字的Unicode編碼爲何？抱歉我們找不到^^;;;;;

**Comment by lxgw** [comment]
這些二分漢數字沒有 Unicode 編碼，不過在 Adobe-Japan1-4 或以上規格的日文字體中可以通過 OpenType 特性 `aalt`或 `nalt` 調用。

**Comment by SyaoranHinata** [comment]
Orz Orz Orz 囧rz 囧rz 莔rz
涉及 OpenType 特性的話……我們要留待技術人手可行時，再仔細硏究。
畢竟它有相當大的複雜性、難控作性，而它也不是我們計劃的宗旨……
非常抱歉！
