### ISSUE TITLE
一点明异体修补某些字的建议。

### ISSUE THREAD

**Issue by sangoking** [ichitenfont/I.Ming#136]
近来发现有几个字还没够完美：

1、文字中含有「又」字结构，或者「撇捺」结构，收笔为【点捺】

例字：又、翅、使

但我查了几个字，有的有这个情况，有几个字遗漏了，起笔的【点】，宜在异体中添加。

2、[色字头]，有的字是【刀】字头，有的字又没有，宜在异体中添加。

3、邦、蚌等字起笔为【撇】，宜在异体中添加。

4、侯爵的侯字，有的字书上侯的右上角为【工】字，宜在异体中添加。

5、老鼠的鼠字，有的字书上鼠的四点为【向上斜点】，宜在异体中添加。

（我是参考54年作家出版社的《三国》、78年版人民出版社的《东周》、80年增你智出版社《金瓶梅词话》，里面的旧字型的。）

详见图：
![Snap2](https://github.com/user-attachments/assets/9c20e2ee-1093-41bf-8d14-56540a5ceb8d)
![Snap3](https://github.com/user-attachments/assets/97e7f3e5-0ccf-4c20-bc16-204200318929)
![Snap4](https://github.com/user-attachments/assets/c360ea0d-c8c5-4dcb-9fb5-521d654ba651)
![Snap5](https://github.com/user-attachments/assets/982e606a-7875-45c7-aae8-c96778cd5443)
![Snap1](https://github.com/user-attachments/assets/0ba0af67-d76a-4e0f-ad7a-64df07bca3cf)

**Comment by sangoking** [comment]
![Snap6](https://github.com/user-attachments/assets/8e6539bd-6ae1-4fe6-b402-891be6889621)

**Comment by Fuur-Cho** [comment]
２　「色」字上方的「⺈」，金文作「爪」，小篆訛變爲「人」，與「刀」無關，故不應作「刀」，也符合『部件檢校表』之規定；
![image](https://github.com/user-attachments/assets/874b7f98-a661-4bd7-b6d3-25f58372a01c)
「絕」從刀從絲卩聲，右半邊不是「色」。
![image](https://github.com/user-attachments/assets/b540ed1e-d690-4e18-ab83-54ef59377e08)

**Comment by SyaoranHinata** [comment]
感謝樓主的意見。

說在前面，「一點明體」的製作，以《檢校表》爲依歸。《檢校表》在不違反約定俗成的情況下，以字理佔優的形體作爲推薦形體。至於「一點明體異體」，除了《檢校表》上另一推薦形體外，有時也多提供一些形體，多數是即使《檢校表》沒推薦但仍不悖於字理的形體，所以還是會以字理爲準繩的。

「一點明體」與「一點明體異體」的處理，並不是但凡某些舊刊物裏出現的形體就會收錄。我們無意否定那些形體也可以是構成舊字形的一員，但收錄那些形體未必符合我們的宗旨。有關這方面，建議詳閱《檢校表》。

關於樓主提及的一些具體部份，回覆如下：

1.起筆處飾筆的捺筆，並不是「點捺」，捺前的那一筆並不是「點」，而是小小的一「挑」，《筆畫表》已說明是「挑捺」。《檢校表》的〈表三：不視作部件區別之差異〉已說明：「飾筆只視爲筆畫的裝飾。捺筆的起筆處有飾筆與否，即是無論作捺還是挑捺，都只視爲設計風格差異。」這一「挑」只是裝飾筆畫，與字理無關，不是本計劃着重的範圍。

原IPA明體在這筆的處理上並不統一，有些字收錄了異體，既有直接作「捺」的，也有作「挑捺」的；有些字只有作「捺」的版本；有少數字只有作「挑捺」的版本。平衡過工作量多寡，在「一點明體」處理時，統一作不帶飾筆的「捺」。至於「一點明體異體」，若原IPA明體有「挑捺」的版本，我們就保留「挑捺」的形體，但若原IPA明體沒有提供「挑捺」的版本，我們並不特地加上。

要是有同好希望每一個這樣的字都能有「挑捺」版本的異體，歡迎各位修改字形並提交給我們，我們檢査過提交的字圖可用的話，會在日後的更新版本替換之。感謝！

2.「色部件」不从「刀」。而从「刀」者爲「絕部件」。若混淆兩者即違反字理，本計劃不取。正如樓上 @Fuur-Cho 所言的一樣。請參閱《檢校表》上「色部件」和「絕部件」兩段之說明。

3.「邦、蚌」从「丰」得聲。《檢校表》「丰部件」已說明其首筆爲橫，不作撇。如果寫成撇，就跟「憲、害、㓞、砉」等字所從之「丯部件」相混，本計劃不取。請參閱《檢校表》上「丰、丯之別」之說明。

4.「侯」本从「厃」从「矢」，今「厃」約定俗成作「亻ユ」之形，若再變爲「工」形，距字源太遠，本計劃不取。

5.「鼠」字在「一點明體」收錄了下方四頓點之形，在「一點明體」收錄了下方四短橫之形，這已涵蓋了日常最常見的兩種形體。若再要添加「四向上斜點」之形體，恐怕要另行製作一套「一點明體異體二」字型檔才行。且我們也沒怎麼看到「四向上斜點」之字形，現在也難以想像「點」如何向上斜，實在不算太理解這個形體，非常抱歉。

希望能回覆到閣下的發言，讓閣下理解，謝謝。
