### ISSUE TITLE
字形優化建議與問詢

### ISSUE THREAD

**Issue by Fuur-Cho** [ichitenfont/I.Ming#138]
「非」字的挑畫末端似乎可以減細

經檢查，僅「非」字需要優化，其他包含「非部件」字無需調整。

與其他「非部件」字相比存在不協調感（如圖）：
![image](https://github.com/user-attachments/assets/8cf0e14f-237b-41fe-ba96-ff6809981de2)

Ｔｙｐｅｂａｎｋ的「本明朝　Ｍ」：
![image](https://github.com/user-attachments/assets/715f219b-afb9-4bd8-a7d5-a419f8669ab4)

**Comment by Fuur-Cho** [comment]
一點明體「華」字的末橫設計與原版ＩＰＡ明朝有不同。請問是出於何種考慮？
![image](https://github.com/user-attachments/assets/944557a2-f66d-4a3d-92c3-5be041a38dab)

**Comment by SyaoranHinata** [comment]
感謝您的意見！

「非」字的美觀問題，請容我們日後再調整。

「華」字的問題，我們在[《檢校表》這邊的issue 48](https://github.com/ichitenfont/inheritedglyphs/issues/48)也說過，在《檢校表》中我們並沒有硬性規定要作何者。至於一點明體的造型，僅是按我們在取樣時的結果，以及美觀的考慮。其實在取樣過程中，的確可看到末橫較長或末橫較短的兩種形體。而末橫比次末橫短的話，次末橫便不用特地縮太短，以免使其作偏旁時（如「鷨、鞾、鏵」等字），末端的小三角被豎筆阻擋而要迴避太多（雖然同類的迴避其實也很常見），同時也不必硬要末橫顯得較長而競爭空間，因此在「末橫較長」和「末橫較短」兩者之間，統一取後者而已。

希望能解答到閣下的提問，謝謝！

**Comment by Fuur-Cho** [comment]
感謝答覆。
