### ISSUE TITLE
「子」部件的豎鈎筆錯位？

### ISSUE THREAD

**Issue by RuixiZhang42** [ichitenfont/I.Ming#14]
測試字型文件：I.Ming-6.10.ttf

「子」部件的豎鈎筆，有時是錯位的，有時是對齊的。如果錯位是刻意設計的，那麼在保持部件統一的理念下，應當全部錯位才對。有望答疑。

![child-radical](https://user-images.githubusercontent.com/39968857/63642831-74962580-c693-11e9-80bb-af3027de9756.png)

**Comment by i-font** [comment]
謝謝意見！經初步硏究，似乎IPA明朝大多是有點錯位，除了擴展區有一些可能是後添的字。不過似乎在「一點明體」計劃很早期以前，甚至在本計劃的工作展開前，有些字已經對齊了，估計也許是早期的工作朋友以爲字形設計有誤而修改了。若要全面找出哪些字錯位，那些字對齊，恐怕以我們目前的人手來說需要頗長的時間，在此先致歉！

**Comment by SyaoranHinata** [comment]
參 [issue 70](../issue/70)。
