### ISSUE TITLE
追加 Unicode 13.0「biáng」一字

### ISSUE THREAD

**Issue by RuixiZhang42** [ichitenfont/I.Ming#16]
Unicode&nbsp;13.0 預計於 2020&nbsp;年 3&nbsp;月發佈，目前繁體字「biáng」的編碼似乎已經穩定了：

- `U+30EDE` ⿺辶⿳穴⿰月⿰⿲⿱幺長⿱言馬⿱幺長刂心

請問是否有計劃追加這一字呢？

**Comment by creatxrgithub** [comment]
?辵{^(穴<(月^(<(幺言幺)<(長馬長))?刀)心)}

你看這種表示一個新字的語法怎麼樣？

https://github.com/creatxrgithub/chinese_construct_expression

**Comment by aikahiiragi** [comment]
要造這個字很複雜吧……

**Comment by creatxrgithub** [comment]
那沒有辦法，構字因子就是這麼多。最多就是作輸入法或編碼時省略符號。

`⿺辶⿳穴⿰月⿰⿲⿱幺長⿱言馬⿱幺長刂心`
手機上的瀏覽器可以看到這个字的表意字符構造序列

**Comment by creatxrgithub** [comment]
但我覺得這个字的表意字符構造序列不容易讀懂

**Comment by aikahiiragi** [comment]
首先想詢問，Unicode 13.0 預計於 2020 年 3 月發佈，目前有已確定不會再改動的編碼碼位資料嗎？

**Comment by creatxrgithub** [comment]
http://unicode.org/versions/Unicode13.0.0/
就算沒有也快了

**Comment by aikahiiragi** [comment]
我也知道將快，不過問題是，只要在公佈前增刪任何一個字，其後方的碼位可能全部順序移前或移後，那麼就出事了……

**Comment by TNTErick** [comment]
而且該字似乎有大量異體字(民間流傳)

**Comment by i-font** [comment]
今天我們試作了這字，預料會收進下一版本的「一點明體」中。目前的作業結果可參看：
https://commons.wikimedia.org/wiki/File:Biáng.svg
https://commons.wikimedia.org/wiki/File:Biáng_sim.svg
也可以參看我們利用今天的「一點明體」成果修改而成的各種異體：
https://commons.wikimedia.org/wiki/Category:Biáng_(Chinese_character_for_noodle)

**Comment by TNTErick** [comment]
這個字的繁體其實中間還是䜌的。

i-font <notifications@github.com> 於 2020年3月15日 週日 01:25 寫道：

**Comment by i-font** [comment]
我們也有造：
https://commons.wikimedia.org/wiki/File:Biáng-v16.svg

**Comment by RuixiZhang42** [comment]
@i-font 感謝補字！用鏈接裡面的圖試排了一下：
> ![biang-zht](https://user-images.githubusercontent.com/39968857/76704425-4cadf400-66af-11ea-8bb7-806e2bae6861.png)
> ![biang-zhs](https://user-images.githubusercontent.com/39968857/76704427-4f104e00-66af-11ea-926a-8d114b77742c.png)

因為只是用的圖片排版，所以下面的評價可能不太正確，請酌情參考。
1. 感覺 biang 的字面率偏大了。
2. 感覺正體 biang 字裡面的部件「太黑了」，可不可以把筆畫稍微調細？

下面是我測量出來的結果：
> ![zimian](https://user-images.githubusercontent.com/39968857/76705230-d7452200-66b4-11ea-8253-34aa18ccd510.png)

如果我們用思源宋體的 biang 字作為參考來造字，那麼放進一點明體的時候，思源宋體的字可以縮小 97.68% 再作為一點明體的字。

**Comment by i-font** [comment]
感謝意見！我們再調調看

**Comment by i-font** [comment]
新版本已發佈，這次擴展區G裏有些難度非常高的漢字，除了「𰻞、𰻝」外，還有「𰽔、𱁬」等。若大家覺得還可以改善，歡迎嘗試修改，效果良好的話我們可以考慮融合進下一個版本。
