### ISSUE TITLE
「習」字似有誤。顯示上羽下曰，當是上羽下白。

### ISSUE THREAD

**Issue by creatxrgithub** [ichitenfont/I.Ming#19]
「習」字似有誤。顯示上羽下曰，當是上羽下白。

**Comment by FListLee** [comment]
![image](https://user-images.githubusercontent.com/34062491/72271920-bdf70980-3662-11ea-9ca3-13c8ea6c5605.png)

**Comment by FListLee** [comment]
![image](https://user-images.githubusercontent.com/34062491/72272104-0d3d3a00-3663-11ea-93d7-1750867ed234.png)

**Comment by FListLee** [comment]
所以既不是上羽下曰也不是上羽下白

**Comment by creatxrgithub** [comment]
上羽下日的話，習字下部可能還是太寬了。或者，凡是「曰」字的中間一畫就畫到中部或三分二好了，增大區別，也許這樣較好。

**Comment by SyaoranHinata** [comment]
謝謝FListLee解答和引用《檢校表》的資料。

另外回樓上creatxrgithub，現在所有「曰部件」的橫筆都不觸右旁，末端有小三角啊！《檢校表》裏已說明了。如果一點明體有漏網之魚，歡迎擧報，讓我們修正。但至少常用字都已這樣做啊！

至於寬或不寬，則未免太主觀了。比如「書」從「曰」，「晝」從「日」，但「晝」字裏的這個「日」有甚麼方法可以弄得窄呢？因此我們都統一以末端觸不觸及右豎（即是有沒有小三角）爲原則。
