### ISSUE TITLE
我一直想要有種字型：「示」的部首如明體的字形，但「辶」的部首如宋體的字形，且綫寬一致

### ISSUE THREAD

**Issue by creatxrgithub** [ichitenfont/I.Ming#2]
我一直想要有種字型：「示」部及「令」部如明體的字形，但「辶」的部首如宋體的字形，且綫寬一致。
也不知道有沒有人有這種設計的，謝謝

**Comment by i-font** [comment]
你好。我們這個計劃的目標，是要製作傳承字形，相信不會製作「『辶部件』如中國大陸宋體新字形」的字型。不過這是開源計劃，你可以自行修改的。
感謝你的意見！^^
