### ISSUE TITLE
該字體下簡化字有時顯示爲繁體（其中簡化的「諭」對應的是不正確的繁體）

### ISSUE THREAD

**Issue by Reniastyc** [ichitenfont/I.Ming#20]
您好，我在使用一點明體的時候發現，某些簡化字對應的字形爲繁體，如：諭「谕」、緩「缓」。其中簡體的「谕」對應的繁體字形不符合表中提供的標準。而另一部份簡化字則對應正確的簡化字字形，如計「计」
![image](https://user-images.githubusercontent.com/37499529/75112081-62fdfc80-567b-11ea-82a1-3cca3f2b747a.png)
如圖，左側爲簡化字「谕」對應的字形，可以看到有一箇不合理的飾筆。

而因爲我使用的是簡繁通打的字形輸入法，有時候輸出了對應簡化字形的繁體字無法立卽察覺，在其他的字體下可能出現簡繁混用的情況。

我希望能夠將這部份對應繁體字形的簡化字恢復正確的簡化字形。
謹上。

**Comment by SyaoranHinata** [comment]
您好。因爲這字型在我們「I.字坊」於2014年年中接手前，已經是這樣。

翻査歷史，「IPA明體」及其擴充版「IPAex明體」、「IPAmj明體」都缺少簡化字元。至2013年底，Halasjack公開釋出「IPA明體補字」時，除了一些「一簡對多正」的字元外，其餘字元都採用正體字替代缺少的簡化字。

我們「I.字坊」也多番商議過如何解決這問題，目前仍在內部有些嘗試，但都未成功。畢竟涉及的字元太多，理論上全都要人手逐字設計，但我們本身的人手已很有限，要把所有簡化字碼位一一修改，無疑是超級龐大的負擔。因此至今仍未有成果。若有朋友能幫忙，我們萬分非常熱烈深切歡迎！謝謝。

**Comment by i-font** [comment]
目前我們已密鑼緊鼓製作簡化漢字，希望在不久的將來就能提供修改好的版本。
