### ISSUE TITLE
6.12版中部分字元的寬度不統一

### ISSUE THREAD

**Issue by RuixiZhang42** [ichitenfont/I.Ming#23]
用 FontForge 查看 6.12 版字型檔案的**源代碼**，觀察到 9 個「全形字符」的「寬度」有很小的誤差。下面按重要程度列出（越靠前越重要）：

1. 如下 2 個字元 `u30EDD`、`u30EDE` 的「advance width」（橫排前進距離，`Width`）是 2047，應該改成 2048。
2. 如下 1 個字符 `_58041` 的「advance width」（橫排前進距離，`Width`）是 2047，應該改成 2048。
3. 如下 4 個字符 `minus.sups`、`equal.sups`、`minus.sinf`、`equal.sinf` 的「vertical advance width」（直排前進距離，`VWidth`）是 2049，另外 2 個字符 `plus.sups`、`plus.sinf` 的 `VWidth` 是 2047，都應該改成 2048。

因為問題很小，修改好了之後可以等到下一個大版本再一起發佈。

**Comment by SyaoranHinata** [comment]
因爲緊急修訂「𣁳」字，使其遵從[《檢校表》](https://github.com/ichitenfont/inheritedglyphs)，因此也順通更新了「𰻝、𰻞」及豎排全形句號的字寬。

不過我們有個問題，「⁺、⁻、⁼、⁽、⁾、₊、₋、₌、₍、₎」應當不是全形字符，我們應該沒造成全形啊？另外因爲不同成員提交字型後，合集檔目前是以舊版FontCreator來處理的，因此不太確定有沒有修改好這些字符，可能要有勞 @RuixiZhang42 閣下幫忙檢査了。

限於我們的人力和技術，RuixiZhang42 閣下過去向我們提交的標點改善建議，我們也無法一一完成。如果 RuixiZhang42 閣下不介意，不知能不能撥冗幫忙呢？無論可否，請容在下先行致謝。m(_ _)m

**Comment by RuixiZhang42** [comment]
@SyaoranHinata 
上下角標這類字符的確不是全形，但是需要看它們的使用場合：

> ![example](https://user-images.githubusercontent.com/39968857/79174666-5ec3a500-7dc9-11ea-99a6-217feb3ea827.png)

這類變寬的字符是橫排才用得到的，而且一般也就是社會科學、自然科學文獻才會用。直排，例如小說、詩歌，是用不到這些字符的。直排的時候，這些字符變成垂直向下佔全形寬，感覺比較合理。

**Comment by RuixiZhang42** [comment]
@SyaoranHinata 
> 另外因爲不同成員提交字型後，合集檔目前是以舊版FontCreator來處理的

我同意這個workflow的確不方便管理字型檔案的更新。近日我有空會寫一點關於優化字型檔workflow的草案，現在剛剛開了個頭，屆時會發到一點字坊的電郵。

> ![draft](https://user-images.githubusercontent.com/39968857/79175429-b3681f80-7dcb-11ea-88d1-46aa08d10c0d.png)
> 草案會提供一些測試列表（圖中的標點和漢字都是用一點明體渲染的效果）

**Comment by i-font** [comment]
謝謝 @RuixiZhang42 的詳細意見，這段時間內我們也嘗試過實行當中一些，可是也碰到各式各樣的問題。比如字型檔的發佈，若改爲sfd檔，則大眾難以直接下載後安裝，必須先安裝fontforge軟件，以之開啟，並生成ttf後才可以。連我們團隊內也不是人人安裝了fontforge軟件，遑論其他下載的朋友。似乎還是需要以ttf檔作爲共識的交換檔案。而LATEX也涉及不少並非What you see is what you get的操作，比較像程式指令，這是我們這團隊裏大部份貢獻者的最弱項，而且即使懂得使用它，仍難以改變坊間專業的排印和美工人員大多數依賴InDesign、Photoshop、Illustrator等軟件的情況。我們團隊很感謝您的意見，也明白依您所說的方法可以帶來的一些方便和好處，不過以目前來說，克服當中所遇問題的時間遠比不上能帶來的方便，可能我們至少在中短期內，還是要維持目前的作業方式。也許辜負了您的美意，先說聲抱歉！
