### ISSUE TITLE
針對「毙」字字形提出的疑問

### ISSUE THREAD

**Issue by Eganle99** [ichitenfont/I.Ming#24]
「毙」(U+6BD9) 右上「匕形塊」首筆作橫，是有意爲之，還是字形有誤？
![sketch-1588228229318](https://user-images.githubusercontent.com/64576145/80679318-3ccb6180-8aef-11ea-99fa-4f171aff1c50.png)

**Comment by SyaoranHinata** [comment]
正如我們之前所言，目前字型中的簡化漢字，並未有人手和時間處理，把所有簡化字碼位一一修改。它們有些以符合《檢校表》的繁體字暫代；有些以非《檢校表》建議的異體取代；有些或有簡化形態，但尚未符合《檢校表》；有些在筆畫上符合了《檢校表》，但字形美觀有問題。我們希望能有朋友協助造字，處理字型裏的簡化漢字部份，解決這些問題。若有朋友能幫忙，我們萬分非常熱烈深切歡迎！謝謝。

**Comment by SyaoranHinata** [comment]
目前我們已密鑼緊鼓製作簡化漢字，希望在不久的將來就能提供修改好的版本。
