### ISSUE TITLE
大陆习惯的偏靠标点

### ISSUE THREAD

**Issue by tanukihee** [ichitenfont/I.Ming#25]
目前的一点明体的标点是遵循日文规范的（如冒号分号居中，竖排横置，问号叹号全宽居中等），希望能提供符合大陆标点习惯的字体（冒号分号偏靠，竖排时竖直，问号叹号半宽偏靠等）。

**Comment by i-font** [comment]
抱歉我們這計劃集中在傳承字形方面，標點本非我們處理範圍之內。過往因徇眾要求，增設了CP（標點置中）版本，已令我們每次修改字形的工作量增加了近50%。若現在再增加標點差異版本，我們的工作量勢必更大，以目前的人手來說實在不勝負荷。因此暫時難以提供了，還望見諒。但我們很歡迎有朋友協助，修改標點作衍生版本。

**Comment by tanukihee** [comment]
也许你们可以考虑将四个字体封装成一个ttc？毕竟大部分glyph是相同的

**Comment by i-font** [comment]
抱歉我們也不懂這樣的技術……現在我們使用的字型編輯程式做不到……
