### ISSUE TITLE
專案軟體包的名稱

### ISSUE THREAD

**Issue by ShamrockLee** [ichitenfont/I.Ming#26]
有些包管理器，軟體包名稱名稱需要由小寫字母、數字組成、減號分隔（`^[a-z]([-][a-z0-9]+)*`）。
想請教是否有建議的名稱以對應「I.Ming」？

**Comment by SyaoranHinata** [comment]
很久以前字體是以「1.」開頭的，後來有些軟件不支援以「1」字作字體名稱，才改成統一以「I.」開頭表示「一點」，並且測試了一些大路軟件，肯定它們沒有問題才使用。我想我們不會再爲此而改名了。如果眞的確實非常極度有必要，建議可以把「I.」換作「Jatdim」、「Ichiten」、「1dot」或「Onedot」，不過我們並不會提供這樣的檔案，有勞使用folk的功能呢。感謝査詢。^^

**Comment by ShamrockLee** [comment]
@SyaoranHinata 謝謝您的建議！

我沒有希望專案或檔案改名的意思。只是 Nix package manager 用來唯一識別 package 的變數，要使用含有句點的名稱比較麻煩，所以來詢問識別性較高、較能保留原意的變數名稱。

原本的名字還是能保留在「軟體包名稱（pname）」與「描述(description)」中。

**Comment by SyaoranHinata** [comment]
@ShamrockLee 不用客氣，謝謝您的提問。只是沒想到會這樣呢。
其實過去「1」字碰釘時，我也大惑不解，印象中有不少歐文字體以數字命名啊，當中也有以數字開首的。怎麼「1.」就不行了>_<……

**Comment by hfhchan** [comment]
*nix package manager 用的唯一機器標誌，建議採用 ichitenfont-iming.

**Comment by hfhchan** [comment]
*nix package manager 用的唯一機器標誌，建議採用 onedot-iming 或 ichitenfont-iming.
