### ISSUE TITLE
關於阿拉伯數字的字寬

### ISSUE THREAD

**Issue by kyeyo** [ichitenfont/I.Ming#3]
I.MingCP令我相當滿意 唯獨阿拉伯數字的大小及字寬
相較其他明體顯得大些 不知可否修改或新增一個

**Comment by i-font** [comment]
你好！我們這次更新時，曾考慮過這提議。不過我們工作人員對修改西文字母和阿拉伯數字的美感並不太掌握得好，對試作的效果不甚滿意。而且這字型中，不但是阿拉伯數字，它還有多種西文字母都悉悉相關的，要修改的話恐怕要修改許多字元。我們恐怕會弄巧反拙，因此無法實現。
其實阿拉伯數字也是原本由「TB明體」的設計者林隆男（Takao Hayashi）先生所設計的，看上去也很美觀啊。若需要窄身一點，配搭Times New Roman等英文字型使用也不錯的。
感謝你的意見！^^
