### ISSUE TITLE
討論「夬」字下半是否該作「丈」字的腳

### ISSUE THREAD

**Issue by qiyao-zhong** [ichitenfont/I.Ming#31]
「夬」，音「決」或「 怪」，《說文解字》音「決」，用作《廣韻》韻目時音「怪」。此字的宋體或明體字，一般看到為「大」字的腳。但其篆形，下半作「又」形，一般隸定作「又」，而與上半豎筆串接時，作「丈」、「史」等字的腳。附圖（若有上載［音再］成功）為在《說文解字》和《廣韻》兩書裏的字形，皆作「丈腳」。而當「夬」字作「大腳」時，其垂直比例為「央」字的比例，但當此字作「丈腳」時，其垂直比例可能為「史」字的比例，上半可能較高。故，望高手指點，「夬」字的傳承形，以及《一點明體》，是否值得採用「丈」字的腳。

**Comment by qiyao-zhong** [comment]
![P_20200312_083611_1](https://user-images.githubusercontent.com/13633530/91048512-5bc9a280-e64e-11ea-80be-2878cc95bf70.jpg)
![P_20200323_170151](https://user-images.githubusercontent.com/13633530/91048585-76038080-e64e-11ea-8be0-4aac5143fc67.jpg)

**Comment by i-font** [comment]
《廣韻》所彫爲楷體，我們只作參考，一般都不會直接取樣，以免「以楷凌明」，犯下新字形的毛病。
《說文》和《段注》的明體彫字則可以採樣。唯此形雖字理更優，但以目前使用正體（繁體）地區來說，已不算能很順利地通過約定俗成準則。我們經商議後，會收在日後版本的「一點明體異體」中。
