### ISSUE TITLE
希望能造一款“一點明體 粗體”字體

### ISSUE THREAD

**Issue by Jason-Yao1902** [ichitenfont/I.Ming#32]
希望能在一點明體的基礎上改造出一款“一點明體 粗體”字體，配合一點明體需要加粗時使用，避免出現“偽粗體”的問題：）

**Comment by hfhchan** [comment]
目前人手不足，如閣下有興趣參與製作，可以加入 https://www.facebook.com/groups/inheritedglyph/ 群組。
