### ISSUE TITLE
无必要的简体卖（yù）形

### ISSUE THREAD

**Issue by tanukihee** [ichitenfont/I.Ming#33]
简体的卖（yù）与通用字形差距过大，辨识上有困难。简体字并无必要区分两个卖，如实在有必要，也许可以使用
![image](https://user-images.githubusercontent.com/34062491/93715436-cf9e9280-fb9b-11ea-9f9c-e6f90747ed8d.png)
形。

**Comment by lxgw** [comment]
个人看法，如果要在简体上区分「賣」和「𧶠」，可以借鉴一下 1935 年《第一批简体字表》或新加坡以前的简体字写法。

![wqwSds.png](https://s1.ax1x.com/2020/09/21/wqwSds.png)

**Comment by hfhchan** [comment]
> 简体字并无必要区分两个卖

@tanukihee 本字體依照傳承字形標準化文件推薦字形，不同字理在可行情況下採用不同字形。拓展簡化字時，本設計團隊決定簡化字維持分開設計。

@tanukihee @lxgw 另外建議的設計，設計團隊會再考慮。目前簡化字字形由本團隊少部分義工在公餘時間製作，感謝理解。

**Comment by i-font** [comment]
詳細補充一下。

首先，我們「I.字坊（一點字坊）」團隊維護「一點明體」的原意，是不設簡化字的。因爲簡化字本身是人爲地大量及大規模改變漢字形體，有不少形體在頒佈簡化字時才出現，或者官方聲稱是取自過往俗字但其實該俗字過往不怎麼通行。而正體（繁體）字的傳承字形則是數百年來一代一代傳承至今的，基本上每字都有天天見慣的形體。大家對一般漢字的傳承字形需求明顯比對簡化字的需求大，我們就先處理需求較大的部份。

不過，過往也有不少使用者反映，希望能有簡化字的傳承字形。我們審視了直至今年的工作，認爲一般漢字的傳承字形維護算是有了少許成果，簡化字部份的需求呼聲便冒起了。爲了釐定簡化字形體的準繩，我們商議好定形原則（可見[history.md文件](https://github.com/ichitenfont/I.Ming/blob/master/7.00/I.Ming_history.md)2020/04/15的說明），並進行繁複的製字作業，再三調敎。

在簡化字原則中，我們確立了凡能以正體（繁體）字的字理延伸涵蓋者，都盡量繩以之此理，遵[《檢校表》](https://github.com/ichitenfont/inheritedglyphs)之則，修正簡化字新字形。不然的話，若我們貿然就可以打破《檢校表》之則，不但跟我們過往一直的工作準繩不一致，也勢必使未來的工作陷入許多無法決定的難關。而《檢校表》中的表二（15畫，1.35版的第82頁），就已清晰規定「𧶠（中古：juk；粵：juk6；官北：yu4）」與「賣（中古：mreh；粵：maai6；官北：mai4）」必須區分。事實上，「𧶠」與「賣」同樣作爲形聲字的聲符，它們代表着天差地遠的諧聲音系，要是把兩者相混，對漢字的學習來說，其影響是相當災難的。

我們曾考慮使用過往的簡化字字形，但是簡化字皆都將「𧶠」與「賣」兩個部件混同，因此我們實在無法苟且盲從。

對於應該如何區分，我們內部也作過不少査證與取樣，並討論了很久。我們採集過二樓 @lxgw 提出的所有字形，以及陳光垚《常用簡字表》等簡化字草案、芻議案、提案，但都把「𧶠」與「賣」混同，違反了我們的大原則。於是我們製作「𧶠部件」時，由於上方「𡍬的省寫」沒有減省的規定，我們只能按「貝→贝」的推類，只簡化了「𧶠」字下方的「貝部件」（可參見「一點明體異體」版本）。之後我們收到反饋，說「𧶠部件」與現行簡化字區別很大。對於如何符合我們的大原則同時，又能平衡辨認，實在相當棘手。經過團隊多番討論及嘗試後，最後決定修改成接近現行簡化字的「卖（賣）」，但是以「儿」的曲筆特徵表明來源，即是目前「一點明體」採用的字形。「𧶠」从「𡍬」，「𡍬」从「圥」，「圥」即「六」之異體，能作聲符。

關於一樓 @tanukihee 的提議，將「头」的兩點替換成「儿」，似乎也可行。但是比起「一點明體」現在的字形，一樓提議的字形跟現行簡化字的外觀差異會更大。我們團隊將會探討該字形是否會更美觀和更合理。感謝大家的意見。
