### ISSUE TITLE
「倾」（U+503E）字尚未简化

### ISSUE THREAD

**Issue by lxgw** [ichitenfont/I.Ming#34]
一点明体 7.00，「倾」字还是显示成「傾」。

是不是漏掉了？

**Comment by i-font** [comment]
感謝提報！日後將會處理。^^

**Comment by fh-ideal** [comment]
簡體的 祎 字目前也沒有，望及時補上

**Comment by lxgw** [comment]
> 簡體的 祎 字目前也沒有，望及時補上

https://github.com/ichitenfont/I.Ming/issues/37 「祎」这个字我已经提交了，不出意外的话下个版本应该就会补上了。

**Comment by SyaoranHinata** [comment]
感謝回報！我們在內部作業裏已修繕好，日後發佈時就有更正版本。
