### ISSUE TITLE
README 當中意音文字的翻譯錯誤

### ISSUE THREAD

**Issue by edward-martyr** [ichitenfont/I.Ming#35]
表意文字，英文即ideograph或ideogram。Logogram指的是略示文字，如$，&之類。

**Comment by edward-martyr** [comment]
（一句題外話，新版I.Ming的破折號使用無問題，點讚。）

**Comment by hfhchan** [comment]
漢字屬於意音文字，又叫語素文字，英文翻譯是 Logogram。
在標準化中被誤稱為表意文字 (Ideograph)，然而僅少數漢字屬於一般意義的表意文字。

**Comment by SyaoranHinata** [comment]
樓上Henry兄所言甚是。

補刀：所以說，甚麼Unicode、政權「標準」、國際組織「標準」，經常都有違反漢字文字學的地方，甚至是文字學入門級的學識都會弄錯。然而他們不肯更正、把持「標準」之餘，還要別人跟從他們，壓根低兒是以錯凌正，以劣驅良。
