### ISSUE TITLE
误誤

### ISSUE THREAD

**Issue by tomgrean** [ichitenfont/I.Ming#36]
“误”右边应该用简化的“吴”字型吧

**Comment by hfhchan** [comment]
本字體依照傳承字形標準化文件推薦字形，7.0 起補上簡化字，簡化字同樣適用此原則。

**Comment by tomgrean** [comment]
但我看“娛”簡化版已作“娱”了

**Comment by SyaoranHinata** [comment]
非也，「娛(U+5A1B)、娱(U+5A31)」是因爲Unicode分別編碼，而「IPA明朝」已把後者製成「⿰女⿱口天」之形，我們這次製字時又沒檢査到而已，它本身並不符合[傳承字形標準化文件](https://github.com/ichitenfont/inheritedglyphs)之規定。始終我們人手和精力都十分有限，我們主要檢査的是正體（繁體）中文裏常用的字元，其他字元有時只有依靠大家的回報。我們團隊日後會看看是否有需要把U+5A31這碼位的字也改回正確的傳承字形。即使我們沒修改，使用傳承字形時，大家也應以U+5A1B的字元爲依歸。

**Comment by tomgrean** [comment]
瞭解，謝謝

**Comment by fh-ideal** [comment]
兌、兑也是一樣的情況，還是希望以後都能修正一下吧，希望I.Ming趨於完美

**Comment by SyaoranHinata** [comment]
@fh-ideal 說到的這些字，都是基於Unicode收錄「統一漢字（Unihan）」時的問題。

本來，Unicode「只對字，而不對字形」編碼，因此，它以「表意文字認同原則（Han Unification Rule，又稱表意文字統合原則）」來統合「抽象字形一致」或「構字相同但寫法微異」的漢字。比如「扁」的首筆有撇、橫、直點、頓點等，Unicode都統合在一起，只編配一個碼位。

可是，同一時間，Unicode又害怕在地區字集裏已分別編了碼的字，若轉換到Unicode時遭合併起來，會令原文本失眞，使Unicode遭受抵制。因此，在安放最常用漢字的基本漢字區域Unified Repertoire and Ordering（URO）裏，Unicode又立了一條與上述規定相矛盾的規則——「原字集分離原則（Source Separation Rule，又稱來源字集分離原則、原規格分離原則」。根據此則，若有些應當統合編碼的漢字，在地區字集裏已分別編作兩碼或多碼，那麼Unicode就不統合。於是，「娛、娱」、「兌、兑」、「戶、戸、户」在一些地區字集裏已編作兩碼或多碼，Unicode寧可違反「認同原則」，都不將它們統合。

Unicode這做法的詳細說明，可見： https://zh.wikipedia.org/wiki/中日韓統一表意文字#認同原則與原字集分離原則 。條目裏也說出了文字學界對Unicode這些矛盾做法的不滿與批評。對傳承字形來說，Unicode這做法是不恰當的。

目前世界上的電腦字型編碼，若要通用，要兼容不同作業平臺和程式，基本上不得不依從Unicode。而Unicode造成的問題，實在不是我們憑個人或組織能力可以改變。一天Unicode不從根源修正這個問題，我們一天都無能爲力。在《推薦字形表》的序言裏，我們已言明Unicode這做法對傳承字形帶來的問題，並強調製作傳承字形時，即使正體（繁體）字的常用碼位被不恰當地分別編碼，字型製作者仍應無視這不恰當做法，將那兩個或多個碼位製作成同一個傳承字形。這已是我們能力上的極限。

若像 @fh-ideal 你所提出的般，把所有簡字、略字（包括中國簡化字、日本略字，以及歷來簡俗字等）都依以做法而行，一方面我們需要更多的人力物力去考證，以免誤改形似卻非同源的部件；另一方面， @fh-ideal 你記得你提出過把「关」字改爲依簡俗字字理，而非正體字字理，我也費了許多脣舌去解釋爲何我們堅持我們的原則嗎？若我們連所有簡字、略字都這樣做，恐怕屆時要解釋的不會是一個「关」字而已。

我們的人手非常非常短缺，在能夠妥善解決這人手荒問題前，恐怕我們眞的無力負擔。
