### ISSUE TITLE
貢獻一下自己業餘時間製作的字元

### ISSUE THREAD

**Issue by lxgw** [ichitenfont/I.Ming#37]
業餘時間製作了 361 個字元，其中有《通用規範漢字表》裏的簡體字 360 個。

已經生成 TTF 格式。算是對這款開源字型的貢獻吧。

![0pMIwd.png](https://s1.ax1x.com/2020/09/24/0pMIwd.png)

https://github.com/lxgw/I.Ming_Supplement_CHS/blob/master/IMSCHS.ttf
https://github.com/lxgw/I.Ming_Supplement_CHS/blob/master/IMSCHS2.ttf

把這 361 個字加進去，應該就可以夠 8105 個字了。

**Comment by i-font** [comment]
非常感謝您的貢獻！！
請問可以怎樣稱呼啊？我們會在說明和歷史紀錄檔裏寫明的。^^

**Comment by SyaoranHinata** [comment]
萬分感謝！一郎先把它們逐字打出來，是這327字沒錯嗎？

垯垱塆壸婳媭屃峃峣崄嵚庼彟挦昽梾梿槚沨浉浐浕溁滪澛狝玱琎疭硁硙祃祎窎筜筼篯纮纴纼绖绤绹缊缞翙荙萚蟏袆袯裈襕觃訚詟讱讻诇诐谞豮赑赒赗赪轪辀辌辒酂酦钖钘铏铚铻锜锧锳锽镃镈镋镚镠镮镴镵闿阇阘颋颎颙飏飐飔飗饳饻馉馌驲骃骉骍骎骕骙骦鬶鱽鱾鲀鲃鲉鲊鲌鲏鲖鲗鲘鲙鲝鲪鲬鲯鲹鲾鲿鳀鳁鳂鳈鳉鳑鳒鳚鳛鳠鳡鳣鳤鸤鸧鸰鸻鸼鹀鹍鹐鹒鹔鹖鹙鹝鹟鹠鹡鹢鹯鹲鹴黡龁龂鿎𣗋𣲗𣲘𣸣𤩽𦈡𦝼𨐈𨱇𨱑𨱔𩽾𩾃𩾌𪟝𪣻𪨶𪩘𪾢𫄧𫄨𫄷𫄸𫇭𫌀𫍣𫍯𫍲𫍽𫐄𫐐𫐓𫑡𫓯𫓶𫓹𫔍𫔎𫔶𫖮𫖯𫖳𫗧𫗴𫘜𫘝𫘦𫘧𫘨𫘪𫘬𫚕𫚖𫚭𫛭𫞩𫟅𫟦𫟹𫠆𫠊𫠜𫢸𫫇𫭟𫭢𫭼𫮃𫰛𫵷𫶇𫷷𫸩𬀩𬀪𬂩𬃊𬇙𬇹𬉼𬊈𬊤𬍛𬍡𬍤𬒈𬒗𬕂𬘓𬘘𬘡𬘩𬘫𬘬𬘭𬘯𬙂𬙊𬙋𬜬𬟁𬟽𬣙𬣡𬣳𬤇𬤊𬤝𬨂𬨎𬩽𬪩𬬩𬬮𬬱𬬸𬬹𬬿𬭁𬭎𬭚𬭤𬭩𬭬𬭯𬭸𬭼𬮱𬮿𬯀𬯎𬱖𬱟𬳵𬳶𬳽𬳿𬴂𬴃𬴊𬶋𬶍𬶏𬶐𬶟𬶠𬶨𬶭𬶮𬷕𬸘𬸚𬸣𬸦𬸪𬹼𬺈𬺓𮧵

當中「𫵷」應是「⿰山历」，「𬤝」應是「⿰讠惠」吧。我會修的。

稍後我們會檢査這三百多個字，部份字還會稍爲調整一下（比如說「绤、绹、𣲘、𫐄」等的左右部件佔寬和佈局還可以再修，不過我這麼看，很大部份的字都造得相當不錯了），如無意外應該會加到下一版本中。

**Comment by SyaoranHinata** [comment]
對應的正體（繁體）字，目前「一點明體」都已收了。

墶壋壪壼嫿嬃屓嶨嶢嶮嶔廎彠撏曨棶槤檟渢溮滻濜濚澦瀂獮瑲璡瘲硜磑禡禕窵簹篔籛紘紝紖絰綌綯縕縗翽薘蘀蠨褘襏褌襴覎誾讋訒訩詗詖諝豶贔賙賵赬軑輈輬轀酇醱鍚鈃鉶銍鋙錡鑕鍈鍠鎡鎛钂鏰鏐鐶鑞鑱闓闍闒頲熲顒颺颭颸飀飿餏餶饁馹駰驫騂駸驌騤驦鬹魛魢魨䰾鮋鮓鮊鮍鮦鰂鮜鱠鮺鮶鯒鯕鰺鰏鱨鯷鰮鰃鰁鱂鰟鰜䲁鰼鱯鱤鱣䲘鳲鶬鴒鴴鵃鵐鵾鵮鶊鷫鶡鶖鷊鶲鶹鶺鷁鸇鸏鸘黶齕齗䃮欓湋潕濆瓛繻膢輄銶鐄鐏鮟鮸鱇勣塿輋巘睍綖絺繶纁蔿襀詷諴謏譞軏輗輮鄳銈鋗錤鐇鐍闑顗頫頵餗饘馼駃騊騄騠騵騱鰤鮆鱲鵟璊綡䡵鉷頍䮄齯僤噁塸埨𡑍墠娙㠣嵽廞彄暐晛梜櫍浿漍熰燖燀瓅璗璕礐𥗽篢紃紞絪綎綄綪綝綧縯纆纕蔄虉蝀訏諓詪諲諟譓軝輶鄩醲釴鋹釿鉥鉮鉊鉧鋐錞鍭鎓鏏䥕鏻鐩闉隑隮隤頔頠駓駉駪駼騑騞驎鮈鮀鮠鮡鯻鰊鱀鰶鱚鵏鶠鸑鶱鷟鷭齘齮齼韡

**Comment by lxgw** [comment]
寫「落霞孤鶩」就行。

**Comment by lxgw** [comment]
但是把這些漢字加上，應該還是不夠《通用規範漢字表》的 8105 個字......等我時間充裕，會把剩下的字補完。

最後感謝貴項目，提供了這麼高質量的開源字型。

**Comment by lxgw** [comment]
> 非常感謝您的貢獻！！
> 請問可以怎樣稱呼啊？我們會在說明和歷史紀錄檔裏寫明的。^^

寫「落霞孤鶩」就行。

**Comment by lxgw** [comment]
目前剩下的 34 個字已經補全，保存爲另一個 TTF。

㑇㘎㤘㧐㧑䁖䃅䅟䌹䏝䓖䓨䗖䝙䥽䦃䲟䲠䲢䴓䴔䴕䴖䴗䴘䴙䶮亸伣俫勚叇唝啴

https://github.com/lxgw/I.Ming_Supplement_CHS/blob/master/IMSCHS2.ttf

**Comment by i-font** [comment]
非常感謝！如果我要順 Unicode 序合併它們的話，先放 IMSCHS.ttf 的 34 字，再在其後加上 IMSCHS.ttf 的 327 字，不用再調整任何次序。這就行了對嗎？

**Comment by lxgw** [comment]
> 非常感謝！如果我要順 Unicode 序合併它們的話，先放 IMSCHS2.ttf 的 34 字，再在其後加上 IMSCHS.ttf 的 327 字，不用再調整任何次序。這就行了對嗎？

是的。

**Comment by SyaoranHinata** [comment]
Fixed ^O^
