### ISSUE TITLE
龝

### ISSUE THREAD

**Issue by fh-ideal** [ichitenfont/I.Ming#38]
請問 龝 的右邊爲何不是 龜

**Comment by fh-ideal** [comment]
無論是從金文、籀文演變，還是《康熙》字型來看，右邊也不應該是I.Ming體的那樣吧。爲何不按《康熙》取右邊爲 龜 呢

**Comment by hfhchan** [comment]
請參閲傳承字形標準化文件 https://github.com/ichitenfont/inheritedglyphs

**Comment by fh-ideal** [comment]
標準化文件中，並未找到對此字字型選擇的單獨解釋

**Comment by hfhchan** [comment]
龝（秋）所從並非龜，而是蟋蟀，詳細可見 https://humanum.arts.cuhk.edu.hk/Lexis/lexi-mf/search.php?word=%E7%A7%8B.

部分國內著作隸定為𬟏形，然而頭定與草無關，故採用「卝」形。

**Comment by fh-ideal** [comment]
原來如此，感謝
