### ISSUE TITLE
幵 部的字，幵的上面兩短橫在有的字中相連(非 开 部)，而在的字中斷開

### ISSUE THREAD

**Issue by fh-ideal** [ichitenfont/I.Ming#40]
![Uploading 20200929_150402.jpg…]()

**Comment by fh-ideal** [comment]
請用I.Ming輸 妍、研、枅、趼( 幵 部非 开 部)四字並放大看，前兩字連而後兩字斷。望回覆

**Comment by hfhchan** [comment]
已知悉。

**Comment by fh-ideal** [comment]
好的，請問後期會修改嗎

**Comment by hfhchan** [comment]
未決定
還要檢視有多數字有相同情況。

**Comment by i-font** [comment]
閣下好，早兩天閣下已經從別的渠道反映過相同問題，我們團隊已經展開了討論。由於我們團隊一直非常缺乏人手，對同一個問題，在同一個時間階段，要是使用了甲渠道，就不必使用乙渠道重複提交了，以免本來短缺的人手再遭虛耗。

此外，我們目前還在硏討中，但以我所知，閣下在別的渠道反映時，我們的成員已清楚地告知閣下，**這並不屬於相連，而屬於明體向來的造型風格**。有些書體造型上必須像閣下所說的「斷」才能視爲一筆的終結，如黑體；但有些書體向來有自己表達筆畫終結的方法而不一定要像閣下所說的「斷」，明體正是其中之一。還望閣下在表達過程中，可以尊重這些事實，不知道而說錯並不打緊，但若我們指正過、解說過了以後閣下還繼續無視，繼續錯誤陳述，我們實在難以處理。還望注意。

**Comment by fh-ideal** [comment]
之前的確不瞭解這個，且我在此提問的時間是在你們的成員於另一平臺回覆我之前，並不是故意錯誤陳述，請勿多想

**Comment by fh-ideal** [comment]
之前的確不瞭解這個。另請知悉，我提問的時間是在你們的成員於另一平臺回覆我相關問題之前，若我當時已知其因果，又何必再問。非是故意作錯誤陳述，請勿多想

**Comment by SyaoranHinata** [comment]
抱歉我們代表上方的回應欠妥。

經我們檢視、比較過含「幵部件」和「幷部件」的字，發現這是源自IPA明朝體本身的設計，而且「假相連」者佔大多數，像「趼」般刻意完全區分屬少數。而且若全都依「趼」般刻意區分，其實未必好看，可能犧牲了美觀。更遑論除了「幵部件」和「幷部件」，這字型中還有許多字都是以小三角代表橫筆完結，而呈現「假相連」的形狀。若眞的要更改，這是十分龐大的工程。我們也諮詢過好些設計職人，他們都一致認爲，在明體裏，「小三角」已足夠表明橫筆完結。我們決定尊重前人做法，不作改動。
