### ISSUE TITLE
簡體字庫缺 嫔 字

### ISSUE THREAD

**Issue by fh-ideal** [ichitenfont/I.Ming#41]
如題

**Comment by fh-ideal** [comment]
祎 字也缺失

**Comment by lxgw** [comment]
没有吗？
![0mMF6e.png](https://s1.ax1x.com/2020/09/29/0mMF6e.png)

**Comment by fh-ideal** [comment]
手寫 嫔 會出現兩個都是 嬪

**Comment by mm-longcheng** [comment]
我看到I.Ming-7.00.ttf中存在"嫔"并能显示正确，而在I.MingCP-7.00.ttf中输入"嫔"出现的是"嬪"，这个问题也存在于异体字包中。望再次校对一下，谢谢。

**Comment by SyaoranHinata** [comment]
感謝回報！我們在內部作業裏已修繕好，日後發佈時就有更正版本。

**Comment by fh-ideal** [comment]
請問新版本大概啥時候會問卋呢
