### ISSUE TITLE
禪、簞 等字的簡體之 单 部用的是日標的 単

### ISSUE THREAD

**Issue by fh-ideal** [ichitenfont/I.Ming#42]
如題

**Comment by fh-ideal** [comment]
CP版本

**Comment by SyaoranHinata** [comment]
@fh-ideal 正如我之前跟你解釋的「表意文字認同原則」和「原字集分離原則」，在Unicode裏，獨用的「单」與「単」分別編碼；作部件時，則時宜分別編碼，時宜統併作一碼。當中，「禅、箪、蝉」三字是統併的，而這三字在本身IPA明朝體裏，已作日本略字的寫法（從「⺍」），我們就沒有修改——不論是否CP版本皆如此。也許日後在異體裏安放另一字形吧。

**Comment by fh-ideal** [comment]
原來如此，感謝回覆
