### ISSUE TITLE
討論「陋的右邊」是否該作「匸@內」或「匸@丙」

### ISSUE THREAD

**Issue by qiyao-zhong** [ichitenfont/I.Ming#43]
《一點明體》諸公：

鑒於：
一、《一點明體》的前身《IPA明朝體》：
https://store.justfont.com/fontdetail/132
「陋」字的右邊右上為「丙」，左下為「豎橫」（註一），而「丙」字的上橫向左伸到「豎橫」的上方。《一點明體》(6.13)把「豎橫」改成「豎彎」（註一）（如「直」字在《一點明體異體》之筆畫），其餘不變；
二、《康熙字典》《匸部》（匸，《校改國音字典》古音音徯，廣州話音奚陽上，國語因濁上變去而變為去聲）有兩個類似「陋的右邊」的字，一作「匸@內」，一作「匸@丙」，兩字皆音「陋」，無註明是否正俗之差。
三、此字之篆形亦形似以「匸」字為框。
四、有傳承印刷品（相片待上載），把「陋」字的右邊印成「匚@內」（匚，《校改國音字典》古音音方，廣州話、國語，亦音方），蓋有些印刷字體「匚匸」不分，另看不清楚其「內」與上方是否接觸。若以此形「正形」為「匸@內」，則「陋」字的右邊作此。若云「內」與上方一橫相接觸，則為一連體字。

茲提問：
一、「陋的右邊」是否「匸@內」這個字？
二、統一碼另外有收錄「陋」字字形，其右邊作「匸@丙」：
https://chardb.iis.sinica.edu.tw/char/64190
http://yedict.com/zscontent.asp?uni=28E5F
而「匸@丙」本身亦有收錄：
https://chardb.iis.sinica.edu.tw/char/315
http://yedict.com/zscontent.asp?uni=3537
而《字海．葉典》把「匸@內」視為其異體字：
https://chardb.iis.sinica.edu.tw/char/30119
http://yedict.com/zscontent.asp?uni=2096E
三、是故，「陋的右邊」是否該作「匸@內」或「匸@丙」？

註一：「豎橫」和「豎彎」依《檢校表》之附錄《普通筆畫叫法》叫之。

提案人　鍾啟堯

**Comment by qiyao-zhong** [comment]
「陋」字的相片。

**Comment by qiyao-zhong** [comment]
![P_20200913_085802_1](https://user-images.githubusercontent.com/13633530/96801533-64660b80-143a-11eb-8528-6cc5be1e23fb.jpg)

**Comment by zoe-the-scribe** [comment]
「陋」(964B)「𨹟」(28E5F) 已分居不同編碼。後者似為「從匸」字形所留，篆書隸書多從之。檢明末印書《四書參》中[《論語》「陋」字不從「匸」](https://ctext.org/library.pl?if=en&file=140422&page=109)，可見「不從匸」字形也有所據。（按《四書參》一書批語全為手寫體，但正文為「明朝」之「明體」可參考。唯所從字形按照今日教學或「官方」標準多所謂「異體字」，或出版物已不常見字形。）

**Comment by zoe-the-scribe** [comment]
個人直觀觀察，圖像（當為《藥師經》？）中「陋」字右部件「豎筆」與上下二橫筆都不連。參考下「盲」字上部「亡」部件字形，若相連應該不至於斷筆如此明顯。或許是圖中印刷物所用字體，為美觀調整了「陋」字的筆畫安排。

**Comment by SyaoranHinata** [comment]
若論字理和字源，從「內」雖有字理（依徐鉉之說），但秦簡的確從「丙」，目前尚無比之更早的字形。自宋字書始見從「內」者。因此在字理字源方面，兩種字形我們都不排斥。

同時，我們根據取樣結果和約定俗成辨識測試，大多數都作今形。因此我們並不捨近就遠。常用字如「陋 (U+964B)」之「𫠥部件」，就從「㇄」，從「丙」。分別編碼的「𨹟 (U+28E5F)」之「㔷部件」，就依篆形，從「匸」，從「丙」。
