### ISSUE TITLE
鼠 字中的四點是否應該改爲四短橫？

### ISSUE THREAD

**Issue by fh-ideal** [ichitenfont/I.Ming#44]
傳統及近現代大部分朙體中 鼠 字中下多作四橫，四橫相對於四點也更合象形字理。不知I.Ming取四點之鼠是依據甚麼原因，標準化文件中對此竝無解釋，故有此問

**Comment by zoe-the-scribe** [comment]
按「鼠部件」見 [ichitenfont/inheritedglyphs/component_of_recom_inherited_glyphs-1.35.pdf](https://github.com/ichitenfont/inheritedglyphs/blob/master/component_of_recom_inherited_glyphs-1.35.pdf) p. 12, 「作點; 亦可作橫。」觀察可見"I.Ming"通作點，"I.MingVar"通作橫。

**Comment by fh-ideal** [comment]
在下的意思是是否應該修改使I.Ming中之鼠作橫，I.MingVar中的鼠作點？畢業正體選字相比於異體更要攷慮傳承性，而各類舊朙體中作四橫的鼠字要朙顯更常見

**Comment by fh-ideal** [comment]
在下的意思是是否應該修改使I.Ming中之鼠作橫，I.MingVar中的鼠作點？畢竟正體選字相比於異體更要攷慮傳承性，而各類傳承字型的舊朙體中作四橫的鼠字要朙顯更常見

**Comment by fh-ideal** [comment]
或者I.Ming及I.MingVar中的鼠都作橫。鼠字似乎不是很有必要區分正異體

**Comment by fh-ideal** [comment]
或者I.Ming及I.MingVar中的鼠都作橫。鼠字似乎也不是很有必要區分正異體

**Comment by SyaoranHinata** [comment]
「鼠」字在實際書籍的採樣結果中，大多作點。作橫的也有，但比作點者少。
考慮到兩者在字理上都是象形，也不算哪種形體明顯地增加或減少了象形程度，就兩者並存了。

**Comment by fh-ideal** [comment]
但康熙字典、說文的各箇清刻本及其註等字書都從四短橫之 鼠 ......

**Comment by SyaoranHinata** [comment]
但《大漢和》、《中文大辭典》、《辭海》、《中華大字典》、《大書源》、《說文考證》、《標準篆典》等字頭都是四點，我們在日常舊字形書報路牌的採樣也大多作四點。
兩形字理上沒甚麼軒輊之別時，我們只能取其一，就會從眾。於本例中，即取四點者。
我們經多番考慮，現在把兩形並收，已顧及兼容。難道閣下不能兼容，要我們只取一形才可以？
