### ISSUE TITLE
止戈为武

### ISSUE THREAD

**Issue by liuxilu** [ichitenfont/I.Ming#45]

**Comment by liuxilu** [comment]
？

**Comment by hfhchan** [comment]
請提供 issue 的詳細説明。

**Comment by liuxilu** [comment]
武：
![或武](https://user-images.githubusercontent.com/53636947/97832696-68354000-1d0e-11eb-8cd1-38a435476855.png)
戍：
![或勽](https://user-images.githubusercontent.com/53636947/97832707-72573e80-1d0e-11eb-8ba4-c852e1aa438b.png)

**Comment by hfhchan** [comment]
「武」的隸定已經非常穩固，請問你提出的形體有沒有現存印刷體依據？

**Comment by liuxilu** [comment]
「戍」怎么说？
____
搞错了，是这样。有碑刻：[拓本文字データベース](http://coe21.zinbun.kyoto-u.ac.jp/djvuchar?query=%E6%AD%A6)
![image](https://user-images.githubusercontent.com/53636947/97954266-ffb59400-1ddd-11eb-82d7-c57d4688c207.png)
- 有上横短的，宋刻本 十家註孫子遺說<details>![image](https://user-images.githubusercontent.com/53636947/97953598-00e5c180-1ddc-11eb-85fd-a6723d498fb1.png)</details>
- <del>上横不出头的，宋刻本 分門集注杜工部詩</del><details>![image](https://user-images.githubusercontent.com/53636947/97954480-9a15d780-1dde-11eb-933d-dde2d1b98c27.png)</details>

**Comment by SyaoranHinata** [comment]
1.
「武」字在明體等印版字型裏已經非常穩固，在採樣中並沒有取得目前字形以外的形體。

至於 @liuxilu 閣下擧出的例子，要麼是書法碑帖，要麼是楷體印本，它們都是本計劃的主力範疇。若強行「認楷作母」，據之改造明體，更有違我們的宗旨。這些問題，我們已在《檢校表》前言裏清楚說明。

2.
「戍」字也一樣，在明體等印版字型裏已經非常穩固，在採樣中並沒有取得目前字形以外的形體。

**Comment by liuxilu** [comment]
不好意思，是我疏忽，本项目是明体。其实我找宋刻本也是知道明刻本大概不会有 :P
____
这个issue的本意是字理，我说的字形能达到「马上辨识」「不会混淆」吧？

**Comment by SyaoranHinata** [comment]
「一點明體」並不是只顧字理而不顧其他因素，而是綜合字理、約定俗成和美觀，在三方面取得平衡。這些問題，我們已在《檢校表》前言裏清楚說明。

況且「武」字和「戍」字，雖然你擧出的字形，也許在字理上佔優一點兒；可是它們的今形，在字理上也不是不可解。

至於閣下提出的字形，能否讓大家「馬上辨識」，恕我個人並不太樂觀。

**Comment by liuxilu** [comment]
我明白了；请教，今字形何解？
另有一建议，愚以为《检校表》虽然表达此意，但并未「清楚说明」。比如，并没有「綜合字理、約定俗成和美觀，在三方面取得平衡」这样的句子。

**Comment by SyaoranHinata** [comment]
今形：

「武」字依然是从「止」从「戈」，只是「戈」字變形作「![戈的變體](https://glyphwiki.org/glyph/cdp-8cb8@3.50px.png)」而已。現代漢字中，部件變形是常有的事。

「戍」字依然是从「人」荷「戈」。
