### ISSUE TITLE
關於 电、電 字和 申、神、伸 等字

### ISSUE THREAD

**Issue by fh-ideal** [ichitenfont/I.Ming#46]
电、電 字是否更應作如下之形，即“日”形從中間斷開？
![20201126_145224](https://user-images.githubusercontent.com/71869626/100317661-b1b83880-2ff7-11eb-81fd-ee81563175ee.jpg)

電、申雖古爲一字但早已分化，電 做上述之形一來更貼合古字之象形，二來簡體之 电 更可與 申 進一步區別(自有 申 字以來的字體或就不需體現二者同源，朙體當然更沒此必要吧)
或者不攷慮第二點，將 電、申 都取“日”形中間斷開之形，以貼合古字字形字理。

**Comment by SyaoranHinata** [comment]
在採樣中，沒怎麼看到閣下所建議的「电」字。

除非特殊情況，否則處理一般用字時，我們先依據在傳統印刷字體場合中的採樣結果，再平衡字理及約定俗成，而不強求自行改造。閣下之建議，並不符合本計劃的宗旨和處理方法。

本字型是開源的，要是閣下喜歡，我們歡迎閣下自行修改字型檔案，說明閣下修改了甚麼並另行發佈。但本字型並不會如此修改。
