### ISSUE TITLE
關於 主 字及從主類的字

### ISSUE THREAD

**Issue by fh-ideal** [ichitenfont/I.Ming#47]
主 字第一筆是否更應寫作直點？爲與 往 字右部 之+王 的 往 之本字區別可將 主 之直點與第一橫之留下空隙(空隙大小應在美觀與區別性之間取平衡)，如下圖 
![20201126_151430](https://user-images.githubusercontent.com/71869626/100319151-242a1800-2ffa-11eb-991c-e80a559719d8.jpg)

主、示 兩字古代同源，所以 主 第一筆無論作直點還是橫點都比斜點合理不少(請類比 礻 旁第一筆分別作橫、直、斜點的三種新舊字形)。由於朙體印刷中 主 用橫點極少見，故建議用直點，可使朙體字的風格更朙顯，又更貼合小篆字形，也更合字理。祈望攷慮

**Comment by SyaoranHinata** [comment]
在採樣中，沒怎麼看到閣下所建議的「主」字。

除非特殊情況，否則處理一般用字時，我們先依據在傳統印刷字體場合中的採樣結果，再平衡字理及約定俗成，而不強求自行改造。閣下之建議，並不符合本計劃的宗旨和處理方法。

本字型是開源的，要是閣下喜歡，我們歡迎閣下自行修改字型檔案，說明閣下修改了甚麼並另行發佈。但本字型並不會如此修改。

**Comment by i-font** [comment]
補充一下，「示」作偏旁時，只有「⺬」才算是傳承字形（舊字形）。「⺭」無論首筆是直點還是頓點，都已楷化、新字形化了，並不算眞的是傳承字形。因此，無論是「示」還是其變體「⺬」，其首筆必定是橫。

「主」字在採樣中，並無作豎點而下方留有空隙者。若作豎點，它要麼變成目前「往」的右方（但這會不必要地混同了相異的部件，應盡量避免），要麼就變成四筆的「龶」（這也混同了相異部件）。這明顯不及它形可取。

「主」首筆作頓點有篆形支持，也是現今主流的明體形體，沿用已久，我們採作「一點明體」；「主」首筆作橫，並不是取樣結果中的主流，但也確有一些例子，也有其篆前的來源爲據，我們採作「一點明體異體」。我們認爲這處理已經充份顧慮及各方因素。

**Comment by fh-ideal** [comment]
好的，謝謝回覆。不過 主 的篆形不是都作直點嗎？不是頓點吧

**Comment by hfhchan** [comment]
小篆裏沒有點
