### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by i-ug-yang** [ichitenfont/I.Ming#49]
我本人水平有限，对于部分字的字形设计有疑惑。
![E9B8C370-EBA7-4CE9-A4D8-26506DE749D3](https://user-images.githubusercontent.com/73928209/109113199-d34fca00-7776-11eb-8cc9-2ee613d3b46e.jpeg)
比如这个龟字，在鬮字中被处理为卝头，我不知这个根据是什么，希望可以得到一个合理的答案。
此外，像是衆和眾这二字，由于讹变等原因已然成为了两种字形，因此我认为要么按照原有字形设计，要么都合并到眾字（像爲和為），但贵团队设计的衆字只是在眾上多了一撇，在我看来是缺少美感的。
![AC35BCDB-EC2B-406D-A4F8-F584F560E834](https://user-images.githubusercontent.com/73928209/109113872-deefc080-7777-11eb-95f3-5ed692155afa.jpeg)

**Comment by i-ug-yang** [comment]
還有我想請問南廱明體和一點明體是什麼關係？

**Comment by hfhchan** [comment]
鬮，古侯切，聲旁是秋的古字，而非龜。另見龝。

**Comment by hfhchan** [comment]
衆字雖為訛變，但舊印版楷宋均有此形。故留之。

**Comment by hfhchan** [comment]
> 還有我想請問南廱明體和一點明體是什麼關係？

不知道，或者您可以聯絡南廱明體的作者試試

**Comment by i-ug-yang** [comment]
谢谢答复


| |
李旭阳
|
|
13161228888@163.com
|
签名由网易邮箱大师定制


在2021年03月2日 18:52，Henry Chan<notifications@github.com> 写道：

Closed #49.

**Comment by i-ug-yang** [comment]
一点明体做得很棒，相信在未来一定能被更多人喜欢。


| |
李旭阳
|
|
13161228888@163.com
|
签名由网易邮箱大师定制


在2021年03月4日 17:35，李旭阳<13161228888@163.com> 写道：
谢谢答复


| |
李旭阳
|
|
13161228888@163.com
|
签名由网易邮箱大师定制


在2021年03月2日 18:52，Henry Chan<notifications@github.com> 写道：

Closed #49.
