### ISSUE TITLE
希望能有適用於小字體 (12px)

### ISSUE THREAD

**Issue by bluelovers** [ichitenfont/I.Ming#5]
希望能有適用於小字體 (12px) 的樣式或 bitmap 字體

**Comment by SyaoranHinata** [comment]
您好！感謝您的意見。我找們過一些開源點陣資源嘗試修改，以及嘗試一些人手調整顯停（Hinting）效果的方法，發現無論是在技術還是在人手資源上，都是我們目前難以克服的。很抱歉在可見將來裏暫時難以滿足閣下的提建。
