### ISSUE TITLE
補充一個字“㼂”

### ISSUE THREAD

**Issue by i-ug-yang** [ichitenfont/I.Ming#50]
![E0D779F8-27FA-4611-8FA7-6BBAFAAF4E2C](https://user-images.githubusercontent.com/73928209/109121997-eff1ff00-7782-11eb-86d4-c9642168a30e.jpeg)

**Comment by hfhchan** [comment]
正字為璺。已編碼漢字有8萬多，未能盡錄，暫不考慮增收。
