### ISSUE TITLE
U+2633B 𦌻

### ISSUE THREAD

**Issue by JLHwung** [ichitenfont/I.Ming#52]
I.Ming 作「⿱罒選」

碼表各地區字形均爲「⿺辶𦌔」

![image](https://user-images.githubusercontent.com/3607926/113440706-e7609a00-93ba-11eb-8573-5d2f81d4d664.png)

**Comment by SyaoranHinata** [comment]
謝謝意見。據《漢語大字典》，此字爲「𦌔」的異體，字理上當爲「從『网』，『選』聲」。所謂「碼表各地區字形」的寫法，在彰顯字理方面，明顯不及一點明體目前寫法，因此我們以維持目前寫法爲宜。

**Comment by hfhchan** [comment]
@JLHwung 

PMingLiU-ExtB：
![image](https://user-images.githubusercontent.com/8191296/129877474-aa78bbd1-e065-464b-9458-9c44d236608d.png)
（非常罕有地新細明體正確的例字）

集韻 （https://ctext.org/library.pl?if=en&file=9487&page=13#%F0%A6%8C%BB）：
<img width="105" alt="image" src="https://user-images.githubusercontent.com/8191296/129877596-4a269700-aea6-4bf1-8dc8-8c962df23a21.png">

得閒寫個提案俾 IRG 改 glyph 改 source 否？

**Comment by JLHwung** [comment]
集韻有南宋本，今存國家圖書館，又存宮內廳書陵部。四庫是寫本，當檢古本爲證。

**Comment by SyaoranHinata** [comment]
![image](https://user-images.githubusercontent.com/8178284/129980159-7bd8b4cc-c6ff-41f0-966b-a3f0f74939a3.png)
