### ISSUE TITLE
清理簡化字！

### ISSUE THREAD

**Issue by Guest-615695028** [ichitenfont/I.Ming#53]
1. 一點明朝體收錄了56,057個漢字字型，加上非漢字字符，數目已逼近（或達到）字庫極限65,535字符。
2. 中日韓兼容表意文字區獨一字型（u+fa0e–u+fa0f、u+fa11、u+fa13–u+fa14、u+fa1f–u+fa21、u+fa23–u+fa24和u+fa27–u+fa29）及u+f91c、u+f9f7可保留，餘者棄去；
3. 《簡化字總表》可類推簡化字，刪去加粗簡體字形及其組字：（斜体为《康熙字典》部首字，保留简体部首形态，组字一并去除）
　　　**愛爱**　**罷罢**　備备　筆笔　**畢毕**　**邊边**　參参　**倉仓**　**嘗尝**　蟲虫　從从
　　　竄窜　達达　**帶带**　黨党　動动　**斷断**　**對对**　隊队　爾尔　豐丰　廣广
　　　**歸归**　**_龜龟_**　國国　**過过**　**華华**　畫画　**匯彙汇**　**夾夹**　薦荐　**將将**　**節节**　**盡尽**
　　　**進进**　**舉举**　殻壳　**來来**　**樂乐**　離离　**歷历**　麗丽　**兩两**　靈灵　**劉刘**
　　　**盧卢**　**虜虏**　**_鹵卤_**　録录　**慮虑**　**買买**　**_麥麦_**　**_黽黾_**　**難难**　**聶聂**　寧宁
　　　**豈岂**　氣气　**遷迁**　親亲　窮穷　**嗇啬**　殺杀　**審审**　聖圣　**時时**　屬属
　　　雙双　**嵗岁**　孫孙　**條条**　萬万　**爲为**　**烏乌**　無无　獻献　鄉乡　寫写
　　　**尋寻**　**亞亚**　**嚴严**　厭厌　業业　**藝艺**　陰阴　**隱隐**　猶犹　與与　雲云
　　　**鄭郑**　**埶执**　**質质**　**_貝贝_**　**賓宾**　産产　**_長长_**　**_車车_**　**_齒齿_**　芻刍　**單单**
　　　**當当**　**東东**　**發发**　**_風风_**　**岡冈**　**咼呙**　**會会**　幾几　**戔戋**　**監监**　**_見见_**
　　　**龍龙**　**婁娄**　**侖仑**　**羅罗**　**_馬马_**　**賣卖**　**門门**　**_鳥鸟_**　**農农**　**齊齐**　**僉佥**
　　　**喬乔**　區区　**師师**　**壽寿**　**肅肃**　**_韋韦_**　**堯尧**　**_頁页_**　**義义**　**_魚鱼_**　**專专**
　　　　　简化偏旁
　　　**讠**〔訁〕只簡化左偏旁。
　　　**饣**〔飠〕只簡化左偏旁。
　　　**𠃓**〔昜〕獨用不簡化。
　　　**纟**〔糹〕只簡化左偏旁。
　　　**⿰〢又**〔臤〕，獨用不簡化。
　　　**𫇦**〔𤇾〕，熒字頭。
　　　只〔戠〕獨用不簡化。
　　　钅〔釒〕只简化左偏旁。
　　　**⿱⺍冖**〔𦥯〕，學字頭。
　　　**𠬤**〔睪〕獨用不簡化。
　　　**𢀖**〔巠〕獨用不簡化。
　　　亦〔䜌〕独用不简化。
4. 不類推簡化字（參考维基词典）
A
碍〔礙〕肮〔肮、骯〕袄〔襖〕
B
**坝**〔垻、壩〕板〔板、闆〕**办**〔辦〕帮〔幫，幚〕宝〔寶〕**报**〔報〕
**币**〔幣〕**毙**〔斃〕**标**〔標〕表〔表、錶〕别〔别、彆〕卜〔卜、蔔〕
**补**〔補〕
C
才〔才、纔〕蚕〔蠶〕灿〔燦〕**层**〔層〕**搀**〔攙〕**谗**〔讒〕**馋**〔饞〕
**缠**〔纏〕忏〔懺〕**偿**〔償〕厂〔厂、廠〕彻〔徹〕尘〔塵〕衬〔襯〕
称〔稱〕**惩**〔懲〕**迟**〔遲〕冲〔衝、沖〕丑〔丑、醜〕出〔出、齣〕
**础**〔礎〕处〔處〕触〔觸〕**辞**〔辭〕**聪**〔聰〕**丛**〔叢〕
D
担〔擔〕胆〔膽〕**导**〔導〕**灯**〔燈〕**邓**〔鄧〕**敌**〔敵〕
籴〔糴〕递〔遞〕点〔點〕淀〔淀、澱〕电〔電〕冬〔冬、鼕〕
斗〔斗、鬥〕独〔獨〕吨〔噸〕**夺**〔奪〕**堕**〔墮〕
E
儿〔兒〕
F
矾〔礬〕范〔范，範〕**飞**〔飛〕坟〔墳〕**奋**〔奮〕
**粪**〔糞〕**凤**〔鳳〕肤〔膚〕**妇**〔婦〕复〔复、復、複、覆〕
G
**盖**〔蓋〕干〔干，乾，幹〕杆〔桿〕秆〔稈〕赶〔趕〕个〔个、個〕
巩〔鞏〕沟〔溝〕构〔構〕**购**〔購〕谷〔谷、榖〕**顾**〔顧〕刮〔刮，颳〕
关〔關〕**观**〔觀〕柜〔櫃〕（又櫸異體字）
H
汉〔漢〕号〔号，號〕合〔合，閤〕核〔核、覈〕**轰**〔轟〕后〔后，後〕
胡〔胡、鬍、衚〕
**壶**〔壺〕沪〔滬〕（日本濾俗字）护〔護〕划〔劃〕**怀**〔懷〕**坏**〔坏（pī）、壞〕
**欢**〔歡〕**环**〔環〕**还**〔還〕回〔回、迴〕伙〔伙、夥〕获〔獲、穫〕
J
**击**〔撃〕**鸡**〔鷄、雞〕积〔積〕极〔极、極〕**际**〔際〕**继**〔繼〕
家〔家、傢〕价〔价、價〕**艰**〔艱〕歼〔殲〕茧〔繭〕**拣**〔揀〕
**硷**〔鹼〕**舰**〔艦〕姜〔姜，薑〕**浆**〔漿〕**桨**〔槳〕**奖**〔奬〕
**讲**〔講〕**酱**〔醬〕胶〔膠〕阶〔階〕**疖**〔癤〕**洁**〔潔〕
借〔借，藉〕**仅**〔僅〕惊〔驚〕竞〔競〕**旧**〔舊〕剧〔劇〕
据〔据、據〕惧〔懼〕卷〔卷、捲〕
K
开〔開〕克〔克、剋〕垦〔墾〕恳〔懇〕夸〔夸、誇〕**块**〔塊〕
亏〔虧〕（又于異體字）困〔困·、睏〕
L
腊〔腊（xī）、臘〕蜡〔蜡（xī）、蠟〕兰〔蘭〕拦〔攔〕栏〔欄〕烂〔爛〕
累〔累、纍〕垒〔垒、壘〕类〔類〕里〔里、裏〕礼〔禮〕隶〔隶（dài）、隸〕
帘〔帘、簾〕联〔聯〕怜〔憐〕**炼**〔煉〕**练**〔練〕粮〔糧〕
**疗**〔療〕**辽**〔遼〕了〔了、瞭〕猎〔獵〕**临**〔臨〕邻〔鄰〕
岭〔嶺〕**庐**〔廬〕**芦**〔蘆〕**炉**〔爐〕**陆**〔陸〕**驴**〔驢〕
**乱**〔亂〕
M
么〔麽〕（又幺異體字）霉〔霉、黴〕蒙〔蒙、矇、濛、懞〕梦〔夢〕面〔面、麵〕
庙〔廟〕灭〔滅〕蔑〔蔑、衊〕亩〔畝〕
N
**恼**〔惱〕**脑**〔腦〕拟〔擬〕**酿**〔釀〕**疟**〔瘧〕
P
**盘**〔盤〕辟〔辟、闢〕**苹**〔蘋〕凭〔憑〕扑〔扑、撲〕仆〔仆、僕〕朴〔朴、樸〕
Q
**启**〔啓〕**签**〔籤〕千〔千、韆〕**牵**〔牽〕**纤**〔縴、纖〕
窍〔竅〕窃〔竊〕**寝**〔寢〕**潜**〔潛〕**庆**〔慶〕琼〔瓊〕
秋〔秋、鞦〕曲〔曲、麯〕**权**〔權〕**劝**〔勸〕确〔确、確〕
R
**让**〔讓〕扰〔擾〕**热**〔熱〕**认**〔認〕
S
**洒〔洒、灑〕伞〔傘〕**丧**〔喪〕**扫**〔掃〕**涩**〔澀〕晒〔晒、曬〕
**伤**〔傷〕舍〔舍、捨〕沈〔沈、瀋〕（又沉異體字）声〔聲〕胜〔勝〕湿〔濕〕
**实**〔實〕适〔适、適〕**势**〔勢〕**兽**〔獸〕**书**〔書〕术〔术、術〕
**树**〔樹〕帅〔帥〕松〔松、鬆〕**苏**〔蘇、囌〕虽〔雖〕随〔隨〕
T
台〔台、臺、檯、颱〕抬〔抬、擡〕态〔態〕（又忲結構異體字）**坛**〔壇、罈〕
**叹**〔嘆〕**誊**〔謄〕体〔體〕粜〔糶〕**铁**〔鐵〕听〔听、聽〕**厅**〔廳〕
**头**〔頭〕**图**〔圖〕涂〔涂、塗〕**团**〔團、糰〕**椭**〔橢〕
W
洼〔洼、窪〕袜〔袜、襪〕网〔網〕卫〔衛〕稳〔穩〕**务**〔務〕**雾**〔霧〕
X
**牺**〔犧〕**习**〔習〕系〔系、係、繫〕**戏**〔戲〕**虾**〔蝦〕吓〔嚇〕［又粤字，同下（一下）］
咸〔咸、鹹〕**显**〔顯〕**宪**〔憲〕**县**〔縣〕响〔響〕向〔向、嚮、曏〕**协**〔協〕
**胁**〔脅〕**亵**〔褻〕衅〔衅、釁〕**兴**〔興〕**须**〔須、鬚〕**悬**〔懸〕**选**〔選〕旋〔旋、鏇〕
Y
**压**〔壓〕**盐**〔鹽〕阳〔陽〕**养**〔養〕痒〔痒、癢〕样〔样、樣〕**药**〔藥〕**爷**〔爺〕
叶〔叶、葉〕医〔医、醫〕亿〔億〕**忆**〔憶〕**应**〔應〕痈〔癰〕拥〔擁〕［又喃字，用、吃、喝］
佣〔佣、傭〕踊〔踴〕忧〔憂〕优〔優〕邮〔邮、郵〕余〔余、餘〕御〔御、禦〕吁〔吁、籲〕郁〔郁、鬱〕
**誉**〔譽〕**渊**〔淵〕**园**〔園〕**远**〔遠〕愿〔愿、願〕**钥**〔鑰〕跃〔躍〕**运**〔運〕**酝**〔醖〕
Z
杂〔雜〕**赃**〔贜〕脏〔臟、髒〕**凿**〔鑿〕枣〔棗〕灶〔竈〕
**斋**〔齋〕**毡**〔氈〕**战**〔戰〕**赵**〔趙〕折〔折、摺〕这〔這〕
征〔征、徵〕症〔癥〕**证**〔証、證〕只〔隻、只、衹〕致〔致、緻〕制〔制、製〕
钟〔鐘、鍾〕**肿**〔腫〕种〔种、種〕众〔衆〕昼〔晝〕朱〔朱、硃〕烛〔燭〕
筑〔筑、築〕庄〔莊〕（又廡異體字）桩〔樁〕**妆**〔妝〕**装**〔裝〕
**壮**〔壯〕**状**〔狀〕准〔准、準〕浊〔濁〕**总**〔總〕**钻**〔鉆、鑽〕
5. 不確定者，敬請搜索維基詞典，順便補充罕用字發音、釋義。（大陸只讀鏡像站推薦：http://en.wanweicidian.com/）

**Comment by i-font** [comment]
其實我們也想過許多次，不過要扔的話，又有一堆務實問題要處理。首先，許多簡化字也會出現在正體（繁體）的場合。「曲、只、板、郁、吓、叶、胡、松、卜、御、后、斗」等不在話下，「权」也是「尌（樹）」的初文，「腊」〔思積切〕也是乾肉，「听」也是張口笑的樣子。若再數一些歷史出現過的俗字、略字、異寫，如「双、与、万、无、碍、庄」等，也許更複雜。我們商議過許多次，都沒有能避免「殺錯良民」的方案和字表，目前只能認爲無法實行，請諒！

**Comment by SyaoranHinata** [comment]
謝謝 Guest-615695028 的整理。這個表也許有用，但仍不是全表，當中細節也可討論，例如「铁、药、爷」等應否列爲粗體（即刪去）。期望有更深入的探討、更完整的列表^^~

**Comment by Guest-615695028** [comment]
辞、乱、敌，左为舌耶？为氏口耶？不明，去！

**Comment by Guest-615695028** [comment]
無簡化字特有部件者，留以待議。

**Comment by Guest-615695028** [comment]
「权」「树」非「尌（樹）」初文，古無據。花園明朝，無簡體部件者皆從日本形，宜參考之。

**Comment by Guest-615695028** [comment]
若簡化字無法强行清理，則將簡體糸、言、金、食字旁改爲繁體糸、言、金、食字旁，因簡體糸、言、金、食字旁的分化影響簡化字配傳承字型文篇美觀。

**Comment by SyaoranHinata** [comment]
「尌」之甲骨確是「权」，許多學者的文章都已客觀呈現，有據。
那些簡化偏旁，我們已盡力製作出平衡美觀者。日後新版本的「讠」旁亦會更新。

**Comment by hfhchan** [comment]
請明白簡化字本身不是一點明體的重點處理範圍，有核心團隊成員先前貢獻舊字形版的簡化字，以適合部分簡化字使用者的需要。如果要移除簡化字，則需另外安排時間逐字審理。加上字體未達65535字符限制，並無任何壓力需要騰空字符空間。目前團隊正在忙於開發黑體，不會另外安排時間處理簡化字。

**Comment by Guest-615695028** [comment]
Thank you very much! We hope your Sans Serif come in 2022!
