### ISSUE TITLE
一點字坊楷體、仿宋、黑體、圓黑體、隸書、小篆字形何時上市？

### ISSUE THREAD

**Issue by Guest-615695028** [ichitenfont/I.Ming#54]
一點字坊推出《傳承字型筆畫表》，表三爲《字型間不視作區別之筆畫差異》。我們懇切希望一點字坊開發楷體、黑體、圓黑體以實踐所説「明楷不對立」「明黑圓不對立」之情況，隸書、小篆用於探究「傳承字型」之來源。

**Comment by SyaoranHinata** [comment]
我們人手極度不足啊！不知 Guest-615695028 有興趣加入、能幫忙造字嗎？

**Comment by Guest-615695028** [comment]
爲何不開放官網？可參大陸華文諸體、臺標楷體並《傳承字型筆畫表》而製之。

**Comment by Guest-615695028** [comment]
明楷不對立：肉月内一點一挑；月内二橫，或觸橫竪鈎，或不觸。

**Comment by SyaoranHinata** [comment]
Github就是我們的官網。
我們人手極度不足啊！現階段實在沒法製作這麼多字型。不知 Guest-615695028 有興趣加入、能幫忙造字嗎？

**Comment by Guest-615695028** [comment]
> Github就是我們的官網。
> 我們人手極度不足啊！現階段實在沒法製作這麼多字型。不知 Guest-615695028 有興趣加入、能幫忙造字嗎？
一點黑體可以基於《傳承字型部件檢校表》，參考[思源黑體](https://github.com/adobe-fonts/source-han-sans)製作。

**Comment by SyaoranHinata** [comment]
> 一點黑體可以基於《傳承字型部件檢校表》，參考[思源黑體](https://github.com/adobe-fonts/source-han-sans)製作。

我們已正在這樣做，問題是始終太少人。請問閣下能幫忙造字嗎？

**Comment by Guest-615695028** [comment]
願意，請把已完成的《傳承字型部件檢校表》部件郵寄給我，提供指導。

**Comment by SyaoranHinata** [comment]
> 願意，請把已完成的《傳承字型部件檢校表》部件圖示寄到我的郵箱，提供指導。

抱歉閣下誤會了，字型裏的字是要一個一個製作或修改的。我們並沒有「已完成的《傳承字型部件檢校表》部件」，只有集體分工合作的作業，每人都要依《檢校表》已說明的規則，逐字核對目前思源字型的寫法，錄下不符合的字元及它有甚麼不符合的地方，再使用造字軟件逐字人手修改。我詢問閣下能否參與的，是這個實在的作業，而不是「指導」我們已經寫好了的《檢校表》部件形體。如果閣下願意，須加入我們的群體作業，並遵守大家的做法和規定。請問閣下願意嗎？

**Comment by Guest-615695028** [comment]
考慮書寫習慣，皀鬯二部件底部均作匕。

**Comment by SyaoranHinata** [comment]
> 願意。
> 
> 1. 考慮書寫習慣，皀鬯二部件底部均作匕。
> 2. 思源字型包括思源黑體、宋體陸港臺日韓五地字型，凡陸萬陸仟伍佰叁拾伍字；任一字元只要有一地字形符合，直接選用。
>    例：化字只有大陸版符合《檢校表》要求。
> 3. 左金字旁、左食字旁首撇可出頭，其他人字頭撇畫不出頭。

請看清楚我說甚麼。我已說明，閣下不是「指導」我們已經寫好了的《檢校表》部件形體，而是要加入我們的群體作業，並遵守大家的做法和規定。請閣下不要一邊說願意，一邊馬上說要改變大家的做法和規定而不是遵守它的說話。

**Comment by i-font** [comment]
一點字坊工作團隊不但從來沒有在任何正式或非正式場合說過楷體、仿宋、黑體、圓黑體、隸書、小篆字型的上市時間，連製作楷體、仿宋、圓黑體、隸書、小篆字型的未來計劃或安排都沒有。唯一只有就黑體招募人手，希望能製作，但也從來沒有時間表。請 Guest-615695028 閣下不要無理發問，把閣下的幻想強加到我們身上。我們團隊並沒有責任去服務閣下的幻想。

如果閣下眞的願意幫忙，首先的首先，請閣下好好運用大腦，不要重複提一些我們已回應了不會這麼做的要求，做一些我們已說明並不會如此的事，作無謂的糾纏，浪費大家的時間，打擊大家的士氣。我們的成品是以開源釋出的，如果閣下眞的很想突破我們的規矩，大可以自行去fork，拿我們的成品去改造，並把改造結果以開源授權再發佈出來。而不是企圖透過閣下的嘴巴喝停我們手頭上的工作，改變我們的做法，去滿足閣下、爲閣下服務。

大腦乃至寶，盼君待之好。希望我不用對閣下說第三次。共勉。

**Comment by Guest-615695028** [comment]
原评论已修改。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ichitenfont/I.Ming"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月9日(星期四) 凌晨1:28
***@***.***&gt;;
抄送:&nbsp;"Jack ***@***.******@***.***&gt;;
主题:&nbsp;Re: [ichitenfont/I.Ming] 一點字坊楷體、仿宋、黑體、圓黑體、隸書、小篆字形何時上市？ (#54)





  
願意。
  
考慮書寫習慣，皀鬯二部件底部均作匕。
 
思源字型包括思源黑體、宋體陸港臺日韓五地字型，凡陸萬陸仟伍佰叁拾伍字；任一字元只要有一地字形符合，直接選用。
 例：化字只有大陸版符合《檢校表》要求。
 
左金字旁、左食字旁首撇可出頭，其他人字頭撇畫不出頭。
   
請看清楚我說甚麼。我已說明，閣下不是「指導」我們已經寫好了的《檢校表》部件形體，而是要加入我們的群體作業，並遵守大家的做法和規定。請閣下不要一邊說願意，一邊馬上說要改變大家的做法和規定而不是遵守它的說話。
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
