### ISSUE TITLE
部分需要二（三）選一入一點明朝的字組。（不符合《傳承字形部件檢校表》的應捨棄）

### ISSUE THREAD

**Issue by Guest-615695028** [ichitenfont/I.Ming#55]
U+4E1F / U+4E22
U+4E48 / U+5E7A
U+4E89 / U+722D
U+4EDE / U+4EED
U+4F75 / U+5002
U+4FA3 / U+4FB6
U+4FC1 / U+4FE3
U+4FDE / U+516A
U+4FF1 / U+5036
U+5024 / U+503C
U+5077 / U+5078
U+507D / U+50DE
U+514C / U+5151
U+514E / U+5154
U+5156 / U+5157
U+518A / U+518C
U+51C0 / U+51C8
U+51E2 / U+51E3
U+5203 / U+5204
U+520A / U+520B
U+5220 / U+522A
U+5225 / U+522B
U+5238 / U+52B5
U+5239 / U+524E
U+524F / U+5259
U+525D / U+5265
U+5292 / U+5294
U+52FB / U+5300
U+5355 / U+5358
U+5373 / U+537D
U+5377 / U+5DFB
U+53C1 / U+53C2
U+53C3 / U+53C4
U+5415 / U+5442
U+541E / U+5451
U+5433 / U+5434 / U+5449
U+5436 / U+5450
U+543F / U+544A
U+5527 / U+559E
U+55A9 / U+55BB
U+5618 / U+5653
U+568F / U+5694
U+56EF / U+56FD
U+5708 / U+570F
U+570E / U+5713
U+5716 / U+5717
U+5759 / U+5DE0
U+57D2 / U+57D3
U+5848 / U+588D
U+5861 / U+586B
U+5897 / U+589E
U+58EE / U+58EF
U+58FD / U+5900
U+5910 / U+657B
U+5932 / U+672C
U+5965 / U+5967
U+5968 / U+596C / U+734E 
U+5986 / U+599D
U+598D / U+59F8
U+59CD / U+59D7
U+59EB / U+59EC
U+5A1B / U+5A2F / U+5A31 
U+5A55 / U+5AAB
U+5A7E / U+5AAE
U+5AAA / U+5ABC
U+5AAF / U+5B00
U+5B0E / U+5B14
U+5B24 / U+5B37
U+5B73 / U+5B76
U+5BAB / U+5BAE
U+5BDB / U+5BEC
U+5BDC / U+5BE7
U+5BDD / U+5BE2
U+5C02 / U+5C08
U+5C06 / U+5C07
U+5C13 / U+5C14
U+5C19 / U+5C1A
U+5C2A / U+5C2B
U+5C36 / U+5C37
U+5C4F / U+5C5B
U+5CE5 / U+5D22
U+5DD3 / U+5DD4
U+5E21 / U+5E32
U+5E2F / U+5E36
U+5E76 / U+5E77
U+5EC4 / U+5ECF
U+5F11 / U+5F12
U+5F37 / U+5F3A
U+5F39 / U+5F3E
U+5F50 / U+5F51
U+5F54 / U+5F55
U+5F59 / U+5F5A
U+5F5B / U+5F5C
U+5F5D / U+5F5E
U+5F65 / U+5F66
U+5FB3 / U+5FB7
U+5FB4 / U+5FB5
U+6075 / U+60E0
U+6085 / U+60A6
U+609E / U+60AE
U+60B3 / U+60EA
U+6120 / U+614D
U+613C / U+614E
U+6229 / U+622C
U+622F / U+6231
U+6236 / U+6237
U+623B / U+623E
U+629B / U+62CB
U+629C / U+62D4
U+6329 / U+635D
U+633F / U+63D2 / U+63F7 
U+634F / U+63D1
U+635C / U+641C
U+63B2 / U+63ED
U+63FA / U+6416 / U+6447
U+63FE / U+6435
U+6483 / U+64CA
U+654E / U+6559
U+6553 / U+655A
U+65E2 / U+65E3
U+6602 / U+663B
U+665A / U+6669
U+66A8 / U+66C1
U+66FD / U+66FE
U+67B4 / U+67FA
U+67E5 / U+67FB
U+67F5 / U+6805
U+68B2 / U+68C1
U+6961 / U+6986
U+6982 / U+69EA
U+6985 / U+69B2
U+699D / U+6A27
U+69C7 / U+69D9
U+69D8 / U+6A23
U+6A2A / U+6A6B
U+6B65 / U+6B69
U+6B72 / U+6B73
U+6B7F / U+6B81
U+6BBB / U+6BBC
U+6BC0 / U+6BC1
U+6BCE / U+6BCF
U+6C32 / U+6C33
U+6C5A / U+6C61
U+6C92 / U+6CA1
U+6D44 / U+6DE8
U+6D89 / U+6E09
U+6D97 / U+6D9A
U+6D99 / U+6DDA
U+6DE5 / U+6E0C
U+6DF8 / U+6E05
U+6E07 / U+6E34
U+6E29 / U+6EAB
U+6E88 / U+6F59
U+6E89 / U+6F11
U+6EDA / U+6EFE
U+6F5B / U+6FF3
U+7028 / U+702C
U+70BA / U+7232
U+712D / U+7162
U+7155 / U+7199
U+7174 / U+7185
U+72B6 / U+72C0
U+7464 / U+7476
U+74F6 / U+7501
U+7522 / U+7523
U+75E9 / U+7626
U+76A1 / U+76A5
U+771E / U+771F
U+773E / U+8846
U+7814 / U+784F
U+797F / U+7984
U+79BF / U+79C3
U+7A05 / U+7A0E
U+7A42 / U+7A57
U+7B5D / U+7B8F
U+7BB3 / U+7C08
U+7BE1 / U+7C12
U+7CA4 / U+7CB5
U+7D55 / U+7D76
U+7DA0 / U+7DD1
U+7DD2 / U+7DD6
U+7DE3 / U+7E01
U+7DFC / U+7E15
U+7E48 / U+7E66
U+7FAE / U+7FB9
U+7FF6 / U+7FFA
U+80FC / U+8141
U+812B / U+8131
U+817D / U+8183
U+8203 / U+8204
U+820D / U+820E
U+8216 / U+8217
U+8358 / U+838A
U+83D1 / U+8458
U+8480 / U+8495
U+848B / U+8523
U+848D / U+853F
U+8570 / U+8580
U+85AB / U+85B0
U+85F4 / U+860A
U+865A / U+865B
U+86FB / U+8715
U+885B / U+885E
U+886E / U+889E
U+88C5 / U+88DD
U+8A2E / U+8A7D
U+8AAA / U+8AAC
U+8ACC / U+8AEB
U+8B20 / U+8B21
U+8C5C / U+8C63
U+8D70 / U+8D71
U+8EFF / U+8F27
U+8F1C / U+8F3A
U+8F3C / U+8F40
U+8FBE / U+8FD6
U+8FF8 / U+902C
U+9059 / U+9065
U+90A2 / U+90C9
U+90CE / U+90DE
U+90F7 / U+9109 / U+9115
U+9196 / U+919E
U+91A4 / U+91AC
U+9203 / U+9292
U+92B3 / U+92ED
U+9304 / U+9332
U+932C / U+934A
U+93AD / U+93AE
U+95B1 / U+95B2
U+9667 / U+9689
U+9751 / U+9752
U+9759 / U+975C
U+976D / U+9771
U+9839 / U+983D
U+984F / U+9854
U+985A / U+985B
U+98EE / U+98F2
U+9905 / U+9920
U+99B1 / U+99C4
U+99E2 / U+9A08
U+9AA9 / U+9AAB
U+9AD8 / U+9AD9
U+9AEA / U+9AEE
U+9B2C / U+9B2D
U+9C1B / U+9C2E
U+9CEF / U+9CF3
U+9D87 / U+9DAB
U+9DC6 / U+9DCF
U+9EAA / U+9EAB
U+9EBC / U+9EBD
U+9EC3 / U+9EC4
U+9ED1 / U+9ED2

**Comment by hfhchan** [comment]
你拷貝的是「Unicode 原格分離」列表。那個列表有很多錯。夲 U+5932 和 本 U+672C 是不同源的字。
暫不考慮用此表清理 I.Ming。
