### ISSUE TITLE
一點明朝在中日韓統一表意文字擴展B區以降收字依據爲何？

### ISSUE THREAD

**Issue by Guest-615695028** [ichitenfont/I.Ming#56]
字客網統計數據：
基本區 20406/20992
兼容區 104/512
擴展A區 5897/6592
擴展B區 25962/42720
擴展C區 396/4160
擴展D區 119/224
擴展E區 519/5776
擴展F區 1649/7488
兼容補充區 7/544
擴展G區：46/4944
字元總數：57657/101360

**Comment by SyaoranHinata** [comment]
並非常用的字區域，乃承襲自前身檔案的舊形，這點我們已在主要說明文件裏交代過。
感謝閣下的建議，但有些與我們的主旨不符，或者與我們已作的決定有衝突。比如用變形選擇器收錄異體，會使一些尚不支援的軟件無法調用該字形。又如「賣」和「𧶠」不能相混，我們早已說明。

**Comment by Guest-615695028** [comment]
1. 賣（mai4）用中簡，𧶠（yu5）用日簡。
2. 糸、言、金、食字旁不再簡化。

**Comment by hfhchan** [comment]
基本區與擴展A區內含不少訛字，特別是只有T3源和GE源的字。如果有正字漏掉，歡迎提出，我們另外安排人手製作。

**Comment by hfhchan** [comment]
如果發現基本區和擴展A區裏面漏掉了一些常用字或者罕用正字，請於 https://github.com/ichitenfont/I.Ming/issues/22 提出，並逐字貼上使用證據，好讓團隊可以更有效地安排人手。

**Comment by Guest-615695028** [comment]
據字符映射表，一點明朝已收不少基本區訛字，如舋、畳、潜。

**Comment by hfhchan** [comment]
> 一點明朝已收不少基本區訛字
刪字要人手

> 基本區和擴展A區理應補齊。
畫字更加要人手

**Comment by hfhchan** [comment]
> 一點明朝已收不少基本區訛字
刪字要人手，亦要反覆考證是不是訛字。既然字體仲有空位，本團隊現階段唔打算花時間處理。

> 基本區和擴展A區理應補齊。
畫字更加需要人手。本團隊現階段唔打算花時間處理訛字。

我知你對訛字好抗拒，我哋都對訛字好抗拒，但係你反覆 feedback 我哋話我哋點解唔處理，係解決唔到問題，請見諒。

**Comment by hfhchan** [comment]
我哋已經多番解釋本項目嘅優先主次同考量，訛字我哋目前一蓋不處理。
如果你得閒嘅話，想補齊基本區同擴展A區嘅訛字，歡迎畫好 D 你想補嘅 glyph 再 send 俾我哋。
如果你冇時間補字，但係有時間繼續做塘邊鶴，恕我哋未能奉陪。

**Comment by hfhchan** [comment]
每秒花喺訛字、花喺重複回答點解唔處理訛字嘅時間，就係團隊小一秒畫一點黑體嘅時間。閣下每次回覆團隊每一個成員都會收到電郵通知，你不斷重複糾纏喺訛字上面，團隊成員都好懊惱點講明白你聽。實際上影響到團隊士氣同貢獻進度。希望閣下高抬貴手。

**Comment by i-font** [comment]
本團隊日常以中文作爲本項目的工作語文，唯中文不限於國語，粵語亦屬之。請不要替我們僭建規則，謝謝。
