### ISSUE TITLE
再談清理簡化字

### ISSUE THREAD

**Issue by Guest-615695028** [ichitenfont/I.Ming#57]
* 若簡化字無法强行清理，則將簡體糸、言、金、食字旁改爲繁體糸、言、金、食字旁，因簡體糸、言、金、食字旁的分化影響簡化字配傳承字型文篇美觀。 @i-font #53 #56

**Comment by SyaoranHinata** [comment]
抱歉我們目前眞的沒有人手。如果閣下執着於這兩個已關閉了的舊issue內容，不知閣下能參與動手改字嗎？我們很歡迎閣下fork出閣下所述的版本。

**Comment by hfhchan** [comment]
如無必要請勿相同話題開多個 issue。

**Comment by Guest-615695028** [comment]
Sorry, I haven't got a tool for this. Could you please recommend one?
