### ISSUE TITLE
粗體/Bold

### ISSUE THREAD

**Issue by ddlr** [ichitenfont/I.Ming#6]
(sorry, I'm not good at writing Chinese! 很抱歉，我的中文不好)

I was wondering if there will be a bold version of the font in the future.

謝謝！

**Comment by hfhchan** [comment]
There are currently no plans for a bold version.

I.Ming is based on IPAmj and predecessors/derivatives, of which there is no bold variant.

Release of a bold version is unfortunately not attainable in the near future due to resource constraints.

**Comment by ddlr** [comment]
I understand, thank you for the quick response!
