### ISSUE TITLE
“藴”的問題。

### ISSUE THREAD

**Issue by garfieldLSY** [ichitenfont/I.Ming#60]
我在打簡體的“藴”和“緼”時，并没有正常顯示舊字形，而是“昷”之外的部分是舊字形，“昷”本身不是。
請看看有没有别的“昷”爲部首的簡體字没有把“昷”的部分以舊字形的方式呈現出來。

**Comment by hfhchan** [comment]
這是因為在 Unicode 縕和蘊與緼和藴是不同的字，I.Ming 只是承襲 IPA Mincho 的字符，沒有特別處理。

**Comment by garfieldLSY** [comment]
原來如此，那等我有機會以後自己改一個罷。



---- 回复的原邮件 ----
| 发件人 | Henry ***@***.***> |
| 日期 | 2021年12月02日 20:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ichitenfont/I.Ming] “藴”的問題。 (Issue #60) |

這是因為在 Unicode 縕和蘊與緼和藴是不同的字，I.Ming 只是承襲 IPA Mincho 的字符，沒有特別處理。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
