### ISSUE TITLE
The characters for "歩" are not standardized.

### ISSUE THREAD

**Issue by chankaede** [ichitenfont/I.Ming#61]
I don't speak English or Chinese, so I use machine translation.
I can understand if it is in Japanese.

In I.Ming-7.01, the character form of 歩 (U+6B69) is not unified. Could you please fix it?
![歩](https://user-images.githubusercontent.com/95613646/144816091-aed7a227-20c8-4206-ae43-05e80020263f.png)

**Comment by aikahiiragi** [comment]
我的看法是，因爲「步」有字理的寫法是「𣥂」，而「𣥂」在檢校表裏有規定，所以「一點明體」作海色的字，「一點明體異體」作地色的字。
而「歩」字不是有字理的寫法，也不是正常正體（繁體）中文裏的用字，所以就承繼IPA明朝，不再修改或處理。

**Comment by chankaede** [comment]
> 我的看法是，因爲「步」有字理的寫法是「𣥂」，而「𣥂」在檢校表裏有規定，所以「一點明體」作海色的字，「一點明體異體」作地色的字。 而「歩」字不是有字理的寫法，也不是正常正體（繁體）中文裏的用字，所以就承襲「IPA明朝」（ IPA Mincho ）的字符，沒有特別處理。

I was very discouraged. You are thinking only about Chinese speakers and not at all about those who use Japanese _kyujitai_.
The Kangxi dictionary belongs to everyone in East Asia. It's not just about Chinese.

**Comment by chankaede** [comment]
README.md says "一点明朝". This is clearly Japanese. Not in Chinese.
Please, please. Don't abandon those who use traditional Japanese. Don't be Chinese-speaker-centric.

**Comment by hfhchan** [comment]
> I was very discouraged. You are thinking only about Chinese speakers and not at all about those who use Japanese kyujitai.

We are sorry but as a small volunteer team, we do not have enough human resources to cover non-Traditional Chinese character set.  Even for the Traditional Chinese character set, we have only covered the most common usages of Mandarin Chinese and Cantonese, but we do not have the resources to cover other characters used by other Sinitic Languages, such as Hokkien or Taiwanese.

Of course we would not mind your contribution if you are able to use font creation software and make the required changes, however, as non-Chinese is currently out of the project scope, we cannot devote resources to maintaining its upkeep.  Unless we also have other Japanese speaking contributors who are fluent in character etymology and willing to join our team, I think we are unable to devote much resources to the task.

>  The Kangxi dictionary belongs to everyone in East Asia. It's not just about Chinese.

I am aware of the authority status of the Kangxi Dictionary in Japan. Rest be assured our team does not intend to monopolize it.  The project scope of I.Ming is to provide a reference font according to the [Inherited Glyphs](https://github.com/ichitenfont/inheritedglyphs) standard, which doesn't directly use the glyphs from Kangxi or Morahashi Dictionary, but also samples dictionaries and printed texts from Ming dynasty until late 20th century.

**Comment by hfhchan** [comment]
This is also the same issue as https://github.com/ichitenfont/I.Ming/issues/60.

**Comment by chankaede** [comment]
> Of course we would not mind your contribution if you are able to use font creation software and make the required changes, however, as non-Chinese is currently out of the project scope, we cannot devote resources to maintaining its upkeep. Unless we also have other bilingual Chinese/Japanese speaking contributors who are fluent in character etymology and willing to join our team, I think we are unable to devote much resources to the task.

Can't I join the team?

**Comment by hfhchan** [comment]
Regarding the other issue #65 you just opened, I agree that in a ideal implementation we will make 歩 (U+6B69) display the same as 步 (U+6B65), same as 青 (U+9752) and 靑 (U+9751).  But we have lack of human resources.

**Comment by hfhchan** [comment]
> Can't I join the team?

As a lot of our discussion involves scholarly discussion in written Chinese, we are only able to welcome members who are proficient in written Chinese to join.

**Comment by hfhchan** [comment]
We have some contributors from mainland who also know Japanese.  Let me ask them if they have free time to handle common characters used by Japanese. But there is no promise or gurantee.

**Comment by chankaede** [comment]
> > Can't I join the team?
> 
> As a lot of our discussion involves scholarly discussion in written Chinese, we are only able to welcome members who are proficient in written Chinese to join.

😭……

**Comment by hfhchan** [comment]
If you know python and can gather a list of characters which need to be remapped, I think you can use fonttools to remap the characters.

**Comment by i-font** [comment]
很抱歉讓你覺得灰心，我們並不是排除使用日文的朋友，遺憾的是我們的團隊實在太小。雖名爲團隊，但每人都有工作量龐大的正式工作，都只能在僅餘的工餘時間中擠出一小點來貢獻大家的義務工作。日常溝通也只能以中文爲主。

如果閣下有興趣，其實可以用造字軟件修改好我們未及處理的字元，按《檢校表》所述來處理即可，完成之後，把含有閣下修改過的字元之檔案，上傳到這裏來，並列出閣下曾修改過的字元。我們日後更新時，便可以檢査閣下的修改是否適合，若適合的話便可以匯整到日後版本的字型檔案中。

I'm sorry to discourage you, but we're not excluding our Japanese speaking friends.  Unfortunately, our team is too small. All members have formal jobs with huge workloads. We can only squeeze a few minutes out for our voluntary contribution. Our daily communication is also mainly in Chinese.

If you are interested, you can use font making software to modify the characters that we have not yet processed, and process them as described in the "component list". When we update the font in the future, we can check whether your changes are suitable, and if they are, we can integrate them into future versions of the font file.
