### ISSUE TITLE
1、为什么「郎」「朗」左部不作「良」，参考康熙字典和其他旧字形即如此。2、一点明体异体是否可以调整「眾」「聚」下部为「乑」，同时「眾」作「衆」形。

### ISSUE THREAD

**Issue by i-ug-yang** [ichitenfont/I.Ming#63]

**Comment by i-font** [comment]
一點明體盡量以[《檢校表》的推薦字形](https://github.com/ichitenfont/inheritedglyphs)爲依歸。而《檢校表》推薦字形的取捨，主要以以部件爲單位，盡量在不悖於約定俗成的條件下，選出最能彰顯字形、最有代表性和系統性的傳承字形形體。而約定俗成的衡量，主要審視從多部權威字書和多本彫版古籍、鉛活字字模印刷物、照相植字印刷物和現代印刷物中採樣的結果，個別疑難字會再進行跨地域的抽樣査問。

換言之，並不是只要在以往出現過那種形體，我們就會盲目地列爲推薦字形。我們是會站在字理的角度，加以梳理和擇優從之。

閣下詢問的這兩個部件，在《檢校表》中均已說明。

一、良部件

![圖片](https://user-images.githubusercontent.com/24702034/156740098-de574970-051d-482b-9472-6837df5fd4b3.png)

對比甲金篆文那個「廊」的象形字，「良」字的頂部和底部都經過訛變，無法以明楷筆畫存古，因此這並不在重點。

要彰顯字理，重點在於「良部件」不要與「皀部件」混同。參考採樣結果，「良部件」的區分重點，在於上方的橫筆。只要上方統一保持橫筆，即可妥善區分，保留字理。

二、𫡑

![圖片](https://user-images.githubusercontent.com/24702034/156741336-a6011882-457f-48e8-8c8a-a08548a459eb.png)

對比甲金篆文，這個部件一直由三個「人」字組成，是會意字。隸變以後，主要有兩種寫法：甲形者，中間的人寫作「亻」（俗稱「立人」形），左右仍作「人」形。乙形者，中間寫作「亻」的同時，左邊的人變形作兩撇，右邊的則變作側人。在約定俗成方面，兩種字形皆出現在採樣之中。但是於字理上，比較兩種形體，甲形者仍保留了三人，可以直接會意。乙形者經過訛變，已再難看出是三人。因此甲形比乙形明顯佔優。我們沒有棄甲形取乙形之理。

而「眾」的上方，甲金作「日」，篆作「目」，均可會意。隸書寫作「橫目」，文字構理沒變化。後來增撇，變成不可解的部件，該部件再變作「血」形，是訛變再訛變。而且變形後，並沒有產生容易理解的新構意，不算作理據重構。換言之，在字理上，也是從「目」者比從「血」者優勝。而取樣結果上，兩形皆有。綜合起來，我們也一樣，沒有棄目形取血形之理。

希望這解釋能讓閣下明白，謝謝。
