### ISSUE TITLE
“钘”字的字形問題

### ISSUE THREAD

**Issue by garfieldLSY** [ichitenfont/I.Ming#64]
“钘”和它的繁體“鈃”一樣，在傳承字形中右邊應該是“幵”，但是在I.明體裏這倆字形不一樣，“钘”的右邊并不是一個“幵”，而是一個“开”。

**Comment by lxgw** [comment]
「钘」字读 xíng 也读 jiān，读 xíng 的时候，右面是「开」，读 jiān 的时候，右边是「幵」。

Unicode 里「銒」（U+9292，jiān）和「鈃」（U+9203，xíng）是分开的，不过简体只有一个「钘」，取 xíng 的读音。

**Comment by garfieldLSY** [comment]
我囸，懂力（這池沼的U碼……）



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月04日 10:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ichitenfont/I.Ming] “钘”字的字形問題 (Issue #64) |

「钘」字读 xíng 也读 jiān，读 xíng 的时候，右面是「开」，读 jiān 的时候，右边是「幵」。

Unicode 里「銒」（U+9292，jiān）和「鈃」（U+9203，xíng）是分开的，不过简体只有一个「钘」，取 xíng 的读音。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aikahiiragi** [comment]
U碼超級池沼
令大家的工作和判定都很困難，怎麼做都難以解決所有問題

**Comment by hfhchan** [comment]
此處非同源法則 (non-cognate rule) 無法適用，但兩字的標準形^1 一樣 ^2。

1: 中國源的字理論上只交附合國標字形的字，國家政策。
2:「需不同形要求」的唯一例外是月月和肉月旁，除了保存康熙字典的區分格局，還牽涉港、台的橫向擴展問題。

**Comment by garfieldLSY** [comment]
欸，懂了。



---- 回复的原邮件 ----
| 发件人 | Henry ***@***.***> |
| 日期 | 2022年03月05日 22:12 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ichitenfont/I.Ming] “钘”字的字形問題 (Issue #64) |

此處非同源法則 (non-cognate rule) 無法適用，但兩字的標準形^1 一樣 ^2。

1: 中國源的字理論上只交附合國標字形的字，國家政策。
2:「需不同形要求」的唯一例外是月月和肉月旁，除了保存康熙字典的區分格局，還牽涉港、台的橫向擴展問題。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by garfieldLSY** [comment]
雀食，解决所有的字形問題那是不可能的，除非再多加幾個字體，但是那樣工作量又太大，現在哪個字體公司遇上這種情况腦袋都得冒烟，没辦法，衹能另請高明，亦或是自己改字體（前提是得會改）。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月05日 17:25 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [ichitenfont/I.Ming] “钘”字的字形問題 (Issue #64) |

U碼超級池沼
令大家的工作和判定都很困難，怎麼做都難以解決所有問題

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
