### ISSUE TITLE
"青" 的問題

### ISSUE THREAD

**Issue by chankaede** [ichitenfont/I.Ming#65]
In Unicode, 青 and 靑 are not inclusive. They are assigned the codes U+9752 and U+9751, respectively. Also, neither are Compatibility Ideographs.
In other words, U+9752 must appear in the form of [an image](https://glyphwiki.org/glyph/u9752.svg). The current letter form is incorrect.

See also:
- https://glyphwiki.org/wiki/u9752
- https://glyphwiki.org/wiki/u9751

**Comment by hfhchan** [comment]
This is the Source Separation Rule problem in Han Unification which is causing so many problems.  As the main use case of this font is for Traditional Chinese, and 青 (U+9752) is the predominant code-point used by Traditional Chinese, we are forced to copy the glyph for 靑 (U+9751) on to 青 (U+9752).

There is no part in the Unicode Standard or ISO10646 that requires two codepoints to have different glyphs.  The code charts only provide a _reference glyph_ for that particular character in a given locale, but the glyph shape is not _normative_.  Our team made a conscious decision to ignore the Source Separation Rule for characters related to common Traditional Chinese characters only.

**Comment by i-font** [comment]
甚至進一步來說，假如所謂的Unicode標準，或者所謂的ISO10646標準，眞的要求把U+9752定樣作「月」底，那麼，就是該等所謂標準的錯誤，是該等所謂標準無視傳承字形的字理字源需求，無視漢字文字學上的正確需求。我們既然是梳理既存傳承字形，推出傳承字形的推薦形體標準，就絕對不可以且不可能盲目依照這些違反字理字源需求、違反文字學的荒謬要求。

關於這點，我們在《推薦形體表》的前言中已說得清清楚楚。抄錄如下：

//Unicode在實際收字時，不時基於「原字集分離原則」而自打嘴巴，把本應整併收錄的字，分作兩個或多個碼位。Unicode設立「原字集分離原則」，爲的是呼應當時的技術限制，解決與既有通用字集的對應問題。但自從Unicode的漢字收錄進入擴展A區後，Unicode官方已放棄「原字集分離原則」。而且今天已有異體字選擇器（Variation Sequence）、CID字型等技術解決對應問題，「原字集分離原則」已經過時。科技以人爲本，我們絕不應本末倒置，因爲遷就過時的技術、錯誤的碼位區分，而強行收進不符傳承字形的形體。應以字理佔優形體來整併的漢字，還是必須整併。因此本表會遵守上述規則，不會盲目依從「原字集分離原則」。

我們強烈呼籲字型製作者以字理爲本，製作傳承字形的字型時，不要盲從「原字集分離原則」這違反傳承字形原則的過時技術副產品。否則，若製作者只把「値」、「靑」、「爲」等傳承字形，放在5024、9751、7232這些正體（繁體）中文「事實標準」裏少用的碼位；至於正體（繁體）中文「事實標準」裏常用的碼位503C、9752、70BA，卻放置着違反傳承字形規定的「值」、「青」、「為」等字形，只會令用戶容易踩中陷阱，誤用非傳承字形。這種做法顯然違反選擇傳承字形用戶之意願，絕不可取。//

**Comment by aikahiiragi** [comment]
其實呢，我想問頂樓的人兄，爲甚麼要用面世才30年的Unicode所說的，來分判「correct」與「incorrect」呢？要說漢字字形，難道不是文字學學術的標準和依據（換言之即是字理）更重要、更有道理嗎？

古往今來，累積前人智慧和今人硏究成果的文字學學術，學者都知道「青」字的兩種寫法：下方從「円」與從「月」是異體字，是同一個字的不同寫法。它們在一般使用時可以互相替代。即是說，它們是inclusive的，它們是Compatibility Ideographs。

換言之，文字學學術上inclusive的字，卻被Unicode說成是「are not inclusive」；學術上是Compatibility Ideographs的字，卻被Unicode說成是「neither are Compatibility Ideographs」。

In other words，到底是學術的錯，還是Unicode的錯？？？

這個計劃是宏揚傳承字形推薦形體，而傳承字形推薦形體的選定標準，就是在不違反日用的情況下，選最具備字理的字形。所以，在這個計劃裏，「correct」的字就是無礙日用的最具備字理的字形。明顯在字形上有違反的，除非日用情況下沒有更好選擇，否則就是「incorrect」。

眾所周知，「青」字下方從「円」或者從「月」，都符合日用，所以對這兩個字來說，能判定「correct」與「incorrect」就只有字理。

而前輩大大都說了，從「円」的寫法符合字理，從「月」的寫法不符合字理。我就偷懶不解釋了。所以，在這個計劃中，從「円」是correct的，從「月」是incorrect的。

換言之，correct的字形，被頂樓的人兄說成是「incorrect」；incorrect的字形，卻被頂樓的人兄說成是「correct」。

In other words，到底是這個計劃的錯，還是頂樓人兄的錯？？？

基本上就是回到 https://github.com/TakWolf/ark-pixel-font/issues/11 這邊說過的內容一樣——要說漢字字形，爲甚麼只有Unicode標記爲錯誤才算錯字？漢字本身的字理字源沒有say嗎？！No stake in the society嗎？！

再者，正如樓上兩位前輩大大的回應，Unicode並沒有硬性規定兩個字碼要不同形。難道頂樓的人兄就要把Unicode說得這麼硬性嗎？是真正的Unicode有問題，還是「頂樓的人兄所說出來的Unicode」有問題？

要是真正的Unicode有問題，違反字理，那麼，我們這些重視字理的人，就應該有可以選擇不認同Unicode的自由和空間。要是Unicode本身沒有問題，只是「一些人兄所說出來的Unicode」有問題，那麼，這些人兄應當更正自己的說法，把重視字理的權利與空間還給Unicode、還給我們。
