### ISSUE TITLE
「𠉞」字未有收錄

### ISSUE THREAD

**Issue by Violationist** [ichitenfont/I.Ming#66]
「𠉞」字未有收錄
圖中是昭源黑體中的「𠉞」字

![InCollage_20220325_230636122](https://user-images.githubusercontent.com/99552237/160213286-6d58a1f9-22b3-41eb-b1c2-362f562743cd.jpg)

例子
![InCollage_20220325_230704719](https://user-images.githubusercontent.com/99552237/160213346-0472684e-56e6-481d-92c2-e2ee406d7fbc.jpg)

一點明體的顯示
![InCollage_20220325_230720775](https://user-images.githubusercontent.com/99552237/160213327-eed31ca9-280e-4564-86d4-cf663535a6f9.jpg)

**Comment by Hulenkius** [comment]
参见：
#58
