### ISSUE TITLE
「䵑」字未收錄

### ISSUE THREAD

**Issue by imcaimeng** [ichitenfont/I.Ming#67]
「䵑」字在古代典籍中比較常見，建議收錄。

<img width="176" alt="image" src="https://user-images.githubusercontent.com/64359693/165086422-f3092e30-ee7b-41e7-b462-9324a11f0e96.png">

**Comment by i-font** [comment]
可是在ctext數據庫中，似乎不那麼常見？
https://ctext.org/pre-qin-and-han/zh?searchu=%E4%B5%91&reqtype=stats
https://ctext.org/post-han/zh?searchu=%E4%B5%91&reqtype=stats

**Comment by imcaimeng** [comment]
在ctext中顯示見於《爾雅》和《方言》，因為二書都屬於基礎文獻，所以一些重要著作中經常轉引，比如《左傳正義》、《周易述》、《易通釋》、《毛詩傳箋通釋》、《廣雅義疏》、《文獻通考》等等。
另外，「䵑」作為「䵒」或體被收入《說文解字》，ctext數據庫並不會註明。《戰國策》也有「膠漆至䵑」，在ctext中被寫作「膠漆至粘」。

**Comment by i-font** [comment]
明白，我們硏究增收至日後的版本吧。
