### ISSUE TITLE
骤 Linux artificial bold?

### ISSUE THREAD

**Issue by szc126** [ichitenfont/I.Ming#68]
![image](https://user-images.githubusercontent.com/29127915/168399510-de7402f1-954d-4642-a29a-4171122b1e0c.png)

I.Ming v7.0.1

I do not know if this is entirely the Linux renderer's fault.

**Comment by Egnale99** [comment]
Hello, @szc126. It is not Linux renderer's fault but 4 contours (又 and 乑) of 骤 are incorretly anti-clockwised. 

(Screenshot from long time ago.)
![image](https://user-images.githubusercontent.com/64576145/168706762-0ee22477-0b1f-412d-901c-0b1dbb15dab8.png)
