### ISSUE TITLE
字形优化

### ISSUE THREAD

**Issue by Scratchbin** [ichitenfont/I.Ming#69]
笺訚鉴籴类
Var: 盏溅贱戦
[I.MingBinxiao-Regular 20220624.subset.ttf.zip](https://github.com/ichitenfont/I.Ming/files/8975965/I.MingBinxiao-Regular.20220624.subset.ttf.zip)

**Comment by i-font** [comment]
非常感謝！我們稍後會看看，合用的話會用在以後的版本中。
