### ISSUE TITLE
關於子寸才及部件的豎未在同一直綫

### ISSUE THREAD

**Issue by laabaafu** [ichitenfont/I.Ming#70]
帶「子、孑、才」和「寸」部件的很多字（如：子才宯对守寽封村材財犲狩孥）中「亅」唔喺同一直線上；
![寸](https://user-images.githubusercontent.com/78459529/182407997-dc5fba98-30f2-493a-9948-5bf498dc76fe.png)
![子](https://user-images.githubusercontent.com/78459529/182408056-23fa88d9-8293-422a-b52e-02cacaf42325.png)

**Comment by i-font** [comment]
這是IPA明朝本來的設計風格。

**Comment by SyaoranHinata** [comment]
見 [issue 14](../issue/14)。
