### ISSUE TITLE
建議加一粵字

### ISSUE THREAD

**Issue by laabaafu** [ichitenfont/I.Ming#71]
建議增加「𫵱（U+2BD71）」，北流話toet6，廣州白話cat6（廣州）
![cat6](https://user-images.githubusercontent.com/78459529/182408728-f27d444b-75b7-4737-973b-8dcb04b86604.png)
![李氏中文字典](https://user-images.githubusercontent.com/78459529/182408759-8d35891f-a1df-447f-b41b-323bd741793a.JPG)

**Comment by i-font** [comment]
此字實際上寫作「𨳍」，或假「柒」字，不作這種「上山下十」之形。我們無意收錄，同時也希望各位使用約定俗成的眞正粵字，謝謝。
