### ISSUE TITLE
捺筆的起筆處（乀）的覆蓋範圍（異體版）不完整

### ISSUE THREAD

**Issue by Marcus98T** [ichitenfont/I.Ming#74]
比如又、叉、史、吏部件等。
<img width="1086" alt="Screenshot 2022-09-09 at 02 37 39" src="https://user-images.githubusercontent.com/10541683/189201022-d76bfb38-1b5a-4941-8df1-63d03cb0ef17.png">
<img width="915" alt="Screenshot 2022-09-09 at 02 19 06" src="https://user-images.githubusercontent.com/10541683/189201571-e469b7b6-1dff-4184-9a3d-ddfa5f966655.png">

**Comment by i-font** [comment]
您好，感謝意見。其實閣下引述的《檢校表》部份也說了，捺筆的起筆處只視爲設計風格，不視爲字理上有需要的分別，因此一點明體是統一不加這飾筆的。

至於一點明體異體，僅保留了一些在我們處理字型前，已有前人選擇了含飾筆的字，但要是前人也沒選到含飾筆的形體，或者我們有別的需求（例如「又」部件，在檢校表中還要解說它開口與否的問題，因此「又」字元就要有開口者），我們就不會特意加上。

一點明體異體所收錄的字形，不一定代表了我們的選擇立場，有時會額外多收了其他形體。我們推薦的形體，以《推薦形體表》和《檢校表》爲準。如果不是《推薦形體表》和《檢校表》所確立者，即使一點明體異體收錄了一些，我們也沒有計劃全盤收錄。

希望能解答閣下的問題，謝謝！
