### ISSUE TITLE
U+30EDD從「⻌」而非「⻍」

### ISSUE THREAD

**Issue by haydenwong7bm** [ichitenfont/I.Ming#76]
<img width="36" alt="image" src="https://user-images.githubusercontent.com/51369959/189529584-ab4de3fc-cba2-4ae5-8894-b93fc76ce531.png">

**Comment by i-font** [comment]
感謝意見。這個「字」畢竟太特殊，我們有一點作爲例外。而我們比較建議使用「𰻞」而非「𰻝」。
