### ISSUE TITLE
uni2FB7的字宽为2049

### ISSUE THREAD

**Issue by lethefrost** [ichitenfont/I.Ming#77]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/47198693/189631260-23883e4f-aa65-40b2-aa0a-844f64dd0043.png">
其他类似字形都是2048，请问此处是否是一个小小疏漏或是有意为之？

非常感谢诸位辛苦开发这款字体，字形古雅，是我心目中在墨水屏上排版效果最佳的一款明体。

**Comment by i-font** [comment]
感謝您的意見！這看來應該是不太對的，我們將會修正。
