### ISSUE TITLE
「骤」字在电子墨水屏上显示异常

### ISSUE THREAD

**Issue by Reniastyc** [ichitenfont/I.Ming#78]
在电子墨水屏上，「骤」字有一部分无法正常显示，繁体的「驟」字则无此问题

**Comment by i-font** [comment]
您好！請問您使用的是甚麼版本？因爲在[issues #68](68)上已有網友匯報過，最新版本應當已修正了。

**Comment by Reniastyc** [comment]
抱歉，在提這問題的時候未看見8.0版本釋出，我即刻去嘗試8.0版本！
有勞費心！
