### ISSUE TITLE
缺少常用字

### ISSUE THREAD

**Issue by 2ach** [ichitenfont/I.Ming#8]
很奇怪 Excel 套用的時候缺很多常用字
_如：煊 晗 啓_
還要套用舊版來補字

**Comment by hfhchan** [comment]
請問使用 Word 時有沒有出現缺字問題？

**Comment by 2ach** [comment]
> 請問使用 Word 時有沒有出現缺字問題？

剛剛測試了一下，在 Word 中幷不缺這幾個字。

**Comment by 2ach** [comment]
> 我在Excel和Word裏都正常。
> ![image](https://user-images.githubusercontent.com/8178284/52267436-f92d8a80-2973-11e9-86c4-86d78b75a77f.png)
> 奇怪……

確實很奇怪，我現在打開也是正常的了。

**Comment by hfhchan** [comment]
安裝字體後，有時需要重啓應用程式，或者是這個問題。
