### ISSUE TITLE
勝簡化字胜便旁不一樣

### ISSUE THREAD

**Issue by mollen** [ichitenfont/I.Ming#81]
胜字，即勝的簡化字，其部首寫得和原字兩樣，詳見以下圖。前輩學歷有限不曉得是正是錯，不過遇見簡化字偏旁改成舟月旁。

![bild](https://user-images.githubusercontent.com/22658912/193993755-13aea1a8-978c-4b5c-a3d0-f061bd8d7bd4.png)

**Comment by mollen** [comment]
謝謝一一解釋，這種處理很有道理。

非常欣賞貴字體和大家的努力。加油！

**Comment by lxgw** [comment]
「胜利」的「胜」是一种「双声符字」（「声声字」），「朕」省声，「生」声，只不过与「胜肽」的「胜」撞形了。

类似的因汉字简化产生的「声声字」还有「宪」（憲），「𡩜」省声，「先」声。

**Comment by mollen** [comment]
謝謝兩位老師！簡化胜利的胜和胜肽的胜兩個字區別很小，楷書似乎無別，用正體的勝字區分比較明顯。簡化胜字可能可以理解爲假借？便只有一個胜字。班門弄斧。

**Comment by SyaoranHinata** [comment]
眞的要替「簡化字胜」的字理強作解釋，大概就只能說「雙聲符字」。然而這也不才表「簡化字胜」的構形合理。

首先，傳統漢字的「雙聲符字」是非常少的，可說是正常構字方法中的例外。一些被部份學者視爲是「雙聲符字」的字，到底是否眞的是雙聲符，也有爭議。

而「胜」和「宪」，除了雙聲符外，其中一個聲符還要大幅度地省聲，這種減省幅度，比段玉裁認爲「《說文》省聲」中不可信的字例，簡直有過之而無不及。

再加上，那個省聲的聲旁，在未減省之時，正是該簡化字欲取代的原字！換言之，要學會「胜」和「宪」這兩個簡化字的字理，過程中必須先學會「勝」和「憲」。這跟除褲放屁有何異哉？

聲明一下，聲稱「簡化字胜」是形聲字的，可不是我虛構，是一些給簡化字說項的人所說的。

說到底，許多簡化字之所以會如此構形，其成形過程中根本沒有好好考慮字理。以致要說簡化字的字理，總是牽強附會，貽笑大方。

要說「簡化字胜」是「假借」了正體（繁體）字裏的「胜」字，也許還比「雙聲符字」更淺易，但還是得注意這並不是原本六書的「假借」（本無其字的假借），而是在「本有其字」時，拿甲字記乙字的因循方法而已。

在通假字還盛行的遠古年代，本有其字的假借並沒有什麼問題。但那個年代的文本，是讀死人的，比如看到「棗」字卻不指棗子，指「早晨」的「早」；看到「矢」字卻不指箭，指糞便的「屎」。自從漢字已約定俗成要各施其義後，還如此寫字的，就是寫別字。
