### ISSUE TITLE
關於又字的字形建議

### ISSUE THREAD

**Issue by yshumy** [ichitenfont/I.Ming#83]
又字不當封口。既然時傳承字體，又是手的象形，手指岔開才能更好的會意。

<img width="586" alt="截屏2022-10-20 23 04 08" src="https://user-images.githubusercontent.com/103359913/196986408-0096b74a-b760-41eb-bef0-8fc2972060d5.png">
<img width="252" alt="截屏2022-10-20 23 03 35" src="https://user-images.githubusercontent.com/103359913/196986445-c9960971-3b63-42a2-9469-99f46cf059fb.png">

**Comment by yshumy** [comment]
還有，反文旁下邊也是又的變形，最好捺不與左上的撇相連。
![网页捕获_20-10-2022_232515_zi tools](https://user-images.githubusercontent.com/103359913/196991525-fb5831e6-f9d7-4f48-a4fe-bca7f00e3562.jpeg)

**Comment by i-font** [comment]
我們在《檢校表》中已經解釋了「又部件」的取捨：

> 這字篆作「又」，像三根手指，字源上開口與初形較貼近，但即使不開口亦不與別的部件相混，取不開口者比較適應明體造型美觀。

我們的選形原則，是從傳承明體中，盡力挑選最符合字理、同時不悖於約定俗成準則的寫法，並且兼顧美觀設計需求。

在我們的取樣過程中，現代明體所得的「又部件」造型，絕大多數是不開口的。除非該「又部件」的捺筆變點，那麼則絕大多數都開口。

從字型設計角度而言，若「又部件」必須開口，部份明體字的設計較難取得平衡，例如「友」字。若必須開口，那是相當不容易設計得美觀的。

而且設計明體字的參考或採樣，應在明體而言。閣下的擧例，混雜書法楷體、彫版或彫刻活字楷體，甚至隸書。這些字形對明體來說只是旁參，不能作爲絕對的取捨因素，否則會有令明體認楷作母之弊，不符合我們的宗旨。

希望這樣解釋閣下能明白，謝謝。

**Comment by yshumy** [comment]
不敢苟同。康熙字典體是不是明體？它的又字是開口了的。宋元明清歷代又字印刷體都開口，上圖都有印刷體典型案例，列出楷隸是爲了看源流。字形用的多就是正常字形？不看刻工水平和出版機構的權威性？明體是刻工對楷書的模仿，有些刻工任意改字形並不是爲了美觀，而是沒文化。刻工的審美能有多高？字形以對稱爲第一原則那就是審醜。但是還是有字形開口的刻體，說明規矩的刻工不會亂來。當然這些話你不會接受，忠言逆耳，只是聲稱傳承字形有點名不副實。

**Comment by yshumy** [comment]
> 我們在《檢校表》中已經解釋了「又部件」的取捨：
> 
> > 這字篆作「又」，像三根手指，字源上開口與初形較貼近，但即使不開口亦不與別的部件相混，取不開口者比較適應明體造型美觀。
> 
> 我們的選形原則，是從傳承明體中，盡力挑選最符合字理、同時不悖於約定俗成準則的寫法，並且兼顧美觀設計需求。
> 
> 在我們的取樣過程中，現代明體所得的「又部件」造型，絕大多數是不開口的。除非該「又部件」的捺筆變點，那麼則絕大多數都開口。
> 
> 從字型設計角度而言，若「又部件」必須開口，部份明體字的設計較難取得平衡，例如「友」字。若必須開口，那是相當不容易設計得美觀的。
> 
> 而且設計明體字的參考或採樣，應在明體而言。閣下的擧例，混雜書法楷體、彫版或彫刻活字楷體，甚至隸書。這些字形對明體來說只是旁參，不能作爲絕對的取捨因素，否則會有令明體認楷作母之弊，不符合我們的宗旨。
> 
> 希望這樣解釋閣下能明白，謝謝。

不敢苟同。康熙字典體是不是明體？它的又字是開口了的。宋元明清歷代又字印刷體都開口，上圖都有印刷體典型案例，列出楷隸是爲了看源流。字形用的多就是正常字形？不看刻工水平和出版機構的權威性？明體是刻工對楷書的模仿，有些刻工任意改字形並不是爲了美觀，而是沒文化。刻工的審美能有多高？字形以對稱爲第一原則那就是審醜。但是還是有字形開口的刻體，說明規矩的刻工不會亂來。當然這些話你不會接受，忠言逆耳，只是聲稱傳承字形有點名不副實。

**Comment by i-font** [comment]
所謂「宋元明清印刷體」不一定是明體。像閣下的圖片中，即使被閣下圈起來的圖片下方寫着「印刷字形」，但它們明顯只是彫版或彫刻活字楷體，並無明體的基本特徵。而《康熙字典》用的雖然是明體，但它本身的字頭有不少不一致的地方。單是「又」部的103字（見[此連結](https://www.kangxizidian.com/search/index.php?stype=Radical&sword=又&detail=n)），有開口的，有合口的，有捺筆帶飾筆的，有捺筆不帶飾筆的。若再翻査其他部首中包含「又」部件的字，不統一的情況會更多。

如是者，即使我們要依《康熙》，但《康熙》本身就不統一，那麼我們要以哪種形體爲準？如果要偏執如閣下，主張閉口的「又」不能稱爲傳承字形，認爲是「名不副實」，那麼《康熙》裏以閉口「又」示人的字，又是否傳承字形？《康熙》本身又會否「名不副實」？

我們製作「一點明體」，是以傳承字形推薦形體爲依歸。傳承字形推薦形體的標準，已在《檢校表》、《推薦形體表》等標準化文件中說清楚，它是一套經採樣、整理過的規範，包括整理了《康熙》不一致的地方，也包括兼顧專業字型設計的美觀設計需求。不是說《康熙字典》怎麼樣，就每個字都依樣畫葫蘆。

傳承字形本身就有多面形態。閣下有閣下的個人好惡或選擇，絕無問題。但不宜否定本來的事實面貌，並對事實肆意中傷。

「一點明體」是套開源字形，如果閣下不妄加謗詆，把時間花得有意義，大可自行改造，成爲符合閣下審形的字型，閣下甚至可以撰寫說明，解釋閣下如此審形的原因。忠言逆耳，閣下能否接受，聽憑尊便。
