### ISSUE TITLE
建議将古韻羅馬字换成更合理的切韵拼音(TUPA)

### ISSUE THREAD

**Issue by ryanlo713** [ichitenfont/I.Ming#84]
Qjit temx > Qit Temq

[切韵拼音](https://zhuanlan.zhihu.com/p/478751152)

[切韻音系自動推導器](https://graphemecluster.github.io/qieyun-autoderiver/)

**Comment by SyaoranHinata** [comment]
感謝意見，https://graphemecluster.github.io/ 也是個好網站，
不過當中的「[切韻音系自動推導器](https://graphemecluster.github.io/qieyun-autoderiver/)」好像有點問題，不知應該怎樣使用，改換當中的漢字，見圖：
![image](https://github.com/ichitenfont/I.Ming/assets/8178284/d0b86f41-819b-4f96-880f-ed6e4858ba94)

我們找到[另一個自動推導器](https://nk2028.shn.hk/qieyun-autoderiver/)，不知它跟閣下提意的切韻拼音一樣嗎？
![image](https://github.com/ichitenfont/I.Ming/assets/8178284/bd5deb8f-70ec-475f-a190-b85949da3f5c)

另一方面，似乎切韻拼音與古韻羅馬字有些側重點不同，乍看似乎各有千秋。不知閣下可以簡單點出兩者各自的長短嗎？感謝^^

**Comment by graphemecluster** [comment]
@SyaoranHinata 多謝多謝，推導器 v0.2 有一段時間冇 update，現時嘅介面的確係會令唔太熟悉編程嘅人感到困惑。
改善咗呢個問題之後，年尾至下年年頭 https://nk2028.shn.hk/qieyun-autoderiver/ 將會更新至呢個版本。
各位遇到其他問題可以去 https://github.com/nk2028/qieyun-autoderiver/issues/ 留個言、喺 nk2028 Telegram 羣組提出或者直接同我講。

---

https://graphemecluster.github.io 都係我中學時期嘅產物，已經幾年冇更新，期望下年可以抽出時間更新。

**Comment by aikahiiragi** [comment]
抱歉我這個完完全全的外行人，說一個外行人的考慮。
在古韻羅馬字中，如果採用首字母簡寫，它比較有效分辨不同的聲母，
尤其是d和t。

古韻羅馬字中的d只會是定聲母和澄聲母，t只會是端透知徹聲母。
精清莊初章昌聲母會是c，而z雖然有從崇常邪俟船聲母共6個，但都是相對較少見的聲母。

可是切韻拼音剛好相反，尤其是t是超級氾濫，分不到是端透知徹精清莊初章昌10個聲母中的哪一個。
d也同時是定澄從崇常5個聲母的首字。
雖然z只有邪俟船3聲母，但這3聲母是出現率很少的，字母z還有可以利用的空間。
而字母c完全沒有給使用。
我在中古音韻學/聲韻學是行外人，抱歉意見可能不適合，
不過以拼音法來說，用同一個字母作10個聲母（而且那些聲母看來出現率都高）實在未必太好。
而古韻羅馬字設計時，有考慮過聲母代表字的分佈平均問題
（[他的維基頁面](https://zh.m.wikipedia.org/wiki/User:Polyhedron/%E4%B8%AD%E5%8F%A4%E6%BC%A2%E8%AA%9E%E6%8B%BC%E9%9F%B3)上有列出每個聲母的字數，設計時有一併考慮），
在作名字來說，古韻羅馬字是比較優勝的，方便採用首字母縮寫時較易分辨的。

不知道切韻拼音是否真的沒有可能考慮這一點作出改善？
否則採用首字母縮寫時，字母t真的超重得很誇張。

**Comment by untunt** [comment]
谢谢你的建议，不过这和切韵拼音的理念是相反的。切韵拼音在起草之初就定下了“尽可能使用拉丁字母的通用发音”以及”反映发音优先于缩短拼写“的方针，我们认为这是拉丁化转写应该优先考虑的东西，而不能为了照顾首字母不同而把拼法弄得不直观。古韵罗马字把 [dz] 拼成 z、[z] 拼成 zs 就非常违反一般习惯了

当然这方面问题只是实用和审美角度的问题，是次要的，古韵罗马字的主要问题是它的介音和元音有很多不合切韵音系之处

另外缩写不一定只取首字母，比如精母开头的词缩写成 Ts. 也没有问题

**Comment by aikahiiragi** [comment]
@untunt 謝謝你的解釋，我也說明我這個是不專業的角度，尤其是沒有在中古音韻學上去考慮。
不過我所思考的，是在實際數碼命名和排序等處理上的考慮。
這點在粵拼的設計時也有考慮過，粵拼的前身方案之一是教院拼音，
教院拼音用 dz 和 ts 表示 /ts/ 同 /tsʰ/，而粵拼則用 z 與 c 表示。
專家都認爲教院方案這一點是一個小缺陷。因爲用 dz 同 ts 除了兩個字母冗長沒必要之外，
更會影響輸入法的編碼處理。例如很多輸入法都有聲母簡拼功能，
如果我打 ts，在教院拼音方案中，應該識別成「此」這一字的聲母，還是「聽寫」這兩字的聲母？
這樣又增加了重碼率，提高了處理成本，亦都令輸入法更難用。
取複合字母作縮寫的話，若不只取一個，應該要取多少個？
統一取一個定量，有些字的聲母部份會不夠取。
每字都不統一，取的字母數量是浮動的話，就無法反還原。
例如看到 tsrh 的檔案名，它代表的是一個初聲母？是莊+曉？是端+生+曉？
這點對數碼處理，要作檔案名，要排序等等，都是很頭痛的問題。
這並不是「縮短拼寫」，而是在區分上能提供足夠的分辨度，這點對拼音方案來說也是重要的。
以個人看法，
以 z 表示 /dz/、以 c 表示 /ts/ 並沒有違反一般習慣，不少拼音方案也這麼處理，符合以拉丁字母反映通用發音的習慣，
至於是 zs 表示 /z/ 真的是少見，但既然它包含的字不多，是可以接受的，有拿捏過當中的平衡。
現在你們推薦的切韻拼音，可能在音韻原理上很配合廣韻，
但在數碼命名和排序等處理上，可謂是完全沒考慮，沒有嘗試去拿捏一個平衡，而是認為考慮這方面就跟你們的理念相反了。
如果是這樣，我站在數碼命名和排序等處理上去思考，要同意採用切韻拼音去命名的話，就會很難辦。
我覺得至少在聲母的設計上，拿捏一個平衡是百利而無一害的。
甚至我個人認爲連古韻羅馬字也還未真的完全善用，例如匣聲母與其用 gh ，倒不如用 x 才更方便上述的處理而沒有衝突。
希望原諒我在中古音韻上的無知。不過我個人希望是能對中古音韻上以及命名輸入排序上也是能共同包容和平衡的，而不是只一面倒向其中一邊。
若是能有比較好的平衡，我是會支持的。

**Comment by aikahiiragi** [comment]
我想了想，不知算不算是一個折衷，
就是當成是一個便捷模式，
在這便捷模式下，凡「ts」可以借用正式TUPA沒有使用的「c」去取代，
凡「dz」可以借用正式TUPA沒有使用的「x」去取代，
其餘不改變照依TUPA，
透過這種「便捷模式TUPA」來解決我所提出的問題？
允許「便捷模式TUPA」，不會撼動正式TUPA的地位，
只是為我在上方指出的一些確實會面對的問題，提供能平衡一下的一種解決。
謹提出此構想。

**Comment by graphemecluster** [comment]
如果係限於輸入法，我認為呢一點係冇問題嘅，畢竟部分平台粵拼輸入法都支援用 x 代 ng，r 代 aa 等快捷鍵
