### ISSUE TITLE
羋(U+7F8B)與芈(U+8288)字形弄反了

### ISSUE THREAD

**Issue by Huanying04** [ichitenfont/I.Ming#85]
如圖所示，上圖為一點明體中羋(U+7F8B)的字形；下圖為一點明體中芈(U+8288)的字形<br>
![羋](https://user-images.githubusercontent.com/59917505/205331277-94baa71b-e1b2-4591-b360-16deb54de507.png)<br>
![芈](https://user-images.githubusercontent.com/59917505/205331279-0154f333-a9f9-4583-a953-35e58966d141.png)

但Unicode裏羋(U+7F8B)才是羊字頭與下方不相連的字形，而芈(U+8288)則是相連的，因此個人認為兩者應該弄混了
![7f8b](https://user-images.githubusercontent.com/59917505/205331977-cb9544db-6e17-46bf-be3a-f3b9fc40ce63.PNG)
![8288](https://user-images.githubusercontent.com/59917505/205331980-c14bc346-f383-455e-829c-072ffd7429a5.PNG)

**Comment by i-font** [comment]
Unicode的字形並非以字理、字源來考量。依理而言，「⺸」爲「羊」之變體，其實是把羊角「⻀」之形寫得更突顯，它跟下方的「干」形（代表羊的臉）應該是一體的，取相連之形較佳。從「⺸」之字，如「哶𦍟𦎧」等，一點明體皆統一作此形，因此「羋」也不例外。然而「羋」字不算很常用，其分開編碼的異體「芈」(U+8288)更少見，我們才沒有去統一那個異體字符，只着重訂正了相對較常用的「羋」(U+7F8B) 這個碼位的字形而已。

它的較常用碼位之形體已定了。我們會硏究一下異體編碼，若眞的有需要，可以連異體編碼也跟訂正形體統一。
