### ISSUE TITLE
一點明體圖標亂碼？

### ISSUE THREAD

**Issue by laabaafu** [ichitenfont/I.Ming#89]
Win7 HK 一點明體圖標亂碼？
![image](https://user-images.githubusercontent.com/78459529/220111752-0dec7c35-041f-40fb-a706-a37d89c66a97.png)

**Comment by i-font** [comment]
你好，這並不是正常的情況。正常的情況應該如下圖所示：
![圖片](https://user-images.githubusercontent.com/24702034/220539027-45848448-9a62-47b1-8054-81a03c8fb8b0.png)

已知是Windows問題，可以試一試把字型全部刪除乾淨，要刪除得徹底，然後重啟Windows再重新安裝。

**Comment by laabaafu** [comment]
> 你好，這並不是正常的情況。正常的情況應該如下圖所示： ![圖片](https://user-images.githubusercontent.com/24702034/220539027-45848448-9a62-47b1-8054-81a03c8fb8b0.png)
> 
> 已知是Windows問題，可以試一試把字型全部刪除乾淨，要刪除得徹底，然後重啟Windows再重新安裝。

重新把四個一點明體的字體刪除後重裝，解決了字體圖標亂碼問題，這個是舊版留下的問題，新版本解決了。
貴字體並未添加港臺繁體中文的中文名稱。
![擷取](https://user-images.githubusercontent.com/78459529/222145964-721d2a09-17d0-4563-8f64-65c18ffd0a62.PNG)
