### ISSUE TITLE
在 I.Ming 5.00 CP 版中，我作了些更改

### ISSUE THREAD

**Issue by creatxrgithub** [ichitenfont/I.Ming#9]
在 I.Ming 5.00 CP 版中，我作了些更改：
一、增加六十四卦圖象
二、半角的字母數字及符號，便于中英文混排，如編程時用
三、個別文字：同形原則（丸），及與小篆形同原則（气衮），增大區別（曰：5.00版中「日曰」形過于相似）
四、根據觀感，中文符號也作了些少增換。

![Screenshot_2019-03-12_15-42-51](https://user-images.githubusercontent.com/27437178/54230812-959bfd00-44dd-11e9-9c85-909941a57875.png)

**Comment by creatxrgithub** [comment]
![Screenshot_2019-03-12_16-09-04](https://user-images.githubusercontent.com/27437178/54232517-30e2a180-44e1-11e9-85e7-1184526890b8.png)

**Comment by creatxrgithub** [comment]
[i.ming.modify.txt](https://github.com/ichitenfont/I.Ming/files/2958630/i.ming.modify.txt)

**Comment by creatxrgithub** [comment]
在 windows 10 和 ubuntu 18.04 下效果極好，只是，重灌原裝的 windows 8.1 後，字體效果很差。

**Comment by SyaoranHinata** [comment]
歡迎和感謝閣下衍生。「一點明體」已有6.00版本了，大幅修正了5.XX版的字符，可以用新版來再修改啊。

半形字符似乎是黑體？

另外解釋一下「一點明體」的初衷，我們希望整理出平衡字理、美觀和實際使用的字形，具體成果見《檢校表》。

當中，「彈丸的丸」與「執之右旁」是兩個形音義俱不同的字。「彈丸的丸」胡官切，今形作「橫曲鈎（橫折彎鈎）」，而「點」筆內藏。「執之右旁」由「丮」變化而成，几劇切，今形作「橫捺鈎（橫斜鈎）」，而「點」筆破撇出頭。由於兩者並不同形，因此不應運用「同形原則」。「汍」與「𢓃」爲形聲字，從「彈丸的丸」得聲。而「秇」爲「埶、蓺、藝」字初文，從「執之右旁」。

至於「袞」字，古時從「公」聲、從「谷」聲、從「㕣」聲皆有。三者韻尾皆不同，當中「㕣」聲音韻最合，同時亦爲正體（繁體）中文裏最常見者。故我們在「袞 (889E)」取「㕣」聲。Unicode分收的異體「衮 (886E)」取「公」聲。

**Comment by creatxrgithub** [comment]
多謝指教。

我倒是知道「丸丮」不同形，只是不知「丸」作「橫曲鈎（橫折彎鈎）」，而「丮」作「橫捺鈎（橫斜鈎）」。

「气」我是把簡化字的 unicode 那個還原成簡化字，這個字我更傾向使用「气」。

「衮袞」「滚滾」「磙𥕦」這幾個字也是，我把 unicode 字形爲「公」的那個字還原使用「衮」。

半角的字母數字符號，使用的是黑體，較細的那種。

我本想等 6.00 的 CP 版出來後再改，現發現沒必要，因爲那些符號我基本上都改了。

一會提交到另一帖。

**Comment by creatxrgithub** [comment]
i.ming.modify.txt 那個文件是我在 5.00 CP 中作的增改部份

我試了一下 6.00 regular

發現好多字還是濃淡不一，反而不如 5.00 CP，我還是等 6.00 CP 吧。

![Screenshot_2019-03-13_11-48-46](https://user-images.githubusercontent.com/27437178/54293258-ff6fe180-4585-11e9-96b1-fdf256d21eb5.png)

**Comment by creatxrgithub** [comment]
![Screenshot_2019-03-13_11-54-05](https://user-images.githubusercontent.com/27437178/54293636-ba987a80-4586-11e9-85b1-212494d4fef0.png)

**Comment by creatxrgithub** [comment]
我是通過 fontforge 得到 svg
再將增改部份加在末尾，生成字體時就能覆葢前面的同名字符。
增改 6.00 造成文字粗細不一，但加裝原版 6.00 後又好了，可能是不是生成的 svg 中某些部份是引用的。
又或許，需要重啓？

**Comment by creatxrgithub** [comment]
我是通過 fontforge 得到 svg
再將增改部份加在末尾，生成字體時就能覆葢前面的同名字符。
增改 6.00 造成文字粗細不一，但加裝原版 6.00 後又好了，可能是不是生成的 svg 中某些部份是引用的。
又或許，需要重啓？

**Comment by creatxrgithub** [comment]
原版字體中的「丸」作偏旁時，點在內部，感覺不好看，「丸」的點在內部，我覺得可能用「撇」在內部美感好，所謂的「撇」指用頭尾粗細一致的筆畫。

**Comment by SyaoranHinata** [comment]
你說你的字「濃淡不一」，在下從附圖所見，不是變了濃淡，而是直接變成了黑體。換言之，在字型檔案內，好些字元的字圖（glyph）直接遺失了。接着系統就自動把字型裏的缺字用黑體顯示。如欲解決，得檢査不見了甚麼字圖。

至於「一點明體」原來字形寫法的釐定依據，我已說了。當然閣下也有權不依，改成你喜歡的字型。其實我看不明白閣下的modify.txt，抱歉呢！

**Comment by creatxrgithub** [comment]
那个 modify.txt 是我用 fontforge 生成 svg 文件後，將更改部分加在末尾，再編譯成 ttf 當時，主要是要加入六十四卦，及更改半角的字母數字符號，以便中英文混排。

**Comment by creatxrgithub** [comment]
@SyaoranHinata 

請教：「去」字和「盍」的上部，兩者在小篆裏的字形是不一樣的，不知在一點字形裏有沒什麼象「丸丮」這樣的區別？

「盍」有異體「盇」，「嗑」有「㗐」，但我沒找到「瞌磕」的異體（至少是無法輸出，也不知有沒有）。

謝謝

**Comment by SyaoranHinata** [comment]
其實樓上的問題與之前各層無關，可以開新issue討論，方便其他朋友看到吶。

樓上所言非是，離去義之「去」，與「盍」之初文「去」，早於商代、於甲金文時期已合流。詳見季旭昇《說文新證》，可參考在下在「知乎」上回答〈「却」和「卻」哪個比較符合字源？〉的節錄：
https://www.zhihu.com/question/318956916/answer/644271322

及中文大學《漢語多功能字庫》之解說：
http://humanum.arts.cuhk.edu.hk/Lexis/lexi-mf/search.php?word=%E5%8E%BB
http://humanum.arts.cuhk.edu.hk/Lexis/lexi-mf/search.php?word=%E7%9B%8D

至於小篆，閣下謂其不一樣，應該是根據《說文》所錄之形。但《說文》「盍」字收形有誤，不合同時代的出土文字，詳見詹邯鑫《談談小篆》。而季旭昇已指出，「盍」的秦系文字在「大（蓋覆之形）」下從「𠙴形」，漢印徵再省爲「一」，而爲《說文》所自承，《說文》因而誤釋爲「从血大」。因此《說文》所錄之形非秦篆，乃省減後的漢印篆，而據其釋形亦有誤。

綜合考慮，「盍」形早已深入民心，古人的彫版與書法都有很多作「盍」形之例，此形大量出現在我們的取樣之中，而「盍」形有字理依靠，「盍」形頂部跟「去」合流是早於商代已然，我們無論從理、從習慣，皆以取「盍」形爲是。「盇」形只錄在Unicode有區分者，它也不是我們所取、所製者，只是沿用IPA明朝之形而已。

**Comment by SyaoranHinata** [comment]
誠然，如果有些形近偏旁，至今還有方法保持區分，大家容易接受這區分，而且是系統性的區分，而不是在甲字區分、在乙字相混，那麼我們通常都會保留這種區分。但含有「盍之初文」的字，只有寥寥幾個字有變「去」形爲「太」形之例，其量也不及作「去」形者；有些字如「闔、瞌」等，在我們的取樣裏，從「太」形者數量更接近零。而像「法」等同樣從「盍之初文」的字，更不可能易作「太」形。如是者，要是我們在少數字中取「太」形，反而更割裂字源，誠非可取之法也。
