### ISSUE TITLE
「汎」的撇筆起角處有多餘節點

### ISSUE THREAD

**Issue by haydenwong7bm** [ichitenfont/I.Ming#90]
<img width="476" alt="image" src="https://user-images.githubusercontent.com/51369959/221220423-f1da64a7-d712-4a45-b3ff-eaefadf80386.png">
<img width="476" alt="image" src="https://user-images.githubusercontent.com/51369959/221223069-d750a82b-d526-44b8-b20b-83fcc64dea9b.png">
如圖，比較二者。

**Comment by i-font** [comment]
感謝回報，日後將會更新。
