### ISSUE TITLE
日本新字體「売」偏旁與「賣」混同了

### ISSUE THREAD

**Issue by haydenwong7bm** [ichitenfont/I.Ming#92]
另參見#33。
![](https://user-images.githubusercontent.com/51369959/225932307-54db8167-f087-44a6-aba3-84c9afceb400.png)

**Comment by i-font** [comment]
一點明體原來是處理正體（繁體）中文裏會使用的字，後來因爲簡化字傳承形體的需求聲音龐大，才額外處理了一些簡化字。日本新字體的字形，若在一般正體中文裏不會使用，我們並不特別處理。
