### ISSUE TITLE
能否增加入简得繁的版本

### ISSUE THREAD

**Issue by ChellyL** [ichitenfont/I.Ming#93]
如题，
一点明朝拿来做阅读字体使用感受很不错，旧字形拿来读古代典籍很不错，
但大部分古代典籍都是默认简体，不知可否增加入简得繁的字体版本？
标点居中+旧字形+入简得繁，这样搭配古籍就很完美了

**Comment by lxgw** [comment]
可以试一下 [中文字体简繁处理工具](https://github.com/GuiWonder/TCFontCreator)。

**Comment by ChellyL** [comment]
> 可以试一下 [中文字体简繁处理工具](https://github.com/GuiWonder/TCFontCreator)。
> 
> 不过「入简得繁」很有可能会遇到「一简对多繁」的问题，虽然这个处理工具可以利用类似[「繁媛明体」](https://github.com/ayaka14732/FanWunMing)的技术处理「一简对多繁」，但碍于词库和字形（glyph）数量限制，效果可能不算太理想。

感谢介绍，试了一下效果还不错，放kindle上看一般的古籍已经够用~
