### ISSUE TITLE
希望能優化簡體字【金】偏旁（钅），簡體【金】偏旁（钅）與【全】太過與相似

### ISSUE THREAD

**Issue by shishamao** [ichitenfont/I.Ming#94]
一點明體簡體【金】偏旁（钅）與【全】太過與相似。比如圖中上爲一點明體【钊】，下爲康熙字典【𠛮】，兩字形幾乎完全相同。建議【钅】的第二筆改作橫。
![zhao](https://user-images.githubusercontent.com/112676634/227689077-62b18760-6f0b-4412-9035-e30ed0f4b55d.png)  
![quan](https://user-images.githubusercontent.com/112676634/227689087-21ecef30-98bc-4439-ab4e-ad29bea9f09b.png)

**Comment by Egnale99** [comment]
> 一點明體簡體【金】偏旁（钅）與【全】太過與相似。比如圖中上爲一點明體【钊】，下爲康熙字典【𠛮】，兩字形幾乎完全相同。建議【钅】的第二筆改作橫。
![zhao](https://user-images.githubusercontent.com/112676634/227689077-62b18760-6f0b-4412-9035-e30ed0f4b55d.png) ![quan](https://user-images.githubusercontent.com/112676634/227689087-21ecef30-98bc-4439-ab4e-ad29bea9f09b.png)


閣下午安。其實一點明體中「钅部件」、「全部件」並不相似，如下圖中「𠛮」、「钊」二字所示。
![一點明體中的「𠛮」、「钊」二字](https://user-images.githubusercontent.com/64576145/227696811-026f79df-a03c-4b95-90da-59e459917aa7.png)

《傳承字形部件檢校表》中解釋了「全部件」，亦提及「金部件」與「全部件」字源截然不同。
![《傳承字形部件檢校表》「全部件」說明](https://user-images.githubusercontent.com/64576145/227698083-fc086480-e74c-4766-a2fa-587187abed6f.png)

目前一點明體中「钅部件」的形體，似乎也是歷史略字中的一種常見的寫法。

「𠛮」(U+206EE) 字從「全」得聲，當從「全部件」。以下分別是武英殿版、同文書局版、渡部溫訂正版（掃描本）《康煕字典》中的「𠛮」字頭字形，可見前兩者都是誤形，只有渡部溫訂正版中的字形對了。
![武英殿版「𠛮」字頭](https://user-images.githubusercontent.com/64576145/227697694-927b750f-b6ad-4321-8d7d-f6ba6926f6c0.png)![同文書局版「𠛮」字頭](https://user-images.githubusercontent.com/64576145/227697699-1364f86a-15ef-4924-a85f-48cb6fba0448.png)![渡部溫訂正版「𠛮」字頭](https://user-images.githubusercontent.com/64576145/227697703-94b4fb36-e59d-4b95-aec6-addd9b375845.png)

**Comment by enderseven1** [comment]
一看就是偷懒把繁体金字旁的两点去掉了

**Comment by aikahiiragi** [comment]
> 一看就是偷懒把繁体金字旁的两点去掉了

請你不要胡說八道好不好？身為其中一個修改的義務作業人員，每一個我們所修改簡化字都是重新調整的，而不是偷懶！把繁體的「金」旁改成簡體時，不同部件的比例，「人」下各橫的位置和牽涉到的空間分佈，我們都細心調整，絕對不是隨便刪掉兩點就算！你眼睛不好，看不出這些修改，就不要胡亂說好嗎？

**Comment by aikahiiragi** [comment]
順便也說一說我個人對於修改一點明體的意見。

一點明體這個計劃或項目，就是爲了字理而出發，製作出既滿足大家對漢字字理的需求，也不違反今天正體（繁體）使用者的約定俗成，同時照顧到字型設計美觀的字型。

即使它是開源字型，大家怎麼改，我們管不了，可是我個人（不代表組織立場）還是認為，要是連我們這最基本的大宗旨都不認同，那麼就不要拿一點明體去改了，開源字型不少，拿別的去修改不可以嗎？為什麼要破壞本來一點明體致力維持的字理，例如把「者」改成「老頭」，把「告」改成不穿頭，把「真」改成新字形，把「犮」改成「又」，把「青」改成「月」，把「爭」改成「ク」等等等等，將一點明體破壞得面目全非、不知所謂、不倫不類！？

還有，修改的時候，為什麼有人會強行把肥瘦不同、比例不同的部件，整個直接拉肥拉瘦就算？拉完以後，各部件的粗幼不一，難看無比，修改的人不會去理會嗎？

一點明體被人破壞成這樣，而這個破壞的人還走來踩場亂噴，罵製作者「一看就是偷懶」，這是什麼態度！？

重申，這只是我個人（不代表組織立場）的想法，組織其他人也在事前不知道我的言論，如果有問題由我來負責，與組織無關。

**Comment by enderseven1** [comment]
> 順便也說一說我個人對於修改一點明體的意見。
> 
> 一點明體這個計劃或項目，就是爲了字理而出發，製作出既滿足大家對漢字字理的需求，也不違反今天正體（繁體）使用者的約定俗成，同時照顧到字型設計美觀的字型。
> 
> 即使它是開源字型，大家怎麼改，我們管不了，可是我個人（不代表組織立場）還是認為，要是連我們這最基本的大宗旨都不認同，那麼就不要拿一點明體去改了，開源字型不少，拿別的去修改不可以嗎？為什麼要破壞本來一點明體致力維持的字理，例如把「者」改成「老頭」，把「告」改成不穿頭，把「真」改成新字形，把「犮」改成「又」，把「青」改成「月」，把「爭」改成「ク」等等等等，將一點明體破壞得面目全非、不知所謂、不倫不類！？
> 
> 還有，修改的時候，為什麼有人會強行把肥瘦不同、比例不同的部件，整個直接拉肥拉瘦就算？拉完以後，各部件的粗幼不一，難看無比，修改的人不會去理會嗎？
> 
> 一點明體被人破壞成這樣，而這個破壞的人還走來踩場亂噴，罵製作者「一看就是偷懶」，這是什麼態度！？
> 
> 重申，這只是我個人（不代表組織立場）的想法，組織其他人也在事前不知道我的言論，如果有問題由我來負責，與組織無關。

對不起，我在此深表歉意。

**Comment by aikahiiragi** [comment]
> 【钅】寫成【全】這麼明顯的BUG還是更正一下比較好。雖然一點明體的【全】寫成「入王」，但寫成「人王」的【全】也不在少數。 下圖來自「[書法字典網](http://www.shufazidian.com/)」。

繼續是個人意見，不代表團隊。
上方已經清清楚楚解釋了，「亼土」的簡體金旁，是符合字理的寫法，絕對不是什麼所謂的bug！
相反，強迫遵從字理的一點明體，使用「𠂉一七」這種違背字理的寫法，如果一點明體真的依從，這才是真真正正的bug！
一點明體是明體，不是書法字形，不會像所謂「新字形」般認楷作母，在說明文件中已說明。
我個人認為樓上應該仔細閱讀，而不是貼出楷書行書的圖，強迫一點明體認楷作母，成為真真正正的bug！

**Comment by aikahiiragi** [comment]
總結一下：
- 「亼土丷」：是「金」字最有字理的寫法，一明點體在正常的正體（繁體）中文裏所使用的寫法。
- 「亼土」：是「金」字在簡化要求下維持「符合字理」這基本原則、基本底線的寫法，不可能再退讓。
- 「𠂉一七」：是違反字理的寫法，無論作為哪個字都講不通，不可能採用。
- 「入王」：是「全」字符合字理的寫法，「全」字沒有區分正體（繁體）與簡化字元，無論正簡都統一使用「入王」，「入」不可能與「人」混同。

**Comment by aikahiiragi** [comment]
> 主要是我們簡體字地區全字都是人字頭，本身簡體字就不符合字理，強行安排字理確實很違和，但我不反對

一點明體的最基本宗旨、最大考慮就是字理，在說明文件中已說明對簡化字的處理方法，
會製作簡化字傳承字形，純粹是因爲有多名來自簡化字地區的使用者要求，
而且他們的要求是具備字理的簡化字，而不是重蹈坊間簡化字字型覆轍、無視字理的字形。
如果想使用不理會字理、只顧簡化字無理字形，大可選擇其他字型，不應該強逼一點明體違背初心！

最後，如果真的真的要修改簡體「金」字旁，我唯一支持以下這種修改：
![image](https://github.com/ichitenfont/I.Ming/assets/37748071/277e120a-36b6-40c3-a07c-61c8ba68e7c0)

要是改成「𠂉一七」，我個人絕對大力反對，而且拒絕參與這種破壞性操作！

**Comment by enderseven1** [comment]
> > 主要是我們簡體字地區全字都是人字頭，本身簡體字就不符合字理，強行安排字理確實很違和，但我不反對
> 
> 一點明體的最基本宗旨、最大考慮就是字理，在說明文件中已說明對簡化字的處理方法， 會製作簡化字傳承字形，純粹是因爲有多名來自簡化字地區的使用者要求， 而且他們的要求是具備字理的簡化字，而不是重蹈坊間簡化字字型覆轍、無視字理的字形。 如果想使用不理會字理、只顧簡化字無理字形，大可選擇其他字型，不應該強逼一點明體違背初心！
> 
> 最後，如果真的真的要修改簡體「金」字旁，我唯一支持以下這種修改： ![image](https://user-images.githubusercontent.com/37748071/244940260-277e120a-36b6-40c3-a07c-61c8ba68e7c0.png)
> 
> 要是改成「𠂉一七」，我個人絕對大力反對，而且拒絕參與這種破壞性操作！

![image](https://github.com/ichitenfont/I.Ming/assets/81961525/f9ab48c1-169a-451b-aff4-a21f5991d1e8)

我觀察了一下一點中的金字旁，左邊是簡體金字旁，右邊是如我所說“簡單去掉兩點”，中間是繁體金字旁，確實如您所說“細節有調整過”，我發表我的個人意見，簡體字本身已經非常破壞字理，對簡體字使用字理，可謂是牛頭不對馬嘴，一定要按照字理，我覺得大可不必支持簡體字。

**Comment by enderseven1** [comment]
我個人認為，簡單去掉兩點雖然不能肯定的說像“金”字，但至少不那麼像“全”字，我覺得可以適當參考一下

**Comment by aikahiiragi** [comment]
還是那句，不同字型本來就有不同定位、宗旨、初衷，
一點明體的定位、宗旨、初衷，就是盡力追求字理。
不認同這一點的，就不要使用一點明體。
因爲不考慮字理的字型在這世界上多的是。

否則，要是一點明體今天真的為了你們這兩個討厭字理的人而改了，你們的無理強逼得逞了，
那麼當初有「盡量符合字理的簡化字」這個需求的使用者，不就是被一點明體背叛了嗎！？
樓上你們兩人怎樣去面對他們！？還是你們根本無視他們不覺得要面對！？

**Comment by enderseven1** [comment]
> 還是那句，不同字型本來就有不同定位、宗旨、初衷， 一點明體的定位、宗旨、初衷，就是盡力追求字理。 不認同這一點的，就不要使用一點明體。 因爲不考慮字理的字型在這世界上多的是。
> 
> 否則，要是一點明體今天真的為了你們這兩個討厭字理的人而改了，你們的無理強逼得逞了， 那麼當初有「盡量符合字理的簡化字」這個需求的使用者，不就是被一點明體背叛了嗎！？ 樓上你們兩人怎樣去面對他們！？還是你們根本無視他們不覺得要面對！？

我自身並不討厭字理，我不排斥字理，我修改是希望它盡量符合大陸地區的字形規范，我支持正版的一點明體，絕對沒有討厭字理的意思。

**Comment by aikahiiragi** [comment]
> 我自身並不討厭字理，我不排斥字理，我修改是希望它盡量符合大陸地區的字形規范，我支持正版的一點明體，絕對沒有討厭字理的意思。

當所謂「大陸地區的字形規范（範）」違背字理時，爲什麼要強逼一點明體去「盡量符合」！？
要「盡量符合大陸地區的字形規范（範）」的話，這就絕對不是一點明體！
不要再強逼一點明體做出違反宗旨、違反初心了，好嗎！？
坊間有這麼多字型都「盡量符合大陸地區的字形規范（範）」，為什麼你不選用它們，要強逼一點明體這樣做？
如果你的強逼成功，當初有「盡量符合字理的簡化字」這個需求的使用者，不就是被一點明體背叛了嗎！？

**Comment by enderseven1** [comment]
> > 我自身並不討厭字理，我不排斥字理，我修改是希望它盡量符合大陸地區的字形規范，我支持正版的一點明體，絕對沒有討厭字理的意思。
> 
> 當所謂「大陸地區的字形規范（範）」違背字理時，爲什麼要強逼一點明體去「盡量符合」！？ 要「盡量符合大陸地區的字形規范（範）」的話，這就絕對不是一點明體！ 不要再強逼一點明體做出違反宗旨、違反初心了，好嗎！？ 坊間有這麼多字型都「盡量符合大陸地區的字形規范（範）」，為什麼你不選用它們，要強逼一點明體這樣做？ 如果你的強逼成功，當初有「盡量符合字理的簡化字」這個需求的使用者，不就是被一點明體背叛了嗎！？

我並不強迫一點明體這樣做，我喜歡字理，若是在我自己的私人網站中我會使用一點明體的原版。我只在我自己的修改中遵循大陸字形規範，而此修改是為了面向大眾，我做的只是基於一點明體的修改，我承認我的表述有誤，我在此深表歉意。

**Comment by i-font** [comment]
「金」旁簡化字的定形，在我們團隊中經過多番討論，各位在上方所言的各種觀念，都已在討論中細思過。

「金」旁原字和簡化偏旁的字理，藍歌君已解釋過。而一點明體處理簡化字的原則與考慮，我們已在《傳承字形部件檢校表》的〈附錄三：俗訛簡字處理原則與方法〉中詳細說明過。只有目前一點明體的定形，符合我們的原則與考慮。Shishamao閣下與島田閣下的建議，都有與我們原則相牴牾的地方。

我們目前的定形，也絕不構成不同部件的混同。「全」字本身从「入」，在傳承字形中絕不會相混。

要是連非傳承字形的同形也要避免，這可會導致削足適履的情況，對許多既有字形也會構成嚴重問題，並不可取。

綜合上述，我們並不會修改目前的定形。感謝各位的意見。
