### ISSUE TITLE
有没有想过给「配」字「封口」？

### ISSUE THREAD

**Issue by silascript** [ichitenfont/I.Ming#95]
配：「酒色也」。「配」字右半边实则是省了「人」的「色」字。而「色」本是「人節」，就是在人的眉间部分的气色，这里的气色与人体内的状态相关，就如「符節」的两半，故称「人卪」。「配」字右半边的「卪」省了点后，看起来形如同「巳」一样。但现在诸字体，都将其写成「己」，这非常有问题。当然像《康熙字典》，其实也是有点「暧昧」：

![康熙字典_配](https://user-images.githubusercontent.com/13313323/229888231-3c8a5510-4328-4b7a-87aa-cc60f6473181.png)

当然在《洪武正韵》中就存在了：
![洪武正韵_配_妃](https://user-images.githubusercontent.com/13313323/229888381-84f6fa9c-f413-4c1c-9eac-aeb8f9f3f34d.png)

这口要封不封的，应该是明清两代字书编纂者的纠结！

时间往前推，《中原音韵》就比较直接了当，都是封口：

![中原音韵_配](https://user-images.githubusercontent.com/13313323/229888803-e94f9b6d-f125-489b-9bf3-4fa334be90b5.png)

![中原音韵_妃](https://user-images.githubusercontent.com/13313323/229888866-755cbe46-843a-487b-a305-4f98503743d8.png)

宋本《广韵》的重要一系「鉅宋本」也是封口的：

![鉅宋广韵_配_妃](https://user-images.githubusercontent.com/13313323/229889857-6f40bfe0-8b6a-4ab9-831e-491cdf598df1.png)

省了点并变了形的「卪」长得跟「巳」一样，而又因为「已」源于「巳」，写成「已」我也勉强能接受，但「己」，这就完全搭不上关系，真的受不了。所以基于传统，应该将这「配」字的「己」修正为「巳」--至少是「已」状态！

**Comment by i-font** [comment]
「配」字右旁並不是「省了『人』的『色』字」，翻査「配」和「妃」等相關字，從來沒有作「色」或取自「色」省的證據。《說文》的「酒色也」不一定是「配」的初義（中大《漢多》：「『配』字的初義未有定論，一說初義當為伴飲、伴食(金文形義通解)，一說當與酣、釂諸字義近(李孝定)，一說當為配偶之義，從『妃』省聲(陳劍)。一說義為釀酒調配得宜，酒色良好之意(季旭昇)。」只有季說支持《說文》解釋）。即使是，也不見得「配」字的構形就是从「色」而來。漢字本義之闡釋，不等於漢字構形的組成原因。

「配」最早的寫法是从「㔾」，這個「左酉右㔾」的字形，今天日常生活中已經少見，但有時還在書法作品看到，已收進一點明體異體中。到《說文》變成「己聲」或「妃省聲」，是一種聲化的過程，可見「配」字右旁作「己」也有其字理，絕非閣下所言的「完全搭不上關係」。魏《三體石經》、唐《開成石經》都已清楚地寫作「己」，亦可見從「己」之形已有相當的歷史。一點明體取形，是平衡字理與約定俗成的。當「左酉右㔾」與「左酉右己」皆有字理支持，而後者在約定俗成方面遠勝前者時，一點明體自當取後者爲主。

至於「己、巳、已」，這三字本身其實到了很晚期才很明確的區分。又因爲聲韻有其相通之處，作爲聲旁時，有些字互換也合理，久而久之也擴散起來，造成「己」聲旁與「巳」聲旁成爲可以交換的異體構件。連明顯跟「己」聲更近的「杞」、「紀」等字也有从「巳」或「已」的寫法，並且可以在閣下所擧的字書中找到。再者，閣下採用《漢典》所錄的康熙字形圖片，但這版本的圖片不一定全都可靠，無論[是同文本書影還是武英殿本書影](https://www.kangxizidian.com/kxhans/%E9%85%8D)，《康熙》中的「配」字右旁也是清楚地寫作「己」的。閣下的擧證並沒反映到「配」字的全貌。

**Comment by silascript** [comment]
> 「配」字右旁並不是「省了『人』的『色』字」，翻査「配」和「妃」等相關字，從來沒有作「色」或取自「色」省的證據。《說文》的「酒色也」不一定是「配」的初義（中大《漢多》：「『配』字的初義未有定論，一說初義當為伴飲、伴食(金文形義通解)，一說當與酣、釂諸字義近(李孝定)，一說當為配偶之義，從『妃』省聲(陳劍)。一說義為釀酒調配得宜，酒色良好之意(季旭昇)。」只有季說支持《說文》解釋）。即使是，也不見得「配」字的構形就是从「色」而來。漢字本義之闡釋，不等於漢字構形的組成原因。
> 
> 「配」最早的寫法是从「㔾」，這個「左酉右㔾」的字形，今天日常生活中已經少見，但有時還在書法作品看到，已收進一點明體異體中。到《說文》變成「己聲」或「妃省聲」，是一種聲化的過程，可見「配」字右旁作「己」也有其字理，絕非閣下所言的「完全搭不上關係」。魏《三體石經》、唐《開成石經》都已清楚地寫作「己」，亦可見從「己」之形已有相當的歷史。一點明體取形，是平衡字理與約定俗成的。當「左酉右㔾」與「左酉右己」皆有字理支持，而後者在約定俗成方面遠勝前者時，一點明體自當取後者爲主。
> 
> 至於「己、巳、已」，這三字本身其實到了相當晚期才很明確地區分。又因爲聲韻有其相通之處，作爲聲旁時，有些字互換也合理，久而久之也擴散起來，造成「己」聲旁與「巳」聲旁成爲可以交換的異體構件。連明顯跟「己」聲更近的「杞」、「紀」等字也有从「巳」或「已」的寫法，並且可以在閣下所擧的字書中找到。再者，閣下採用《漢典》所錄的康熙字形圖片，但這版本的圖片不一定全都可靠，無論[是同文本書影還是武英殿本書影](https://www.kangxizidian.com/kxhans/%E9%85%8D)，《康熙》中的「配」字右旁也是清楚地寫作「己」的。
> 
> 總結而言，閣下的擧證並沒反映到「配」字的全貌。「配」字的有理字形不只一種，但「左酉右己」是其中之一。
> 
> P.S.像人跪坐之形的那個字，獨用時通常隸定作「卩」，作偏旁時也常作「㔾」或「𰆊」形。古書有時也增點作「卪」，但不宜反過來說「卩」是「卪」省了點。


我明明给出了《洪武正韵》《中原单韵》及钜宋本的《广韵》的”配“字(《三体石经》和《开成石经》都是经学书籍，非字书或韵书，何况”小学“领域，汉唐根本比不过明清，何况汉时真书根本没出现，更不说很多问题字是汉开始的，如”眾“的”血“头，那一撇就是汉人隶书起字起得重了；而如”鬥“旁，秦汉至唐宋，都混成”門“字（这就是为简体”闹“是门字），直到明清才”纠正“成”鬥“，要说约定俗成这不更约定俗成），明明就是”已“或”巳“占多数,你选择性无视，偏揪着一个《康熙字典》不放，而且还拿同文本或英武殿本的来举例，这人两本都是”己“又如何，论年代比得过《中原音韵》《洪武正韵》这些更早的韵书吗？再说了《康熙字典》不也引《说文》”酒色“之义，你怎么又双标地选择性无视--还有渡部温版的，人家可是取”巳“”已“这一系的，怎么不见你提，因为人家不”靠谱“吗？人家怎么说也是康熙字典著名校勘者啊--而且日本人明显更喜欢”己“，如”包“字日本就是取的是”己“，类似的还有”巷“，但偏偏渡部温版是取了”巳已“这系？

还有"己"与“巳已”并不同源。“己”，是绳弯曲之义，后引申出”计事计时“及”约束“之义；而“巳已”与“子”同源，而且声更近，s/z同样的舌尖音，上古是”心母“或”邪母“；而“己”是舌面后音，是”见母“字，两个发音上根本天差地别，在发音上根本不可能混用，发音异同而发生混用只能是属于误写，如东汉时将”汜“误写成”氾“，所以三国那个货，到底是”郭汜“还是”郭氾“？（氾还两音，一个地名或水名，念二声；另一个是”氾滥“念四声）。硬说有关系，就是“巳”其中一个起源“蛇虫之形”跟“绳曲之形”都是弯曲的；但“巳”应该更多的是与“子”亲缘性更高，而上古”巳“是当”祀“的来用。而”配“中的”巳“即使不是”色“字省”人“，那也是跟人有关：”配字從「酉」從「卩」，象人坐在酒尊之側，疑本義是伴飲，引申表示匹配。“--香港中文大学的「漢語多功能字庫」。用”己“根本没法解释"配"字，用”巳“至少可以解释”酒色“或”伴饮“。
而且从演化上看，只能是”巳“”误写“成”己“，绝少会出现反过来的情况，因为在观察先秦”配“字，大部分是”巳“形，”己“形明显少得多，而还有一总分少数”巳“形写法，其”巳“的口写得非常窄，跟”己“极为接近，可以推测”配“中”巳“写成”己“完全就是一种快速书写状态下的”简化“，所以只能是”巳“写成”己“，不可能反过来。

相似的”起“字也是”己“和”巳“两系写法。而”起“能写”巳“用的是”巳“的引申义”停止“，即坐着或躺着状态停止，进行到要走的状态，即”起本發步之偁“（《说文解字注》），这引申义的”巳“都能用，而”配“中的”巳“，明显比”停止“这个引申义更近源义，宁可用一个无法释义的”己“，也不用至少能释义的”巳“，怎么都说不通(从西周至战国那些”起“字，”己“旁出现比”配“字的”己“机率高多了，”起“能写成”巳“，”配“却不行，非常的荒谬。)--也不是什么”约定俗成“能解释的--真追求"约定俗成"，你们就不会弄这个字体了，你们这字体比市场上大部分的具有”泥古“倾向的字体都还要泥古，现在反倒追求什么”平衡“。

**Comment by i-font** [comment]
請閣下自重，注意禮儀。我們正常回覆閣下，閣下有權同意或不同意，卻不應該撒野謾罵。要是閣下今後繼續撒野謾罵，也不肯爲這樣的撒野道歉，我們將拒絕再理會閣下。

一點明體依照《傳承字形檢校表》製作。《傳承字形檢校表》中，我們多番申明，我們是從字理與約定俗成間取平衡，字形都先從所指出的各種來源中取樣並觀察常見度，再衡量字理，有必要時則以抽樣詢問的形式進行約定俗成測試。過去也有許多舊issue，是有用戶建議我們把一些字改形，但其建議有違約定俗成，我們便拒絕的。若要建構一套空中樓閣字形，請另覓高明。這是我們一貫的宗旨，也多番說明清楚。

閣下沒有好好閱讀《檢校表》和我們的說明，不要緊，我們在回應中禮貌地、大方地跟閣下說。卻沒想過遭到閣下撒野，謾罵我們什麼「真追求"约定俗成"，你们就不会弄这个字体了，你们这字体比市场上大部分的具有”泥古“倾向的字体都还要泥古，现在反倒追求什么”平衡“。」請閣下停止思覺失調般的個人腦補，正視現實。

我們回覆時，以《康熙》作說明，並不是什麼「偏揪着一个《康熙字典》不放」，一來因爲《康熙》是傳承字形中一個非常重要的標準，二來《康熙》也是閣下自己擧出的第一個例子——而閣下的第一個擧證就已犯下了很基本的錯誤。《康熙》的母本是殿本，殿本是最權威也最反證編者原意的版本。閣下不以殿本爲是，卻擧其他翻抄本和翻刻本出來，足見閣下欠缺版本學知識。而日人凡「巳」都改作「己」，是日本推行他們的漢字簡字之事，詳見何群雄：《漢字在日本》一書，與我們的擧證無關。

閣下又說《開成石經》只是經學書籍，跟小學領域無關，也足見閣下的無知。《開成石經》採用的字形，是嚴格依從顏氏《字樣》和《干祿字書》的後繼字樣標準——《五經文字》及《九經字樣》而寫成。因此它向來是硏究字形、字樣的學者重視的材料。眞正硏究這門學問者，沒有人會像閣下般對其如此輕蔑。

至於閣下的其他例子，我們並沒有責任要逐一回覆，尤其是當後面的例子也只是重覆或類同的。《洪武正韻》、《中原音韻》以及《廣韻》都是韻書，不是說它們的字形不重要，但人們主要在意其音韻問題，要論字樣，一般更看重同時代的字樣學著作。而類似的例子擧再多，也跟我們的取樣無關。

再說閣下對字理的分析，摻雜了一些違反學術的個人看法，直白點兒說，就是民科推想，經不起學術證據支持。例如「起」字只是形聲字，不是會意字，其「巳」旁就只是聲符，在「起」字的構字中並沒有表示什麼「停止」之意義。秦系文字从「巳」聲，楚系文字卻从「己」聲，可見「巳」、「己」上古音聲母雖然不同，但作聲旁時確實有互換之實例，絕非不可能。「配」字从「己」聲，在聲母上是不夠理想，但若从「妃省」聲，則很理想。同樣地，以「巳」作聲符的字，在構理上並非以「巳」表義，閣下卻一再聲稱形聲字的聲符表義。

而《說文》的說法，我們之前已解釋過，「酒色也」並不是指「配」的構形，《說文》直接分析「配」的構形是「从酉，己聲」。說什麼「双标地选择性无视」，這個人可是閣下。閣下一再無視《說文》的眞正析形，卻把其釋義「酒色也」私自移花接木地視爲「配」字應从「巳」的支持，引伸出一大堆謬論。再者，「色」字下方是「㔾」不是「巳」，「㔾」是跪着的人，「巳」是還在襁褓裏的嬰兒，嬰兒根本不可能伴飲，即使寫作「巳」，於會意上也無法成立。要是有人眞的很想把「配」寫成會義字，也應該用「一點明體異體」中从「配」从「㔾」的寫法，而不是主張从「巳」。
