### ISSUE TITLE
我想对字体进行修改

### ISSUE THREAD

**Issue by enderseven1** [ichitenfont/I.Ming#97]
我想对字体进行修改，以便呈现我更喜欢的字形，我将仓库地址设在我账户下的I.Ming-Mizuki内，若您不同意我进行修改，请联系我删除。Email：2068651347。

**Comment by lxgw** [comment]
这款字体是在 IPA Font License 1.0 许可条款下发行的，应该可以修改吧。

**Comment by SyaoranHinata** [comment]
本字型是開源字型，歡迎依從 IPA Font License 1.0 授權條款自由修改。
唯修改後請讓大家知悉，字型名字請不要使用「一點」（I.），
在修改的說明文件中，若不是更正我們的疏漏錯訛，而是作與我們方向或理念不同之修改，請不要隨便使用「修正」、「更正」、「撥亂反正」等字眼去描述。
有勞了，謝謝！

**Comment by enderseven1** [comment]
是的，我承認我大幅度的修改了一點明體，背離了一點的方向與理念，若有違和感的部件可以向我發送issue提出，而不是以牙還牙。況且，一點中的簡體金字旁乍一看確實感覺像是繁體簡單去掉了兩點，我不清楚你們背後的艱辛，我在此深表歉意。我自身也沒有太多時間為我的修改品做太多的矯正，你們可以將問題反饋給我，我會在日後一一更正。我個人很喜歡一點明體的風格，我的行為也是希望能為大陸地區的公文等所應用，若你們強烈反對，我會將其刪除，謝謝理解。

**Comment by enderseven1** [comment]
再者，我的字體中大多數修改還是來自於一點明體異體，例如“鑿”的簡體，戔的簡體，凿在正體中下部為臼，異體為凵，我選擇了異體，戋正體為三橫，異體為兩橫，我選擇了異體。

**Comment by aikahiiragi** [comment]
樓上，我不是為了以牙還牙，而是以我義務幫忙做一點明體的開源工作時所知，一點明體絕對不會像現在你這樣做。你卻說這是「I.Ming ( I.明體 / 一点明朝体 / 一點明體 ) 水木修改版」，彷彿一點明體是可以這樣呈現的，我敢肯定這絕對違反一點明體的主旨。

我在上方已舉出了一些嚴重超過低線的部件，請不要避重就輕。如果單單只是改變「凿」「戋」這些部件，還未至於違背一點明體。可是你卻改了「者」「告」「真」「犮」「青」「争」等等，我敢肯定這絕對僭越了一點明體堅守的底線。

你知不知道，當年那些想傳承字形消失、完全被「新字形」取替的網軍的嘴臉和言論？「青」字就是其中一個他們重點打擊的字形，他們把有字理的從「丹（円）」的「青」用紅圈圈起來，說它是「錯字」，說沒有字理的從「月」的「青」才是正確寫法，而且更不容許別人反駁，別人反駁就刪去反駁言論。

一點明體是捱着多少這些攻擊堅持站下去的，你卻把一點明體變成他們要的形狀。

**Comment by enderseven1** [comment]
> 樓上，我不是為了以牙還牙，而是以我義務幫忙做一點明體的開源工作時所知，一點明體絕對不會像現在你這樣做。你卻說這是「I.Ming ( I.明體 / 一点明朝体 / 一點明體 ) 水木修改版」，彷彿一點明體是可以這樣呈現的，我敢肯定這絕對違反一點明體的主旨。
> 
> 我在上方已舉出了一些嚴重超過低線的部件，請不要避重就輕。如果單單只是改變「凿」「戋」這些部件，還未至於違背一點明體。可是你卻改了「者」「告」「真」「犮」「青」「争」等等，我敢肯定這絕對僭越了一點明體堅守的底線。
> 
> 你知不知道，當年那些想傳承字形消失、完全被「新字形」取替的網軍的嘴臉和言論？「青」字就是其中一個他們重點打擊的字形，他們把有字理的從「丹（円）」的「青」用紅圈圈起來，說它是「錯字」，說沒有字理的從「月」的「青」才是正確寫法，而且更不容許別人反駁，別人反駁就刪去反駁言論。
> 
> 一點明體是捱着多少這些攻擊堅持站下去的，你卻把一點明體變成他們要的形狀。

我敬佩你們，可我既然身處大陸地區，就不得不遵從大陸地區的規定，我也是迫於無奈，不然我也想直接用原版。我希望用一點明體與海報、出版等公共領域，這些也迫不得已。

**Comment by i-font** [comment]
回覆之前，首先請藍歌君注意一下，無論多不同意，但也請說話留三分，不要太衝，避免讓人感到冒犯。雖然你再三說明是個人意見，但畢竟是其中一位貢獻的義工，其他有心抹黑我們的人就會拿來做文章，這點是我們控制不到的。

回覆島田樓主，先跟閣下說聲抱歉。早前我們項目發起人一郎回覆過閣下可以修改，一來是基於本項目採用開源授權，只要遵從授權，其他人就確實有修改再發佈之權利，我們沒理由違反；二來是當時一郎審視過閣下的修改，那時候應該只修改了「卖」旁、「戋」旁和少量個別簡化字，儘管有違我們的宗旨，不過我們也明白「𧶠」旁、「戋」旁跟現行簡化字在視覺觀感上確實有點分別；三來當時一郎也提出了閣下要遵守的事項，我們認爲要是閣下都做到，那麼應該問題不大的，不會讓我們被混淆的。然而現在再看，閣下沒有遵從一郎回覆時提出閣下要遵守的事項，修改的字也聲得上是翻天覆地，我們不得不向閣下指出，以維護我們最基本的底線。

第一，開源字型雖然允許修改，但修改版本必然要使用其他名稱，不得把人家的標識名稱放在自己的字型名稱或項目名稱裏，以免混淆。有些開源字型的授權條款中甚至會直接把此要求寫進去。即使沒明文寫進去，這也是開源字型界共同遵守的基本規則。因此一郎回覆時，也明確要求閣下要符合這點。但現在我們看到閣下明顯違反着，閣下把「I.Ming」作爲項目名字的一部份，稱爲「I.Ming-Mizuki」，也在項目名字的中文裏放着「一点明体」四字，稱其爲「水木明体（一点明体水木修改版）」。這徹底地違反了前述之規則。我們嚴正要求閣下馬上移除，我們嚴正聲明並不允許閣下使用任何「I.Ming」、「I.（名稱）」、「一點明體」、「一點（名稱）」之命名。否則，依開源字型的慣例，大家就會視閣下的版本爲一點明體認可的、同意的其中一個版本。

第二，在遵守了第一點以後，雖然說在授權條款上並沒有限制閣下不可以作怎樣的修改，但在本項目的建立上，我們團隊之所以一直地努力着，爲的是捍衛和爭取傳承字形的使用權，並推廣傳承之形是正字的正確觀念，不希望傳承字形被無知的人罵作什麼「錯字」云云。尤其是那些發起過針對傳承字形的網絡批鬥運動的人，曾經攻擊過「青」、「直」、「⻞」、「羽」、「令」、「⺬」、「𧶠」等部件，我們格外不希望被修改。雖然閣下在法理上有權不聽我們的，但我們很希望閣下能尊重我們團隊的立場。

我們感謝閣下喜歡一點明體。可是，閣下這項目所希望做的事情，實在太違反我們的宗旨和立場。我們還是希望閣下能夠撤回這項目。大陸地區新字形的所謂「『規』『範』」，不諱言說，其實實在有太多自相矛盾的與經不起字理考驗的地方。要是閣下喜歡露芒、橫捺、不避重捺等字形特色，其實大可以從「IPA明體（IPA明朝）」着手修改，這是一點明體的母項目，擁有一點明體目前所擁有的這些字形特色。閣下在修改IPA明體時，若遇到其不足之處，而一點明體正好合用，我們也不介意閣下將一點明體合用的字元匯入到閣下的字型檔中。那麼，閣下依然可以實現閣下這項目所希望做的事情，但不至於讓我們團隊感到心血被破壞、宗旨與底線被踐踏之感。

最後，我們也有朋友拍到在大陸地區直接使用一點明體的實例，包括書籍、包括在公眾地區的展示。其實大陸地區的規定是否眞的如閣下所說般死板？

**Comment by enderseven1** [comment]
啥時候能做個一點黑體？

**Comment by enderseven1** [comment]
在此告訴一點明體的每一位負責人：水木明體已于今年五月十三日推出更新的v10.1版本，v10.1是完全重做的，不再使用一點明體作為母項目，改為霞鶩致宋CL，此前使用一點明體的版本已經全部刪除，僅保留了當時最新版本的v10.0以備特殊需求，可以視為與一點明體沒有主要關係（v10.1及以後版本僅在一點明體中借用了部分字形）。在此鄭重向曾經冒犯過的一點明體項目及其負責人致歉。至於當時所謂“一點明體水木修改版”之名號，實為當時並未確定我的項目的正式名稱，由於當時我在開源字體圈是初來乍到，難免會有一些疏忽，現在我已經這些事情全部改正，也請藍歌及一郎君不再提及這些事情。水木明體從開發之初就與一點明體不屬於同一個出發點，我的字體目的在於“反楷化”，一點明體目的在於“傳承字形”，若各位有任何意見，歡迎向我反饋。
